Feature/14giyong
wecode-bootcamp-korea/westagram-backend pull request #114
Opened 2020-11-09 02:33 UTC by amusesla

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-10 11:48 UTC, jamessoun93 requested changes

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/views.py
> +            comments = Comment.objects.prefetch_related('post_id')
- 가독성을 위해 `=` 을 기준으로 정렬해주세요.
- 여기서 `select_related()` 와 `prefetch_related()` 를 사용하신 이유와 해당 메소드들을 사용하면서 생긴 변화를 답글로 설명해주시겠어요?

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/views.py
> +                    'comment' : [
`comment` 라는 key 의 value 로 list가 들어가니 key 는 복수형으로 지어주세요.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/views.py
> +            return JsonResponse({'message': 'KEY_ERROR'}, status = 400)
```suggestion
            return JsonResponse({'result': context}, status = 200)
        except KeyError:
            return JsonResponse({'message': 'KEY_ERROR'}, status = 400)
```

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/models.py
> +    user_created = models.DateTimeField(auto_now_add = True)
앞 부분은 `=` 을 기준으로 정렬해주었을때 가독성이 좋아지지만, 뒤쪽 kwargs 부분들은 전부 동일하게 정렬해주면 가독성이 좋지 않습니다. 
```suggestion
    username     = models.CharField(max_length = 30)
    email        = models.EmailField(max_length = 50)
    password     = models.CharField(max_length = 100)
    phone_number = models.CharField(max_length = 30)
    user_created = models.DateTimeField(auto_now_add = True)
```

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/models.py
> +        db_table = 'user'
테이블명은 복수로 지어주세요.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/models.py
> +
테이블명은 복수로 지어주세요.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/westagram/urls.py
> +    path('post/', include('post.urls')),
앞서 언급드린 위코드 컨벤션대로 수정해주세요.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/urls.py
> +    path('login/', LogIn.as_view()),
여기도 위코드 컨벤션에 맞게 수정해주세요.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/urls.py
> +from django.conf import settings
django.conf 사용 굳입니다 😉

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/urls.py
> +from django.conf.urls.static import static
이 부분은 불필요한 import 문이겠죠?

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/views.py
> +            return bool(re.search('^[0-9]{3}-[0-9]{3,4}-[0-9]{4}$', phone_number))
- 이런 validation 로직들을 재사용하기 위하여 따로 함수로 작성해주신 것은 너무 잘 하셨습니다만, view 클래스 내에 메소드 안에서 선언해주니 코드가 지저분할 수 밖에 없고 어디서 선언문인지 어디가 호출문인지 확인하기가 어렵습니다. 이런 함수들은 다른곳에서도 사용할 목적으로 작성한 것이니 `utils.py` 같은 파일로 따로 빼서 함수만 import 해서 사용해주시면 훨씬 가독성이 좋아질 수 있습니다.
- 조건문에서 사용하려고 `bool()` 로 감싸주셨지만 이 부분은 불필요합니다. 다른 언어와 마찬가지로 파이썬에도 `Truthy`, `Falsy` 값들이 존재하고 이들이 조건문에 조건으로 들어가게 되었을때 자동으로 `boolean` 값으로 처리가 됩니다.
- 그리고 문제는 없지만 이런 validation 목적이라면 `re.search()` 보다는 `re.match()` 가 더 상황에 알맞는 메소드라고 생각합니다.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/views.py
> +            return JsonResponse({'meesage':'INVALID_PHONE_NUMBER'}, status = 400)
앞서 말씀드린 `Truthy`, `Falsy` 값에 대해 이해하셨다면 이 부분을 어떻게 바꿔볼 수 있는지 고민해보시고 한번 수정해보세요!

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/views.py
> +            return JsonResponse({'message':'INVALID_INPUT'}, status=400)
이런 조건이 필요한 이유가 있을까요?

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/core/utils.py
> +    return wrapper
👍 👍 👍

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/core/utils.py
> +from django.core.exceptions import ObjectDoesNotExist
`ObjectDoesNotExist` 는 사용하지 않기때문에 불필요한 import 겠네요!

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/views.py
> +from django.shortcuts import render
쓰지않는 `render` import 문은 없에주세요.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/views.py
> +            return JsonResponse({'message': 'Post has been created successfully!'}, status = 201)
`content` 유무에 따라 아주 살짝 다른 `create()` 문을 두 번 쓰신 걸 볼 수 있는데, 이런 경우 항상 이 코드를 어떻게 줄일 수 있을까에 대한 고민을 꼭 해보셨으면 좋겠습니다.

- 우선, `posts` 테이블에 `content` 컬럼은 `null=True` 라서 파이썬에서 해당 컬럼에 `None` 이 들어가도 `NULL` 로 처리됩니다. 
- 따라서 `content` 에 대한 내용이 들어온다면 `content` 에 저장해주고, 들어오지 않는다면 `None` 을 저장해주고 그대로 `create()` 문을 부르셔도 문제가 없다는 뜻이고, 지금과 달리 `create()` 문 하나로 두 조건 다 처리가 가능해지게 됩니다.

위 내용을 토대로 변경해서 수정해보세요!

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/views.py
> +                ]
코드에서 반복적으로 `qs` 혹은 `cmt` 같은 저는 무슨 의도로 쓰셨는지 알겠지만 이해하기 힘들 수 있는 변수명들이 보입니다. 원활한 협업을 위하여 한눈에 보기 쉬운 변수명을 선택해주세요.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/views.py
> +                qs = Comment.objects.filter(post_id = data['post_id']).prefetch_related('author')
어짜피 91번째 줄에서 `data['post_id']` 부분에서 `KeyError` 가 발생한다면 잡히게 되는데, `if` 문으로 해당 로직이 감싸져있을 필요가 있나요?

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/views.py
> +                    'parent'       : cmt.parent_idi
```suggestion
                    'parent'       : cmt.parent_id
```

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/views.py
> +                    'parent'       : cmt.parent_idi
이런 오타가 있으면 호출 결과가 제대로 나오지 않았을텐데, 꼭 자세히 확인하고 올려주세요.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/post/views.py
> +            return JsonResponse({'meesage':'SUCCESS'}, status = 200)
위의 리뷰내용과 같습니다. 수정해보세요~

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/views.py
> +                return JsonResponse({'message':'phone_number already exists!'})
여러개의 `OR` 조건으로 `filter` 를 처리해주는 `Q 객체`를 사용하면 이 부분이 훨씬 간결해질 수 있습니다. `장고 Q 객체`에 대해 찾아보신 후 적용해보세요.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/views.py
> +                user = User.objects.get(phone_number = data['key'])
여기도 Q 객체를 활용 가능합니다.

2020-11-10 11:48 UTC, jamessoun93 commented on students/14th/team9/giyong-gim/user/views.py
> +                token        = jwt.encode({'id' : user.id}, secret, algorithm = 'HS256')
어떤 알고리즘을 사용해 jwt 인코딩을 했는지도 같이 숨겨주시는게 좋습니다.

2020-11-10 13:43 UTC, amusesla commented on students/14th/team9/giyong-gim/post/models.py
> +    image        = models.URLField()
수정했습니다!

2020-11-10 13:44 UTC, amusesla commented on students/14th/team9/giyong-gim/post/models.py
> +    post_created = models.DateTimeField(auto_now_add = True)
수정했습니다.!

2020-11-10 13:45 UTC, amusesla commented on students/14th/team9/giyong-gim/post/models.py
> +    comment_created = models.DateTimeField(auto_now_add = True)
수정했습니다!

2020-11-10 13:46 UTC, amusesla commented on students/14th/team9/giyong-gim/post/urls.py
> +    path('cmt/', CommentView.as_view()),
cmt/ 를 comment/로 수정하였습니다!

2020-11-10 13:47 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +from .models import Post, User, Comment
수정하였습니다.

2020-11-10 13:49 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +                    'parent'       : cmt.parent_idi
수정전 코드가 올라갔습니다 ㅜㅜ 죄송합니다 !!!

2020-11-10 13:57 UTC, amusesla commented on students/14th/team9/giyong-gim/user/views.py
> +                token        = jwt.encode({'id' : user.id}, secret, algorithm = 'HS256')
말씀주신대로 my_settings.py 파일에 ALGORITHM = 'HS256' 작성해서 import 하였습니다!

2020-11-10 15:40 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +    def get(self, request, *args, **kwargs):
수정했습니다!

2020-11-10 16:05 UTC, amusesla commented on students/14th/team9/giyong-gim/post/models.py
> +    post_id         = models.ForeignKey(Post, on_delete = models.CASCADE)
post 로 수정했습니다.

2020-11-10 16:06 UTC, amusesla commented on students/14th/team9/giyong-gim/post/models.py
> +    comment_created = models.DateTimeField(auto_now_add = True)
created_at 으로 변경하였습니다!

2020-11-10 16:08 UTC, amusesla commented on students/14th/team9/giyong-gim/post/urls.py
> +    path('like/', LikeView.as_view()),
수정하였습니다 !

2020-11-11 12:20 UTC, amusesla commented on students/14th/team9/giyong-gim/user/urls.py
> +    path('login/', LogIn.as_view()),
넵

2020-11-11 12:20 UTC, amusesla commented on students/14th/team9/giyong-gim/westagram/urls.py
> +    path('post/', include('post.urls')),
넵

2020-11-11 12:25 UTC, amusesla commented on students/14th/team9/giyong-gim/user/views.py
> +            return JsonResponse({'message':'INVALID_INPUT'}, status=400)
pass

2020-11-12 07:46 UTC, amusesla commented on students/14th/team9/giyong-gim/user/models.py
> +    user_created = models.DateTimeField(auto_now_add = True)
수정했습니다.

2020-11-12 07:48 UTC, amusesla commented on students/14th/team9/giyong-gim/user/urls.py
> +from django.conf.urls.static import static
네 수정하였습니다.

2020-11-12 10:44 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +            return JsonResponse({'meesage':'SUCCESS'}, status = 200)
<img width="509" alt="Screen Shot 2020-11-12 at 7 43 04 PM" src="https://user-images.githubusercontent.com/70562840/98930103-80336d80-251f-11eb-96ff-6beb0d28d6c2.png">

2020-11-12 10:45 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +            return JsonResponse({'meesage':'SUCCESS'}, status = 200)
``` python
data.get('parent_id',` None)
```

2020-11-12 10:47 UTC, amusesla commented on students/14th/team9/giyong-gim/user/views.py
> +                return JsonResponse({'message':'phone_number already exists!'})
<img width="922" alt="Screen Shot 2020-11-12 at 7 46 55 PM" src="https://user-images.githubusercontent.com/70562840/98930326-d7394280-251f-11eb-8bab-8783728525e2.png">
장고 Q객체를 찾아보고 적용시켜 보았습니다!

2020-11-12 10:48 UTC, amusesla commented on students/14th/team9/giyong-gim/user/views.py
> +                user = User.objects.get(phone_number = data['key'])
<img width="879" alt="Screen Shot 2020-11-12 at 7 47 57 PM" src="https://user-images.githubusercontent.com/70562840/98930466-05b71d80-2520-11eb-9b89-f22357f182c8.png">

2020-11-12 10:50 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +            qs = Post.objects.all()
<img width="459" alt="Screen Shot 2020-11-12 at 7 50 27 PM" src="https://user-images.githubusercontent.com/70562840/98930700-5464b780-2520-11eb-82d8-c1d1d659fc9d.png">
알아보기 쉬운 변수명으로 변경하였습니다.!

2020-11-12 10:57 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +            return JsonResponse({'message': 'KEY_ERROR'}, status = 400)
<img width="355" alt="Screen Shot 2020-11-12 at 7 56 32 PM" src="https://user-images.githubusercontent.com/70562840/98931296-2b90f200-2521-11eb-9b4f-6dba654e7c7d.png">
말씀주신 파이썬 get() 메서드를 사용해서 수정해보았습니다. 
``` python
content = data.get('content', None)
```

2020-11-12 13:10 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +            comments = Comment.objects.prefetch_related('post_id')
<img width="828" alt="Screen Shot 2020-11-12 at 10 05 31 PM" src="https://user-images.githubusercontent.com/70562840/98943688-35235580-2533-11eb-9c70-334b86f6d6e2.png">


select_related() 와 prefetch_related() 의 중복 사용으로 수정하였습니다. 

**목적은 모든 포스트의 정보와 그 포스트에 속한 정보(작성자, 댓글, 라이크)들을 출력하는것에 있었습니다.** 
``` python
posts= Post.objects.all()
for post in posts:
...
'author': post.author.username
...
```
코드를 작성하던 중 for 문이 한번 돌때마다 post.author.username에서 쿼리문이 발생한다는 사실을 알게되었고 쿼리문을 효율적으로 줄이는 방법에 대해서 공부하다가 selected/prefetch 문을 사용하게 되었습니다.

selected_related()문은 정참조에 사용되며  sql 쪽에서 inner join 수행 후 파이썬으로 가져옵니다.(쿼리문1번발생)
prefetch_related()문은 역참조에 사용되며 각 모델들의 쿼리셋을 가져온후 파이썬에서 join을 수행한다고 배웠습니다. (쿼리문2번발생)

post 모델이 User 모델을 정참조하기 때문에  select_related() 문을 사용하였고 역참조인 comment 와 like 모델에 접근하기 위해 prefetched_related()를 사용하여 쿼리문을 줄였습니다.

결과: 다수의 쿼리문에서 총 3개의 쿼리문으로 줄였습니다.

2020-11-12 13:11 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +            return JsonResponse({'message': 'KEY_ERROR'}, status = 400)
띄어쓰기 공간 주의하겠습니다 ㅜㅜ

2020-11-12 13:15 UTC, amusesla commented on students/14th/team9/giyong-gim/user/models.py
> +        db_table = 'user'
수정하였습니다

2020-11-12 13:15 UTC, amusesla commented on students/14th/team9/giyong-gim/post/models.py
> +
수정하였습니다.

2020-11-12 13:19 UTC, amusesla commented on students/14th/team9/giyong-gim/user/views.py
> +            return bool(re.search('^[0-9]{3}-[0-9]{3,4}-[0-9]{4}$', phone_number))
<img width="427" alt="Screen Shot 2020-11-12 at 10 17 12 PM" src="https://user-images.githubusercontent.com/70562840/98944760-e2e33400-2534-11eb-947b-c361b97c0f46.png">
<img width="568" alt="Screen Shot 2020-11-12 at 10 17 20 PM" src="https://user-images.githubusercontent.com/70562840/98944767-e4acf780-2534-11eb-80d4-95d776d77dc7.png">
<img width="637" alt="Screen Shot 2020-11-12 at 10 16 42 PM" src="https://user-images.githubusercontent.com/70562840/98944707-c810bf80-2534-11eb-97e1-0227377d2b91.png">

core 라는 앱을 utils.py 안에 validation 함수를 옮기고 user.urls 에서 import 받아서 사용하는 부분으로 수정하였습니다.

2020-11-12 13:22 UTC, amusesla commented on students/14th/team9/giyong-gim/user/views.py
> +            return JsonResponse({'meesage':'INVALID_PHONE_NUMBER'}, status = 400)
<img width="619" alt="Screen Shot 2020-11-12 at 10 21 56 PM" src="https://user-images.githubusercontent.com/70562840/98945176-7ddc0e00-2535-11eb-915e-84b2831c335c.png">

2020-11-12 13:26 UTC, amusesla commented on students/14th/team9/giyong-gim/core/utils.py
> +from django.core.exceptions import ObjectDoesNotExist
제거했습니다.!

2020-11-12 13:26 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +from django.shortcuts import render
제거했습니다.!

2020-11-12 13:28 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +            return JsonResponse({'message': 'Post has been created successfully!'}, status = 201)
<img width="411" alt="Screen Shot 2020-11-12 at 10 27 24 PM" src="https://user-images.githubusercontent.com/70562840/98945751-4883f000-2536-11eb-8fde-ad7876584e43.png">
알려주신 get() 파이썬 메소드를 사용하여 수정하였습니다.

2020-11-12 13:28 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +                ]
수정완료하였습니다.

2020-11-12 13:32 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +                qs = Comment.objects.filter(post_id = data['post_id']).prefetch_related('author')
<img width="692" alt="Screen Shot 2020-11-12 at 10 30 58 PM" src="https://user-images.githubusercontent.com/70562840/98946108-ccd67300-2536-11eb-8de4-f09fe6a12764.png">

필요 없습니다 ㅜㅜ 좀더 주의해서 보고 코드 작성하도록 하겠습니다!

2020-11-12 13:33 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +                          'id': post.id} for post in qs]
수정하였습니다!

2020-11-12 13:35 UTC, amusesla commented on students/14th/team9/giyong-gim/post/views.py
> +                    'comment' : [
<img width="185" alt="Screen Shot 2020-11-12 at 10 35 52 PM" src="https://user-images.githubusercontent.com/70562840/98946598-6d2c9780-2537-11eb-9a07-95dc9eb48f6d.png">
수정하였습니다.!

2020-11-30 12:06 UTC, merged