[이성보] mission 1,2,3 구현
wecode-bootcamp-korea/westagram-backend pull request #117
Opened 2020-11-09 03:52 UTC by sungbolee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-10 07:56 UTC, jamessoun93 requested changes

2020-11-10 07:56 UTC, jamessoun93 commented on students/14th/team2/sungbo_lee/project_westagram/posting/models.py
> +    image_url = models.CharField(max_length=2000)
- 가독성을 위해 `=` 을 기준으로 정렬해주세요.
- `time` 이 해당 포스팅이 생성되었을때를 의미하시는 것이라면 `auto_now_add=True` 를 주세요. `auto_now=True` 를 주시면 업데이트시에도 해당 필드에 생성시간이 아닌 업데이트 시간이 적용됩니다.
- url 은 `URLField` 를 사용해주세요.
- 그리고 포스팅인데 사진만 있는 것 보다는 여러가지 부가정보중 해당 포스팅의 내용을 입력하는 필드가 있으면 좋을 것 같습니다.

2020-11-10 07:56 UTC, jamessoun93 commented on students/14th/team2/sungbo_lee/project_westagram/posting/models.py
> +# import user.models as user
불필요한 주석은 없애주세요.

2020-11-10 07:56 UTC, jamessoun93 commented on students/14th/team2/sungbo_lee/project_westagram/posting/views.py
> +from user.models import User
여기도 가독성을 위해 `import` 문을 기준으로 정렬해주세요.

2020-11-10 07:56 UTC, jamessoun93 commented on students/14th/team2/sungbo_lee/project_westagram/posting/views.py
> +            return JsonResponse({'message': 'INVALID_KEY'}, status=400)
깔끔하네요! 👍

2020-11-10 07:56 UTC, jamessoun93 commented on students/14th/team2/sungbo_lee/project_westagram/posting/views.py
> +
마찬가지로 사용하고 있지 않은 코드는 지워주세요.

2020-11-10 07:56 UTC, jamessoun93 commented on students/14th/team2/sungbo_lee/project_westagram/user/models.py
> +    email        = models.CharField(max_length=50)
`EmailField` 를 사용해주세요.

2020-11-10 07:56 UTC, jamessoun93 commented on students/14th/team2/sungbo_lee/project_westagram/user/views.py
> +            return JsonResponse({'message': 'INVALID_KEY'}, status=400)
- `KeyError`는 `data` 딕셔너리에서 원하는 key 값을 찾지 못했을때 raise 되는 에러입니다. 그래서 이미 11~16번 째 줄에서 `email`, `password`, `phone_number`, `name` 중 하나라도 찾지 못했을 경우 바로 `except` 문으로 가게 되어 `400` 이 리턴되게 됩니다.
- 18번째 줄부터 시작되는 validation 처리용 조건문들은 User 인스턴스를 생성하기 전에 확인하는게 더 좋을 것 같고, 해당 조건문들에서는 `KeyError` 을 잡아주는게 아니고 `JsonResponse` 로 들어온 값들 중 어떤 값이 조건에 맞지 않는지를 설명하는 에러 메세지와 함께 `400` 을 리턴해주시면 됩니다.

수정해보세요!

2020-11-10 07:56 UTC, jamessoun93 commented on students/14th/team2/sungbo_lee/project_westagram/user/views.py
> +        return JsonResponse({"Hello":"World"}, status=200)
하는일이 없는 `get` 메소드는 지워주세요.

2020-11-10 07:56 UTC, jamessoun93 commented on students/14th/team2/sungbo_lee/project_westagram/user/views.py
> +            return JsonResponse({'message': 'INVALID_KEY'}, status=400)
`SignUpView` 의 리뷰 내용 참고하셔서 수정해주세요.

2020-11-12 13:20 UTC, sungbolee commented on students/14th/team2/sungbo_lee/project_westagram/user/views.py
> +            return JsonResponse({'message': 'INVALID_KEY'}, status=400)
전부 수정하였습니다. 감사합니다!

2020-11-30 12:07 UTC, merged