[이주형] Add: initial settings complete
wecode-bootcamp-korea/westagram-backend pull request #128
Opened 2020-12-01 07:12 UTC by jacobjuhyunglee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-07 07:12 UTC, lordmyshepherd requested changes

2020-12-07 07:12 UTC, lordmyshepherd commented on students/15th/team3/juhyung_lee/.gitignore
> +my_settings.py
👍

2020-12-07 07:12 UTC, lordmyshepherd commented on students/15th/team3/juhyung_lee/users/models.py
> +    password       = models.CharField(max_length=50)
password의 max_length는 왜 50으로 하셨나요?

2020-12-07 07:12 UTC, lordmyshepherd commented on students/15th/team3/juhyung_lee/users/views.py
> +                return JsonResponse({'message': 'SUCCESS'}, status = 200)
```suggestion
    q = Q()
    if ...:
         q &= Q()
         ....

```

2020-12-07 07:12 UTC, lordmyshepherd commented on students/15th/team3/juhyung_lee/users/views.py
> +      #  if User.objects.filter(Q(username=data['username']) | Q(email=data['email']) | Q(phone_number=data['phone_number'])) is not None:
```python
if User.objects.filter()....
```

2020-12-07 07:12 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/models.py
> +    password       = models.CharField(max_length=50)
수정하겠습니다....

2020-12-07 07:13 UTC, kst6294 commented on students/15th/team3/juhyung_lee/users/models.py
> +    password       = models.CharField(max_length=50)
30은 어떠세요?

2020-12-07 07:13 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/models.py
> +    password       = models.CharField(max_length=50)
죄송합니다.....복붙하고 신경을 못 썼네요....

2020-12-09 13:42 UTC, jamessoun93 requested changes
- 현재 주형님이 작성하신 `User` 모델은 `password` 를 제외한 모든 컬럼에 `NULL` 을 허용하고 있어서, 여기서 다른 컬럼을 모두 제외한 `password` 만 담아 호출하게 될 시 에러도 발생시키지도 않고, 아무 `if` 조건도 충족시키지 못해서 아무것도 안하는 `view` 가 됩니다.
- 모델 꼭 수정해주시고, 수정된 모델에 맞춰 `view` 도 수정해서 push 해주세요!

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +            minimum_password     = 8
- `constant` 는 대문자 변수명으로 선언해주세요.
- `min_password_length` 처럼 의미를 더욱 더 정확하게 알 수 있는 변수명을 사용해주시면 더 좋습니다.

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +            if User.objects.filter(Q(username=data['username']) & Q(email=data['email']) & Q(phone_number=data['phone_number'])).exists():
- 여기서는 `Q 객체`사용이 불필요합니다. `filter()` 에 해당 조건들을 `kwargs` 로 넘겨주면 전부 `AND` 로 적용됩니다. 
- `Q 객체`는 `OR` 조건으로 검색하고 싶을 때 유용합니다.
- `exists()` 사용 잘하셨네요 👍

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +            data['phone_number'] = data.get('phone_number')
`data` 라는 변수에 `request.body` 를 담고, 해당 변수에 존재할지 모르는 `key` 로 값을 찾아 다시 `data` 변수에 해당 `key` 값의 `value` 로 재할당 해주고 계신데, 이렇게 `data` 를 재활용하지 마시고 따로 `username`, `email`, `phone_number` 변수에 담아서 사용하시면 아래서 조건걸때 사용하기도 편하고 가독성이 좋아집니다.

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +            if data['email'] is not None and ('@' not in data['email'] or '.' not in data['email']):
python의 [truthy, falsy values](https://www.freecodecamp.org/news/truthy-and-falsy-values-in-python/) 에 대해 공부해보시고 이 부분을 한번 바꿔보세요~

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +        data['phone_number'] = data.get('phone_number')
`SignUpView` 클래스의 리뷰내용과 같습니다.

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +        #        token = token.decode('utf-8')
불필요한 주석 없애주세요.

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +            if data['username'] is not None:
위에서 언급한 truthy, falsy values 내용 보시고 수정해보세요.

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +                        token = jwt.encode({'username' : data['username']}, SECRET_KEY, algorithm = "HS256")
jwt 인코딩할때 어떤 알고리즘을 사용했는지도 함께 `my_settings.py` 에 숨겨주세요.

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +                        return JsonResponse({'message': 'SUCCESS'}, status = 200)
`token` 을 `return` 해주시는걸 깜빡하신 것 같네요.

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +                       return JsonResponse({'message': 'INVALID_USER'}, status = 400)
- 위 `if` 문에 `return` 문이 있기때문에 `elif` 는 불필요합니다.
- 그리고 인증실패 관련 `status code` 는 `401` 을 사용해주세요. `UNAUTHORIZED`의 의미를 갖습니다.

2020-12-09 13:42 UTC, jamessoun93 commented on students/15th/team3/juhyung_lee/users/views.py
> +                        return JsonResponse({'message': 'INVALID_USER'}, status = 400)
- 위에서부터 각각 다른 `if` 문에 정확하게 똑같은 로직을 처리하는 코드가 반복되고 있습니다. 
- 이런 코드를 보면 항상 이걸 어떻게하면 효율적으로 가독성 좋게 바꿀 수 있을지에 대한 고민을 해보셔야합니다.
- 어짜피 해당 `user` 객체만 가져올 수 있으면 `token` 을 생성할 때 필요한 정보는 전부 있으니, 그 밑에 코드는 전부 반복적인 코드가 되는거죠.
- 한번 고민해보시고 어려움 있으시면 말씀해주세요.

2020-12-11 04:57 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/views.py
> +                        return JsonResponse({'message': 'INVALID_USER'}, status = 400)
kwargs 활용해서 if문 한 블럭으로 다 정리했습니다 감사합니다!

2020-12-11 04:57 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/views.py
> +                       return JsonResponse({'message': 'INVALID_USER'}, status = 400)
else로 따로 조건 없이 INVALIDE_USER만 리턴 해주라는 말씀이신가요? 그렇게 수정하고 401도 수정하였습니다.

2020-12-11 04:58 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/views.py
> +                        return JsonResponse({'message': 'SUCCESS'}, status = 200)
수정하였습니다.

2020-12-11 04:58 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/views.py
> +                        token = jwt.encode({'username' : data['username']}, SECRET_KEY, algorithm = "HS256")
따로 숨기고 import 해주었습니다.

2020-12-11 04:58 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/views.py
> +            if data['email'] is not None and ('@' not in data['email'] or '.' not in data['email']):
공부하고 if email로 바꿔주었습니다!

2020-12-11 05:00 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/views.py
> +            data['phone_number'] = data.get('phone_number')
와! 몰랐던 사실입니다..
이름 `username = data.get('username')` 와 같은 식으로 바꿔주고 그 다음 부분들을 username 같은 변수들로 수정했습니다.

2020-12-11 05:01 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/views.py
> +            if User.objects.filter(Q(username=data['username']) & Q(email=data['email']) & Q(phone_number=data['phone_number'])).exists():
네 제가 처음에 null 값을 여러 or로 받아올 로직을 짜다가 Q 객체를 가져왔는데 결국엔 null이라도 하나의 or을 만족시켜서 and으로 수정했었네요.. 
일반 filter, kwargs로 다시 구현했습니다.

2020-12-11 05:01 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/views.py
> +            minimum_password     = 8
대문자로 바꾸고, 변수명 수정하였습니다.

2020-12-11 05:02 UTC, jacobjuhyunglee commented on students/15th/team3/juhyung_lee/users/models.py
> +    password       = models.CharField(max_length=256)
password는 항상 받도록 views.py에 작성하였는데, username, email, phone_number 중 하나만 값을 받고 다른 두개에 null이 들어가도록 상시로 바뀌게 하려면 모델에서 어떤 부분을 바꿔주어야 할까요?

2020-12-28 13:38 UTC, merged