[우혁준] Add: initial settings complete
wecode-bootcamp-korea/westagram-backend pull request #129
Opened 2020-12-01 07:12 UTC by hwukjunwoo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-09 03:42 UTC, Muntari29 commented on students/15th/team1/hwukjunwoo/user/views.py
> +            if (data['email'] == '') and (data['phone'] == ''):
if 조건문과 비교연산자를 함께 사용할 경우 괄호가 필요하지 않는 경우는 
괄호를 제거해주셔도 될 것 같습니다.

2020-12-09 03:42 UTC, Muntari29 commented on students/15th/team1/hwukjunwoo/westagram/settings.py
> +ALLOWED_HOSTS = []
```suggestion
ALLOWED_HOSTS = ['*']
```
해당 과제에서 모든 접근을 허용하기 위해 위와 같이 표시합니다.

2020-12-09 03:42 UTC, Muntari29 commented on students/15th/team1/hwukjunwoo/westagram/urls.py
> +urlpatterns = [
Project urls.py 안의
urlpatterns 가 빈공란으로 보여집니다.
서버로 들어오는 요청은 가장 먼저 Project/urls.py 가 전달받습니다.
이렇게 할 경우 로컬서버를 띄울때 에러가 날 것으로 예상되며
어떤 URL이 요청될지에 따라 각각에 맞는 View로 연결을 시켜줘야하는데 그 부분이 동작하지 않을것같습니다.

2020-12-09 15:07 UTC, jamessoun93 requested changes
혁준님 리뷰남겨드렸으니 확인하시고 반영해서 push 해주세요!

2020-12-09 15:07 UTC, jamessoun93 commented on students/15th/team1/hwukjunwoo/user/views.py
> +            if (len(data['password']) < 8):
파이썬에서는 if 조건을 소괄호로 감싸지 않습니다~

2020-12-09 15:07 UTC, jamessoun93 commented on students/15th/team1/hwukjunwoo/user/views.py
> +                password = data['password'],
`=` 을 기준으로 정렬해주세요.

2020-12-09 15:07 UTC, jamessoun93 commented on students/15th/team1/hwukjunwoo/user/views.py
> +            print(password)
- `print`문을 사용하여 값이 제대로 저장되는지 확인하신 흔적이 남아있네요 👍👍👍
- 하지만 이런 디버깅할때 쓰는 코드들은 git에 push 하실때는 없애주셔야 합니다.

2020-12-09 15:07 UTC, jamessoun93 commented on students/15th/team1/hwukjunwoo/user/views.py
> +                    return JsonResponse({'message': 'INVALID_USER'}, status = 400)
여기서는 첫번째로 수정해주셔야할 문제가 크게 두 가지가 있습니다.
- 불필요하게 너무 if 문이 많이 nesting 이 되어있는데, 로직을 한번 생각해보시고 뺄 수 있는 부분이 있는지 한번 생각해보세요.
- 정확하게 일치하는 코드 몇줄이 서로 다른 if 문에 반복적으로 사용되고 있습니다. 이럴때는 항상 어떻게 효율적으로 코드를 줄일 수 있을지 고민해보셔야 합니다. 
- 이 부분은 flow 를 생각해보면서 하나씩 바꾸셔야하는 부분이라 한번 적용해보시고 어려움 있으시면 말씀해주세요!

2020-12-14 11:07 UTC, lordmyshepherd requested changes

2020-12-14 11:07 UTC, lordmyshepherd commented on students/15th/team1/hwukjunwoo/user/views.py
> +            return JsonResponse({'message': 'KEY_ERROR'}, status = 400)
```python

except User.DoesNotExist:
    return ...
except User.MultipleObjectReturned:
   return ...

```

2020-12-28 13:38 UTC, merged