[이재혁] Add: initial settings complete
wecode-bootcamp-korea/westagram-backend pull request #130
Opened 2020-12-01 07:12 UTC by leejaek

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-08 06:46 UTC, seungjaekim-git requested changes
:+1:

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/westagram/settings.py
> +ALLOWED_HOSTS = []
```python
ALLOWED_HOSTS = ["*"]
```

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/user/views.py
> +             }
여기서 ":" 기준으로 정렬하면 좋을거같아요 !

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/user/views.py
> +from user.models import User
import 기준으로 정렬하면 좋을거같아요 !

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/post/views.py
> +                    "datetime": comment.datetime,
물론 datetime으로 구분할수 있겠지만, 작성자와 댓글내용이 겹치는 경우 구분해야되는 경우가 생길때
그냥 comment의 id로 접근하면 편하지 않을까요? 예를 들어서, 댓글을 삭제할때
id값으로 그냥 delete하면 편할거 같아서 ... 
**한줄요약 : comment의 id값도 result에 포함되면 좋을거같아요 !**

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/post/views.py
> +        comments = Comment.objects.filter(post_id = data['post_id'])
소소하지만 ... "="으로 정렬하면 좋을거같아요

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/post/views.py
> +        data_content = data['content']
"=" 기준으로 정렬해주시면 좋을거같아요.

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/post/views.py
> +                    "img": post.img_url,
":" 기분으로 정렬하면 좋을거 같아요 !

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/post/views.py
> +        results = []
"=" 기준으로 정렬하면 좋을거같아요 !

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/post/views.py
> +class Upload(View):
흠.. 이것도 convention 인지 모르겠지만, class name 뒤에 View를 붙여주는게 표본인거 같습니다. 
예를 들어, 
```python
class UploadView(View):
```

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/post/views.py
> +from django.core.serializers.json import DjangoJSONEncoder
import 기준으로 정렬하면 좋을거같아요

2020-12-08 06:46 UTC, seungjaekim-git commented on students/15th/team4/jaehyeok_lee/post/models.py
> +        db_table = 'comments'
import와 = 기준으로 정렬하면 좋을거같아요 !

2020-12-09 17:23 UTC, lordmyshepherd requested changes

2020-12-09 17:23 UTC, lordmyshepherd commented on students/15th/team4/jaehyeok_lee/user/views.py
> +        return JsonResponse({"message": "SUCCESS"}, status = 201)
이 코멘트는 27 line에 대한 질문에 답을 고민해보시고 봐주세요. 
for문을 사용할 필요없이 아래와 같이 구현 가능할 것 같습니다. dictionary에 `[ ]`가 아니라 `.get()` method를 사용해서 간단하게 구현할 수 있을 것 같습니다.
```
email  = data.get('email')
name  = data.get('name')
phone_number = data.get('phonenumber')
password = data.get('password')

if email:
    account = email
if name:
    account = name
if phone_number:
    account = phone_number

if User.objects.filter(account = account).exists():
    return JsonResponse(...)
```

2020-12-09 17:23 UTC, lordmyshepherd commented on students/15th/team4/jaehyeok_lee/user/views.py
> +        data_password = data['password']
```suggestion
        account  = data['account']
        password = data['password']
```

2020-12-09 17:23 UTC, lordmyshepherd commented on students/15th/team4/jaehyeok_lee/user/views.py
> +        users         = User.objects.all()
users 변수는 어디서 사용하나요?

2020-12-09 17:23 UTC, lordmyshepherd commented on students/15th/team4/jaehyeok_lee/user/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status = 400)
KeyError가 언제 발생하나요?

2020-12-09 17:23 UTC, lordmyshepherd commented on students/15th/team4/jaehyeok_lee/user/views.py
> +            #return JsonResponse({"message": "SUCCESS"}, status = 200)
주석은 지워주세요~

2020-12-10 08:33 UTC, lordmyshepherd requested changes

2020-12-10 08:33 UTC, lordmyshepherd commented on students/15th/team4/jaehyeok_lee/user/views.py
> +            return JsonResponse({"message": "SUCCESS", "Authorization": access_token.decode('utf-8')}, status = 200)
```suggestion
            return JsonResponse({"message": "SUCCESS", "access_token": access_token.decode('utf-8')}, status = 200)
```

2020-12-28 13:38 UTC, merged