[김민철] Add: initial settings complete
wecode-bootcamp-korea/westagram-backend pull request #131
Opened 2020-12-01 07:12 UTC by mincheolkk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-09 17:09 UTC, jamessoun93 requested changes

2020-12-09 17:09 UTC, jamessoun93 commented on students/15th/team3/user/views.py
> +from django.views    import View
- `import` 순서도 가독성에 영향을 미칩니다. 아래처럼 수정해주세요.
```suggestion
import re, json # 파이썬 자체 모듈

from django.http  import JsonResponse # 장고 제공 모듈
from django.views import View

from .models import SignUp # 직접 구현한 클래스
```

2020-12-09 17:09 UTC, jamessoun93 commented on students/15th/team3/user/views.py
> +            data['name'] = data.get('name')
- `data` 라는 변수는 `request.body` 를 파이썬 `dictionary` 로 변환하여 저장하는 변수인데, `data` 에서 꺼내온 값으로 `data`를 변형하고 있습니다.
- `data` 에서 꺼내온 값들을 아래처럼 따로 변수에 담아 사용한다면, 아래 코드들에서도 조건문들이 깔끔해집니다.
```suggestion
            data = json.loads(request.body)

            email = data.get('email')
            tel   = data.get('tel')
            name  = data.get('name')
```
- 그리고 여기서 `get()` 을 사용하신 이유를 설명해주세요.

2020-12-09 17:09 UTC, jamessoun93 commented on students/15th/team3/user/views.py
> +
불필요하게 많이 띄우실 필요 없습니다.

2020-12-09 17:09 UTC, jamessoun93 commented on students/15th/team3/user/views.py
> +                 if (data['name'] is not None) or (data['tel'] is not None) or (data['email'] is not None):
https://www.freecodecamp.org/news/truthy-and-falsy-values-in-python/
위 링크 참고하여 `truthy`, `falsy` values 공부해보시고 여기 `if` 조건에 적용해보세요~

2020-12-09 17:09 UTC, jamessoun93 commented on students/15th/team3/user/views.py
> +                return JsonResponse({'message': 'KEY_ERROR'}, status=400)
`KeyError` 가 언제 발생하는지 정확하게 알고 사용하신건가요? 답글에 어떤 목적으로 잡아주셨는지, 어떤 조건에서 잡히는지 적어주세요.

2020-12-10 12:48 UTC, mincheolkk commented on students/15th/team3/user/views.py
> +                return JsonResponse({'message': 'KEY_ERROR'}, status=400)
KeyError 는 딕셔너리 키를 찾을 수 없을때 발생합니다. 딕셔너리로 전달되는 json 에서 제대로 키값이 전달되는지 확인하기위해 KeyError 를 잡아놨습니다. models.py에서  작성했던 네개의 변수 name, email, tel, password 중에 하나라도 입력이 되지 않으면 KeyError 가 발생했습니다. 여기서 입력되지 않은 값을 .get() 메소드를 사용해 none 으로 만들어 주니, 변수들이 다 입력이 되지 않더라도 KeyError 가 발생하지 않았습니다.

2020-12-10 12:49 UTC, mincheolkk commented on students/15th/team3/user/views.py
> +                 if (data['name'] is not None) or (data['tel'] is not None) or (data['email'] is not None):
if name or tel or email: 
이 코드로 수정했습니다~

2020-12-10 12:58 UTC, mincheolkk commented on students/15th/team3/user/views.py
> +            data['name'] = data.get('name')
따로 변수를 지정해서 수정했습니다.
get() 을 쓴 이유는, 클라이언트에서 email, tel, name 의 값들이 전달되지 않으면, none 으로 받아 keyError 를  막기위해 사용했습니다!

2020-12-10 13:00 UTC, mincheolkk commented on students/15th/team3/user/models.py
> +    password = models.CharField(max_length=45,null=True)
수정했습니다!

2020-12-10 13:01 UTC, mincheolkk commented on students/15th/team3/user/views.py
> +
넵

2020-12-10 13:01 UTC, mincheolkk commented on students/15th/team3/user/views.py
> +from django.views    import View
넵넵

2020-12-10 13:02 UTC, mincheolkk commented on students/15th/team3/user/views.py
> +
넵

2020-12-28 13:38 UTC, merged