[문승희] Add : initial settings complete
wecode-bootcamp-korea/westagram-backend pull request #132
Opened 2020-12-01 07:12 UTC by Muntari29

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-09 04:50 UTC, hwukjunwoo reviewed
일단 미션 2번 3번만 보고 리뷰작성합니다.  
필수적인것아니지만 이렇게하면 좋겠다 해서 했습니다.

2020-12-09 04:50 UTC, hwukjunwoo commented on students/15th/team2/seunghee_mun/user/views.py
> +import json
import json, re, bcrypt, jwt 다합치는 방법도 좋을것같습니다.

2020-12-09 04:50 UTC, hwukjunwoo commented on students/15th/team2/seunghee_mun/user/models.py
> +#    phonenumber = models.CharField(max_length=13)
이걸 주석처리하신 이유가 있을까요?

2020-12-09 04:53 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/user/models.py
> +#    phonenumber = models.CharField(max_length=13)
원래는 USER 테이블의 column을 4개를 구성하였습니다.
도중에 2개 줄이는 바람에 주석 처리하였습니다.

2020-12-09 17:55 UTC, jamessoun93 requested changes
승희님 유저 app 과 보드 app 의 CommentView 리뷰는 내일 이어서 진행하겠습니다.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/westagram/settings.py
> +ALGORITNM = ALGORITHM
오타확인해주세요.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/urls.py
> +        path('board', BoardView.as_view()),
- `/board/board` 를 호출해야 `BoardView` 클래스의 메소드가 호출되는데 이게 의도하신게 맞는건가요?

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/models.py
> +from user.models import User
나중에 `import` 문이 많아지면 이런 영역도 가독성에 큰 영향을 끼치게 됩니다. `import` 를 기준으로 정렬해보세요.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/models.py
> +    contents = models.TextField()
여기도 `=`을 기준으로 정렬해주세요.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/models.py
> +    board_name = models.CharField(max_length=45)
`board_name` 컬럼명은 `Board` 테이블인걸 이미 알고있으니 `name` 으로만 지어주셔도 무방합니다.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/models.py
> +    time = models.DateTimeField(default=timezone.now)
`time` 은 해당 `board` 생성시간을 뜻하는 필드인가요?

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/models.py
> +    image = models.CharField(max_length=200, blank=True)
- 데이터베이스에는 이미지 자체를 저장하는게 아닌 해당 이미지의 주소를 저장하게되니 컬럼명을 `image_url` 처럼 명확하게 지어주세요.
- `url` 은 `URLField` 를 사용해주세요.
- `blank=True` -> 어떤의미로 사용하신건지 코멘트로 설명해주세요.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/models.py
> +    board_title = models.ForeignKey(Board, on_delete=models.CASCADE)
ForeignKey를 담고있는 컬럼명은 참조하고 있는 테이블명의 단수형으로 지정해주시면 됩니다.
```suggestion
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
```

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/models.py
> +    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
여기도 마찬가지입니다.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/models.py
> +    comment_tiem = models.DateTimeField(default=timezone.now)
오타 확인해주시고 `comment` 테이블인걸 알고있으니 여기도 컬럼명에 `comment`는 필요없습니다.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/models.py
> +    comment_body = models.CharField(max_length=100)
여기도 마찬가지입니다.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/models.py
> +# Create your models here.
불필요한 주석 지워주세요.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/views.py
> +from user.models import User
가독성을 위해 `import` 를 기준으로 정렬해주세요.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/views.py
> +            return JsonResponse({'MESSAGE' : 'NOT_MEMBER'}, status=400)
- `try`...`except` 문을 잘 사용하셨지만 에러는 명확하게 잡아주는게 좋습니다.
- 유저 테이블에 조건에 맞는 유저정보가 존재하지 않을 시 `DoesNotExist` 에러를 raise 하게 됩니다. 따라서 아래처럼 수정해주실 수 있습니다.
```suggestion
        try:
            user_post = User.objects.get(user_name=data['user']).id
        except User.DoesNotExist:
            return JsonResponse({'MESSAGE' : 'NOT_MEMBER'}, status=400)
```

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/views.py
> +            image_url = data['image']
`request.body` 가 담고 들어와야할 정보들을 꺼내는 과정은 이 메소드의 가장 상단에 모아주시는게 좋습니다.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/views.py
> +            return JsonResponse({'MESSAGE' : 'NOT_ENOUGH_INFO'}, status=400)
- 마찬가지로 에러를 잡아줄때는 꼭 정확하게 에러를 잡아주는게 중요합니다. 
- 여기서 발생할 수 있는 에러가 뭐가 있는지 아시나요?

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/views.py
> +        if not Board.objects.filter(board_name=data['board_name']):
`filter` 만 쓰면 해당 조건에 맞는 모든 객체들을 가져오는데 여기서는 단순 존재유무만 확인하고 싶을 뿐이니 `exists()` 메소드를 함께 사용하시면 불필요하게 정보를 전부 가져오는걸 방지할 수 있습니다.

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/views.py
> +                return JsonResponse ({'MESSAGE': 'SUCCESS'}, status=201)
`201` 👍👍

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/views.py
> +            board_values = Board.objects.all().order_by('-id') # 최신데이터 먼저
👍

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/views.py
> +            '''
불필요한 스트링 없애주세요~

2020-12-09 17:55 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/board/views.py
> +            get_data = json.loads(serialize('json', board_values))
`board_values` 를 파이썬 `list` 로 변환하기 위해서 이렇게 사용하신 것 같은데, 이럴때는 윗줄에서 `values()` 메소드를 사용하시면 원하시는 결과를 얻으실 수 있습니다.

2020-12-09 18:21 UTC, jamessoun93 requested changes

2020-12-09 18:21 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/user/models.py
> +#    email = models.CharField(max_length=70)
- 더 이상 필요하지 않은 컬럼은 지워주세요.
- `=`을 기준으로 정렬해주세요.

2020-12-09 18:21 UTC, jamessoun93 commented on students/15th/team2/seunghee_mun/user/views.py
> +            return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=201)
- 전체적으로 `print` 문을 통해 여러가지 확인하면서 작업하신 흔적이 보여서 넘 좋네요! 👍
- 하지만 `git`에 `push` 하실때는 디버깅용 `print` 문들은 전부 없애주신 후 `push` 해주셔야 합니다. 
- `PR`에 포함되어있는 코드는 `main` 브랜치에 `merge`가 되어도 무리가 없는 코드여야합니다. 
- 협업하는 개발자들에게 도움이 되는 정보가 아니고 오히려 가독성을 떨어트리는 요소가 될 수 있습니다.

2020-12-10 00:29 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/user/views.py
> +import json
수정하였습니다

2020-12-10 00:30 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/westagram/settings.py
> +ALGORITNM = ALGORITHM
수정완료하였습니다

2020-12-10 00:32 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/urls.py
> +        path('board', BoardView.as_view()),
/board 호출시 comment와 구별하기 위해 추가하였습니다.
현 단계에서 2가지 뷰로만 연결시켜주면 되기때문에 해당 path의 board는 빈문자열로 /board 로만 출력되도록 수정하겠습니다.

2020-12-10 00:35 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/models.py
> +from user.models import User
easy_align_plugin으로 수정하였습니다

2020-12-10 00:35 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/models.py
> +    contents = models.TextField()
수정하였습니다

2020-12-10 00:37 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/models.py
> +    board_name = models.CharField(max_length=45)
수정완료하였습니다.

2020-12-10 00:54 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/views.py
> +        if not Board.objects.filter(board_name=data['board_name']):
존재유무만을 확인하고 싶을때 사용하는 exists() 메소드로 수정완료하였습니다.

2020-12-10 00:57 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/views.py
> +            '''
수정완료하였습니다.

2020-12-10 01:27 UTC, jamessoun93 commented
승희님 혹시 놓치셨을까봐 여기 더 숨어있으니 확인해주세요~
![image](https://user-images.githubusercontent.com/50141312/101709143-4334a980-3ad2-11eb-9120-fb4647ba6ffa.png)

2020-12-10 05:15 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/user/models.py
> +#    email = models.CharField(max_length=70)
수정완료하였습니다.

2020-12-10 05:19 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/user/views.py
> +            return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=201)
push 전 불필요한 주석과 print 문은 전부 삭제하여 푸시하도록 하겠습니다.
수정완료하였습니다.

2020-12-10 05:55 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/views.py
> +            get_data = json.loads(serialize('json', board_values))
수정완료하였습니다

2020-12-10 06:00 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/models.py
> +    time = models.DateTimeField(default=timezone.now)
네 맞습니다.
settings.py에서 한국 현지 시간으로 등록되도록 설정도 함께 변경하였습니다.

2020-12-10 06:08 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/models.py
> +    image = models.CharField(max_length=200, blank=True)
수정완료하였습니다.
처음에는 black = True 사용시 DB에 값이 들어오지 않는 경우를 '' 표기하여 image가 필수적으로 등록되지 않는 방향으로 로직을 구성하였습니다.
해당 과제에서는 image를 필수로 받아올수있게 로직을 구성하여 image 값이 주어지지 않으면 "NOT_ENOUGH_INFO" 를 반환하도록 구성하였습니다.
따라서 black=True는 삭제하도록 하겠습니다.

2020-12-10 06:13 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/models.py
> +    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
거의 대부분 이런 이슈가 있습니다.
혹여나 변수 이름이 겹치는것을 대비해 다른 변수명을 주었습니다.
클래스별로 서로 상충되지 아니하니, 모두 간단한 변수명으로 변경하겠습니다.

2020-12-10 06:15 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/models.py
> +    board_title = models.ForeignKey(Board, on_delete=models.CASCADE)
수정완료하였습니다.

2020-12-10 06:20 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/models.py
> +    comment_tiem = models.DateTimeField(default=timezone.now)
수정완료하였으며, 오타는 찾지 못하였습니다.
어느 부분을 말씀하시는건지요?

2020-12-10 06:20 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/models.py
> +    comment_body = models.CharField(max_length=100)
수정완료하였습니다.

2020-12-10 06:21 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/models.py
> +# Create your models here.
수정완료하였습니다.

2020-12-10 06:21 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/views.py
> +from user.models import User
수정완료하였습니다.

2020-12-10 06:23 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/views.py
> +            image_url = data['image']
수정완료하였습니다.

2020-12-10 10:17 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/views.py
> +            return JsonResponse({'MESSAGE' : 'NOT_MEMBER'}, status=400)
try, except 문에 정확한 에러를 지정해줘하는게 정말 중요하다는것을 알았습니다.
Django의 get method exception 은 총 3가지가 있으며 해당 로직에서는 값이 없을때 나오는 에러만 반환하도록 지정해주겠습니다.
다른것도 모두 이와 같이 수정하겠습니다.

2020-12-10 11:00 UTC, Muntari29 commented on students/15th/team2/seunghee_mun/board/views.py
> +            return JsonResponse({'MESSAGE' : 'NOT_ENOUGH_INFO'}, status=400)
KeyError가 발생하는 구간으로
하단 except 구문으로 수정완료하였습니다.

2020-12-28 13:38 UTC, merged