[김순태] Add: initial settings complete
wecode-bootcamp-korea/westagram-backend pull request #133
Opened 2020-12-01 07:12 UTC by kst6294

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-09 07:44 UTC, supersaloon commented on students/15th/team1/suntae_kim/user/models.py
> +    username     = models.CharField(max_length=45)
fullname, username 이라는 변수명이 모호한 것 같습니다. 좀 더 명확한 변수명을 사용하면 좋을 듯 합니다.

2020-12-09 07:44 UTC, supersaloon commented on students/15th/team1/suntae_kim/user/views.py
> +        try:
너무 많은 코드에 try except를 적용한것 같습니다.
건 별로 걸거나
Exception 별로 except 를 나눌 필요가 있어 보입니다.

2020-12-09 07:44 UTC, supersaloon commented on students/15th/team1/suntae_kim/user/views.py
> +                return JsonResponse({'MESSAGE' : 'ACCOUNT_ERROR'})
위의 if ~ elif 구문들은 각각 if 문으로 분리하는게 더 자연스러워 보입니다.

2020-12-09 07:44 UTC, supersaloon commented on students/15th/team1/suntae_kim/user/views.py
> +            return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status=400)
여기서는 except를 Exception 으로 받는게 더 좋아 보입니다.

2020-12-09 07:52 UTC, supersaloon commented on students/15th/team1/suntae_kim/user/views.py
> +            if (not re.match(email_expression,username) and not re.match(mobile_expression, username)) and not re.match(username_expression, username):
여기서 and 대신 or 를 사용하여, 하나라도 정규식 위반이면 에러 메세지를 내는게 자연스러워 보입니다.

2020-12-09 07:52 UTC, supersaloon commented on students/15th/team1/suntae_kim/user_login/views.py
> +        pass
__ini__ 는 불필요해 보이네요

2020-12-09 07:52 UTC, supersaloon commented on students/15th/team1/suntae_kim/user_login/views.py
> +                return JsonResponse({'MESSAGE' : 'INVALID_USER'})
.filter로 반환된 값에 .exists() 쓰는게 좀 더 자연스러워 보입니다.

2020-12-09 07:52 UTC, supersaloon commented on students/15th/team1/suntae_kim/westagram/urls.py
> +    path('user', include('user.urls'))
user 라는 이름이 모호하네요. 좀 더 명확한 이름을 써서 로그인 API라는 걸 알려주면 좋을 것 같습니다.

2020-12-09 07:54 UTC, supersaloon commented on students/15th/team1/suntae_kim/posting/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
위코드 컨벤션을 지켜서 = 기준으로 정렬하면 좋을 것 같습니다.

2020-12-09 08:11 UTC, supersaloon commented on students/15th/team1/suntae_kim/posting/views.py
> +                    "posting_id" : comment.posting_id
위코드 컨벤션으로 정렬하면 좋을 듯 합니다.

2020-12-09 08:11 UTC, supersaloon commented on students/15th/team1/suntae_kim/user_login/views.py
> +                access_token = jwt.encode({'id' : user_id}, SECRET, algorithm = 'HS256').decode('utf-8')
솔트와 암호화 알고리즘을 코드에 그대로 남기는 것은 바람직하지 않아 보입니다.(알고리즘 코드에 쓰고 push 했다가 수정했습니다;;)

2020-12-09 11:56 UTC, kst6294 commented on students/15th/team1/suntae_kim/user/models.py
> +    username     = models.CharField(max_length=45)
해당 부분은 수정완료 했습니다!

2020-12-09 11:56 UTC, kst6294 commented on students/15th/team1/suntae_kim/user/views.py
> +        try:
Exception 관련해서 더 체크 후 진행하겠습니다!

2020-12-09 11:56 UTC, kst6294 commented on students/15th/team1/suntae_kim/user/views.py
> +                return JsonResponse({'MESSAGE' : 'ACCOUNT_ERROR'})
수정 했습니다! 감사합니다!

2020-12-09 11:57 UTC, kst6294 commented on students/15th/team1/suntae_kim/user/views.py
> +            return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status=400)
이 부분은 더 확인해보겠습니다!

2020-12-09 11:58 UTC, kst6294 commented on students/15th/team1/suntae_kim/user/views.py
> +            if (not re.match(email_expression,username) and not re.match(mobile_expression, username)) and not re.match(username_expression, username):
처음에는 or 을 사용하려 했으나, 에러 발생으로 and 로 수정했었습니다.

해당 내용 반영해서, 고민을 더 해봐야겠습니다.

2020-12-09 11:58 UTC, kst6294 commented on students/15th/team1/suntae_kim/user_login/views.py
> +        pass
수정했습니다!

2020-12-09 11:58 UTC, kst6294 commented on students/15th/team1/suntae_kim/westagram/urls.py
> +    path('user', include('user.urls'))
user 는 그대로 사용하되, signin, signup 으로 endpoint 를 지정했습니다.

2020-12-09 11:59 UTC, kst6294 commented on students/15th/team1/suntae_kim/posting/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
확인했습니다!

2020-12-09 12:00 UTC, kst6294 commented on students/15th/team1/suntae_kim/user_login/views.py
> +                access_token = jwt.encode({'id' : user_id}, SECRET, algorithm = 'HS256').decode('utf-8')
넵 SECRET KEY 는 settings 에 있는 키로 import 했습니다! 알고리즘을 남기지 않는 방식이 따로 있을까요?

2020-12-09 18:26 UTC, lordmyshepherd requested changes

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user/views.py
> +            mobile_expression   = "(010)(-{1}\d{4}-{1}\d{4})"
정규식은 상수라고 생각하시면 될 것 같습니다.

```suggestion
            # 정규 표현식
            REGEX_NAME = "^[A-Za-z0-9_]*$"
            REGEX_PASSWORD = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&]{8,18}"
            REGEX_EMAIL    = "[^@]+@[^@]+\.[^@]+"
            REGEX_MOBILE   = "(010)(-{1}\d{4}-{1}\d{4})"
```

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user/views.py
> +                return JsonResponse({'MESSAGE' : 'PASSWORD_ERROR'})
34 line의 validation 처리는 username에 관련된 로직이므로 password validation은 elif가 아니라 if로 별도로 분리시켜주시는게 좋습니다.

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user/views.py
> +            elif User.objects.filter(username = username).count() >= 1:
마찬가지로 if문으로 분기처리 해주시면 될 것 같습니다.
또한 해당 자원의 존재 여부만 판단하면 되는경우, exists()사용해서 구현해볼 수 있습니다.

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user/views.py
> +                return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=201)
불필요한 else문을 지우면서, 코드를 한 줄 줄여볼 수 있을 것 같습니다.

```suggestion
            user = User.objects.create(
                username     = username,
                password     = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode()
            )

            return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=201)
```

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user/views.py
> +                    password     = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode()
51 line에서 decode에 실패할 경우는 고려해보셨나요?

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user_login/views.py
> +                access_token = jwt.encode({'id' : user_id}, SECRET, algorithm = 'HS256').decode('utf-8')
정말 좋은 피드백입니다! 알고리즘도 my_settings.py로 관리할 수 있을 것 같습니다~

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user_login/views.py
> +# )
불필요한 주석은 지워주세요~

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user_login/views.py
> +#from suntae_kim.user.models import User
마찬가지 입니다~

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user_login/views.py
> +            user_info       = User.objects.get(username = username)
info라는 말이 붙지 않아도 user instance에 대한 정보가 담겨있다는 사실을 코드만 보고도 이해할 수 있습니다.
```suggestion
            user       = User.objects.get(username = username)
```

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user_login/views.py
> +            user_id         = user_info.id
```suggestion

```

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user_login/views.py
> +                SECRET = 'this is my secret'
my_settings.py 의 secretkey를 사용해주세요.

2020-12-09 18:26 UTC, lordmyshepherd commented on students/15th/team1/suntae_kim/user_login/views.py
> +                access_token = jwt.encode({'id' : user_id}, SECRET, algorithm = 'HS256').decode('utf-8')
`token payload`에 담는 id의 값이 어떤 값인지 정확하게 key 값을 정해주세요.

```suggestion
                access_token = jwt.encode({'user_id' : user.id},  my_settings.SECRET_KEY, algorithm = my_settings.ALGORITHM).decode('utf-8')
```

2020-12-10 12:48 UTC, jamessoun93 requested changes

2020-12-10 12:48 UTC, jamessoun93 commented on students/15th/team1/suntae_kim/posting/views.py
> +                posting_username = posting_username_id
`=`으로 정렬해주세요~

2020-12-10 12:48 UTC, jamessoun93 commented on students/15th/team1/suntae_kim/user/utils.py
> + #           return JsonResponse({ 'INVALID_USER_SIGNIN_FIRST' : e })
utils.py 정리.. 부탁드립니다.

2020-12-10 12:48 UTC, jamessoun93 commented on students/15th/team1/suntae_kim/user/views.py
> +            if User.objects.filter(username = username).count() >= 1:
`.exists()` 를 활용하실 수 있겠네요.

2020-12-10 12:48 UTC, jamessoun93 commented on students/15th/team1/suntae_kim/user/views.py
> +            return JsonResponse({'MESSAGE' : e}, status=400)
- `Exception` 핸들링은 기존처럼 명확하게 에러를 잡아주시는게 좋습니다. 
- 이렇게 잡으면 모든 에러를 여기서 거르겠다는건데, 어떤 에러들이 발생할지 명확하게 파악해서 각 에러마다 처리할 로직을 구현해주시는게 좋습니다.

2020-12-10 12:48 UTC, jamessoun93 commented on students/15th/team1/suntae_kim/user/views.py
> +            user_password = user_info.password
`user` 객체만 있으면 `id`, `password` 는 바로바로 가져올 수 있는 값이므로 굳이 변수 선언까지는 불필요하겠네요.

2020-12-10 12:48 UTC, jamessoun93 commented on students/15th/team1/suntae_kim/user/views.py
> +                    }, SECRET_KEY, algorithm = 'HS256').decode('utf-8')
한줄로 처리해주시는게 더 깔끔할 것 같고 어떤 `algorithm` 을 사용하셨는지도 `my_settings.py` 에 숨겨주시는게 좋겠네요!

2020-12-10 13:03 UTC, kst6294 commented on students/15th/team1/suntae_kim/user/utils.py
> + #           return JsonResponse({ 'INVALID_USER_SIGNIN_FIRST' : e })
지금 피드백 남겨주신 코드들이.. 
제가 최종적으로 push  해서 pr 한 코드와 상이합니다...
이유가 무엇인지 모르겠으나 현재까지 리뷰 남겨주신 부분들이... 제가 중간에 작업했던 코드들입니다..

아래 수정 필요한 내용 대부분이 동일한 문제를 갖고 있습니다.

제가 push 후 pr 할 때 문제가 있었을까요?

2020-12-28 13:39 UTC, merged