[김원희] Add: 초기 설정 완료
wecode-bootcamp-korea/westagram-backend pull request #134
Opened 2020-12-01 07:12 UTC by supersaloon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-09 18:26 UTC, lordmyshepherd approved these changes

2020-12-09 18:26 UTC, lordmyshepherd commented
LGTM 👍

2020-12-09 18:27 UTC, merged

2020-12-09 18:29 UTC, jamessoun93 requested changes
원희님 PR merge 되었어도 남겨드린 리뷰는 꼭 반영해주세요!

2020-12-09 18:29 UTC, jamessoun93 commented on students/15th/team1/wonhee_kim/my_settins.py
> +# SECRET_KEY = 'vk$a@emx)hl0ec8%l)%k6eb^8*qjatg9ks0!)qxwz7p$#su229'
- 이런 민감한 정보를 담고있는 파일은 꼭 `.gitignore` 에 추가해서 `git` 에 올라오지 않도록 해주셔야 합니다.
- 이미 이 파일이 올라와 있으므로 `.gitignore` 에 추가해도 변함이 없을텐데 [[Git] Github에 잘못 올라간 파일 삭제하기](https://gmlwjd9405.github.io/2018/05/17/git-delete-incorrect-files.html)를 참고해주세요.

2020-12-09 18:29 UTC, jamessoun93 commented on students/15th/team1/wonhee_kim/westargram/settings.py
> +ALLOWED_HOSTS = []
`'*'` 추가해주셔야 외부에서 들어오는 요청을 처리할 수 있습니다.

2020-12-09 18:29 UTC, jamessoun93 commented on students/15th/team1/wonhee_kim/westargram/urls.py
> +from django.contrib import admin
`settings.py` 에서 주석처리해서 에러날텐데 없애주세요~

2020-12-10 07:04 UTC, supersaloon commented on students/15th/team1/wonhee_kim/my_settins.py
> +# SECRET_KEY = 'vk$a@emx)hl0ec8%l)%k6eb^8*qjatg9ks0!)qxwz7p$#su229'
넵 반영하겠습니다.

2020-12-10 07:07 UTC, supersaloon commented on students/15th/team1/wonhee_kim/westargram/settings.py
> +ALLOWED_HOSTS = []
초기 설정하고 PR 보낼 때 누락되었습니다. 현재는 수정된 상태입니다.

2020-12-10 07:07 UTC, supersaloon commented on students/15th/team1/wonhee_kim/westargram/urls.py
> +from django.contrib import admin
주석처리한 부분 삭제하도록 하겠습니다.