[15기 김승재]  Add: westagram 프로젝트 초기 설정
wecode-bootcamp-korea/westagram-backend pull request #135
Opened 2020-12-01 07:23 UTC by seungjaekim-git

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-04 06:45 UTC, seungjaekim-git commented
wecode PR message template 및 체크 리스트 입니다.
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

수정 사항 간략한 한줄 요약

Westagram 로그인 및 회원가입 구현 완료
포스팅 모델링 까지 완료 !

수정 사항들 자세한 내용

아직 없음

체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요

[ x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
[ x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
[ x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
[ x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-08 07:13 UTC, leejaek reviewed
slug URL이라던지 다양한 방법 사용하신거 보고 많이 배워갑니다!

2020-12-08 07:13 UTC, leejaek commented on students/15th/team4/seungjae_kim/posting/views.py
> +            return HttpResponse(status=200)
여기안 HttpResponse로 처리하신 이유가 있을까요?

2020-12-08 07:13 UTC, leejaek commented on students/15th/team4/seungjae_kim/user/models.py
> +    password = models.CharField(max_length = 64,
추후 Hashed password 저장을 위해 max_length 길이 조정이 필요할것 같습니다.

2020-12-09 01:49 UTC, seungjaekim-git commented on students/15th/team4/seungjae_kim/user/ursl.py
> +#!/usr/bin/env python
실수로 생성된 파일인거 같네요. 삭제했습니다.

2020-12-09 02:04 UTC, seungjaekim-git commented on students/15th/team4/seungjae_kim/posting/views.py
> +            return HttpResponse(status=200)
한번 써보고 싶어서 써보았는데 JsonResponse로 고칠게요 !

2020-12-09 02:04 UTC, seungjaekim-git commented on students/15th/team4/seungjae_kim/user/models.py
> +    password = models.CharField(max_length = 64,
아 감사합니다 ! 수정할게요 !

2020-12-10 05:22 UTC, jamessoun93 requested changes

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/posting/views.py
> +            return JsonResponse({'data' : posts}, status = 200)
`JsonResponse` 에 이미 `serialize` 하는 기능이 있으니 `serialize` 를 따로 해줄 필요없이 파이썬 리스트로 변환하여 리턴해주시면 됩니다.

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/posting/views.py
> +
`=` 기준으로 정렬만 해주셔서 코드만 조금 예쁘게 다듬어주시면 좋을 것 같고, 그 외에는 완벽합니다 👍

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/posting/views.py
> +
여기는 그냥 붙여주시는게 보기 편할 것 같네요.

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/posting/views.py
> +            return HttpResponse(status=200)
- `HttpResponse` 잘쓰셨습니다. 댓글 등록 `POST` 같은경우 굳이 `JSON body` 를 보내줘야할 필요까지 없이 `status code` 로만 성공 여부를 알 수 있기때문에 `HttpResponse` 로 리턴해주셔도 무방합니다.
- 다만 우리 프론트분들이 `JSON body` 가 없을때 어떻게 처리를 해야하는지 아직 잘 모를 가능성이 높기때문에 붙여보실때는 꼭 서로 상의 하에 결정해주세요.

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/models.py
> +    password = models.CharField(max_length = 64,
@leejaek 👍👍👍

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/models.py
> +                                )
이정도 `kwargs` 는 그냥 한줄로 처리해주시는게 가독성이 더 좋습니다.

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/urls.py
> +from user.views import UserView,SigninView
`import` 문을 기준으로 정렬해주세요.

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/urls.py
> +# -*- coding: utf-8 -*-
없애주세요!

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/ursl.py
> +#!/usr/bin/env python
아직 올라와있는걸보니 삭제 후 push 를 안해주신 것 같은데 반영해서 push 부탁드립니다.

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/views.py
> +            return JsonResponse({'MESSAGE': "INVALID_USER"},status=401)
마무리가 덜 되었네요. 작업 마무리해서 push 해주세요.

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/views.py
> +
이런 validation 로직은 따로 파일을 분리해주신다음 사용하고 싶으신곳에서 해당 함수만 import 해서 사용하시는게 깔끔합니다. 한번 시도해보세요!

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/views.py
> +class UserView(View):
클래스명만보고 로그인인지 회원가입인지 알기가 어렵습니다. 다른 개발자가 볼 때 한눈에 파악이 가능하도록 클래스명을 지어주세요.

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/views.py
> +                return JsonResponse({"MESSAGE" : "USER_ALREADY_EXISTS"},status = 400)
이렇게 단순히 존재하는지만 확인하려고 할때는 뒤에 `exists()` 를 붙여주셔야 불필요하게 필터 조건에 맞는 객체들을 불러들이는 걸 방지할 수 있습니다.

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/views.py
> +            else:
바로 위 `if` 문에 `return` 문이 있기때문에 `else` 는 불필요합니다.

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/views.py
> +                return JsonResponse({"MESSAGE" : "SUCCESS"},status =201)
`201` 👍👍👍
```suggestion
                return JsonResponse({"MESSAGE" : "SUCCESS"}, status=201)
```

2020-12-10 05:22 UTC, jamessoun93 commented on students/15th/team4/seungjae_kim/user/views.py
> +            return JsonResponse({"MESSAGE": f"{e}"}, status = 400)
```suggestion
        except KeyError:
            return JsonResponse({'MESSAGE': "KEY_ERROR"},status=400)
        
        except AssertionError as e:
            return JsonResponse({"MESSAGE": f"{e}"}, status=400)
```

2020-12-11 13:54 UTC, closed without merging