[15기 석여주]initial settings
wecode-bootcamp-korea/westagram-backend pull request #145
Opened 2020-12-06 17:29 UTC by YEOJU-SEOK

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-09 15:03 UTC, YEOJU-SEOK commented
수정예정입니다

2020-12-14 07:02 UTC, lordmyshepherd requested changes

2020-12-14 07:02 UTC, lordmyshepherd commented on students/15th/team3/yeoju-seok/user/views.py
> +        password_check = bcrypt.checkpw(data['password'].encode('utf-8'),user_pw.encode('utf-8'))
line 52와 합쳐주세요. 한 줄 더 줄일 수 있습니다.
```suggestion
        
```

2020-12-14 07:02 UTC, lordmyshepherd commented on students/15th/team3/yeoju-seok/user/views.py
> +                if password_check == True:
```suggestion
                if bcrypt.checkpw(data['password'].encode('utf-8'),user_pw.encode('utf-8')):
```

2020-12-14 07:02 UTC, lordmyshepherd commented on students/15th/team3/yeoju-seok/user/views.py
> +import re
`import json, bcrypt, jwt, re`

2020-12-14 07:02 UTC, lordmyshepherd commented on students/15th/team3/yeoju-seok/user/views.py
> +import re
한 줄로 수정해주세요~

2020-12-14 07:02 UTC, lordmyshepherd commented on students/15th/team3/yeoju-seok/user/views.py
> +                    access_token = jwt.encode({'id' : user_id},SECRET,algorithm = 'HS256').decode('utf-8')
알고리즘도 my_settings.py로 빼주세요.

2020-12-14 07:02 UTC, lordmyshepherd commented on students/15th/team3/yeoju-seok/user/views.py
> +            return JsonResponse({"message":"INVALID_USER"},status=401)
마찬가지로 명확한 에러가 아니면 except 문만 사용하지 않도록 주의해주세요.

2020-12-28 13:39 UTC, merged