Feature/signup
wecode-bootcamp-korea/westagram-backend pull request #146
Opened 2020-12-08 00:27 UTC by supersaloon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
- 이메일, 닉네임 또는 전화버호 셋 중에 하나를 받아서 회원가입
- 이메일, 닉네임 또는 전화번호에 대한 중복 검사(DB 확인)
- 이메일, 닉네임, 전화번호, 패스워드에 대한 형식 검삭(정규식)
- 패스워드를 암호화하여 DB에 저장(bcrypt)
- 각 단계마다 실패시 에러 반환
- 모든 단계 성공시 DB에 사용자 정보 저장 및 200 OK 반환

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-09 06:36 UTC, kst6294 reviewed
별*5

2020-12-09 06:36 UTC, kst6294 commented on students/15th/team1/wonhee_kim/user/models.py
> +	def __str__(self):
이 코드를 사용하면 어떤 결과가 나타나나요?

2020-12-09 06:36 UTC, kst6294 commented on students/15th/team1/wonhee_kim/user/views/signup_views.py
> +            print(f'e: {e}')
좋은 디버깅 방법 배워갑니다!

2020-12-09 06:36 UTC, kst6294 commented on students/15th/team1/wonhee_kim/westargram/settings.py
> +USE_TZ = True
False를 안하고도 시간이 정상적으로 한국시간으로 저장 되나요?

2020-12-09 08:14 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/models.py
> +	def __str__(self):
장고 쉘에서 DB 객체를 리턴되는 값으로 찍어볼 수 있습니다.

2020-12-09 08:15 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/views/signup_views.py
> +            print(f'e: {e}')
감사합니다 : )

2020-12-09 08:15 UTC, supersaloon commented on students/15th/team1/wonhee_kim/westargram/settings.py
> +USE_TZ = True
https://fbdjango.wordpress.com/2016/05/13/183432721693235_1011994302170402/

참고하시면 좋을 듯 합니다.

2020-12-10 02:15 UTC, lordmyshepherd requested changes

2020-12-10 02:15 UTC, lordmyshepherd commented on students/15th/team1/wonhee_kim/user/views/signup_views.py
> +            return JsonResponse({"MESSAGE": "KEY_ERROR"}, status=400)
여기서 Key Error가 날 수 있는 상황이 언제인가요?

2020-12-10 07:38 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/views/signup_views.py
> +        print("================= 회원가입 절차 기동 =================")
넵 로컬에서만 확인하고 push할 때는 지우도록 하겠습니다.

2020-12-10 07:45 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/views/signup_views.py
> +        except Exception as e:
어떤 에러가 발생하더라도 일단 동작은 하도록 Exception으로 받도록 했는데
정확히 어떻게 동작하고 어떤 에러가 발생하는지 확인하여 수정하겠습니다.

2020-12-10 07:45 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/views/signup_views.py
> +            return JsonResponse({"MESSAGE": "NO_ACCOUNT"}, status=400)
넵 정리 잘 해서 간결하게 수정하도록 하겠습니다.

2020-12-10 07:47 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/views/signup_views.py
> +            return JsonResponse({"MESSAGE": "KEY_ERROR"}, status=400)
그냥 복사 붙여넣기 하다가 KEY_ERROR 라고 썼습니다.
저확히 분석해서 수정하도록 하겠습니다.

2020-12-10 08:44 UTC, closed without merging