[김원희] ADD: [Mission 8] 게시물 및 댓글 삭제 기능 구현 완료
wecode-bootcamp-korea/westagram-backend pull request #160
Opened 2020-12-10 04:00 UTC by supersaloon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 게시물, 댓글 삭제 구현 및 코드 리펙토링(URL 등)
		 
## 수정 사항들 자세한 내용
- 게시물 삭제 엔드 포인트 구현
  - 데코레이터로 사용자 인증
  - 게시물 존재 확인
  - 게시물이 존재하더라도 사용자가 작성한 것이 아니면 404 리턴
- 댓글 삭제 엔드 포인트 구현
  - 데코레이터로 사용자 인증
  - 댓글 존재 확인
  - 댓글이 존재하더라도 사용자가 작성한 것이 아니면 404 리턴
- 코드 리펙토링(URL 등)
  - URL 체계 변경(기능이 먼저 나오고 뒤에 액션이 나오는 방식으로 변경)
    - 기존: /create/post
    - 변경: /post/create
  - 파라미터 전달 방식 변경
    - 기존: 전부 post 에 담아서 전달
    - 변경: 조회, 삭제의 경우 get 방식으로 변경, url 마지막에 게시글, 댓글 id 값 전달

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-10 09:02 UTC, jamessoun93 requested changes
user app 도 다른 리뷰내용과 비슷한 내용이 많아서 참고하여 반영해주시면 추가적으로 리뷰 남기겠습니다.

2020-12-10 11:39 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/models.py
> +	password_changed_at = models.DateTimeField(null=True)
권고하신 가이드 대로 수정하였습니다.

2020-12-10 11:39 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/models.py
> +	password_changed_at = models.DateTimeField(null=True)
권고하신 가이드대로 수정하였습니다.

2020-12-10 23:38 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/models.py
> +	update_at  = models.DateTimeField(null=True)
null=True 제거하고, auto_now=True 추가하였습니다.

2020-12-10 23:39 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/models.py
> +		db_table = 'posts'
코드 확인하였는데 현재 로컬에서 들여쓰기 4칸으로 맞춰진 상태입니다. push한 뒤 다시 한번 확인해 보겠습니다.

2020-12-10 23:39 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/models.py
> +		return str(self.user.name) + "의 " + "post" + " / id" + "(" + self.id + ")"
이부분도 코드 확인하였는데 코드 확인하였는데 현재 로컬에서 들여쓰기 4칸으로 맞춰진 상태입니다. push한 뒤 다시 한번 확인해 보겠습니다.

2020-12-10 23:40 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/models.py
> +	updated_at = models.DateTimeField(null=True)
이부분도 null=True 제거하고, auto_now=True 추가하였습니다.

2020-12-10 23:43 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/views/comment_views.py
> +from user.utils       import login_required
감사합니다 : )

2020-12-10 23:44 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/models.py
> +	email               = models.CharField(max_length=100, null=True)
EmailField로 수정하였습니다.

2020-12-10 23:44 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/models.py
> +	phone_number        = models.CharField(max_length=11, null=True)
name 필드에 null=True 제거했습니다.
회원가입 조건이 사용자명, 이메일, 전화번호 셋 중 하나만으로 가입한다는 가정이어서 셋 모두에 null=Ture를 줬습니다.
이 과정에서 name까지 null=True를 주는 실수를 했습니다.

그리고 사용자명, 이메일, 전화번호에 unique=Ture 설정했습니다.

2020-12-10 23:49 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/utils.py
> +from django.http            import JsonResponse
import 앞 부분 공백 제거하였습니다.

2020-12-10 23:53 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/utils.py
> +from westargram.my_settings import SECRET_KEY, encryption_algorithm
대문자로 수정하였습니다.

2020-12-10 23:59 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/utils.py
> +            request.user    = user
user_id 부분 삭제했습니다.

2020-12-11 00:03 UTC, supersaloon commented on students/15th/team1/wonhee_kim/westargram/settings.py
> +from . my_settings import DATABASES, SECRET_KEY
수정하였습니다.

2020-12-11 00:12 UTC, supersaloon commented on students/15th/team1/wonhee_kim/westargram/settings.py
> +from . my_settings import DATABASES, SECRET_KEY
가이드 해주신 대로 수정하면 
```bash
    from my_settings import DATABASES, SECRET_KEY
ModuleNotFoundError: No module named 'my_settings'
```

2020-12-11 03:54 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/utils.py
> +        return func(self, request, *args, **kwargs)
jwt.InvalidTokenError 확인하여 except 분기 처리하였습니다.

2020-12-11 03:54 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/utils.py
> +            return JsonResponse({'MESSAGE': 'AUTHORIZATION FAIL: INVALID_TOKEN'}, status=401)
각 경우별로 except를 분기하였습니다.

2020-12-11 03:56 UTC, supersaloon commented on students/15th/team1/wonhee_kim/user/utils.py
> +            user            = User.objects.get(id=user_id) if user_id else None
제가 의도하지 않은 코드였습니다.
이부분 삭제하고 제가 의도했던 대로 데코레이터를 전체적으로 리팩토링하였습니다.

2020-12-12 10:47 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/urls.py
> +    path('/post/delete/<int:post_id>', DeletePostView.as_view()),
하나의 클래스에서 각 요청에 맞는 메소드(get, post, put, delete)로 처리하도록 수정했습니다.

2020-12-12 10:47 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/urls.py
> +    path('/comment/delete/<int:comment_id>', DeleteCommentView.as_view()),
이부분도 각각 적절한 메소드로 처리하도록 수정하였습니다.

2020-12-12 10:48 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/views/comment_views.py
> +
각각 적절한 메소드로 처리하도록 수정하였고, 개발단계에서 사용한 print 문들은 삭제하였습니다.

2020-12-12 10:48 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/views/comment_views.py
> +        return JsonResponse({'MESSAGE': 'SUCCESS'}, status=201)
하나의 try 문에 각각의 except를 잡는 방식으로 수정했습니다.

2020-12-12 10:49 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/views/comment_views.py
> +        return JsonResponse({'MESSAGE': 'SUCCESS'}, status=200)
하나의 클래스로 합쳤습니다.

2020-12-12 10:51 UTC, supersaloon commented on students/15th/team1/wonhee_kim/post/urls.py
> +from .views.like_views        import LikeView
게시글 관련 -> post_views.py 
댓글 관련 -> comment_views.py
좋아요 관련 -> like_views.py 
로 각각 통합하였습니다.

2020-12-28 13:40 UTC, merged