Add: 16기김진수 장고 프로젝트 초기설정
wecode-bootcamp-korea/westagram-backend pull request #163
Opened 2020-12-29 07:47 UTC by xchdtk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-01 10:18 UTC, ddalkigum requested changes

2021-01-01 10:18 UTC, ddalkigum commented on students/16th/team1/jinsookim/user/views.py
> +        q = Q()
```suggestion
  
```
이 부분은 빼도 될 것 같에요,

2021-01-01 10:18 UTC, ddalkigum commented on students/16th/team1/jinsookim/posting/models.py
> +    upadte_time  =  models.DateField(auto_now_add=True)
```suggestion
    create_time = models.DateField(auto_now_add = True)
    update_time = models.DateField(auto_now = True)
```
생성시간은 auto_now_add로 만들어야되고, 수정한 시간은 auto_now로 만들어서 저장 해줘야 되요

2021-01-01 10:18 UTC, ddalkigum commented on students/16th/team1/jinsookim/user/views.py
> +        user = data['user']
```suggestion
email = data['email']
```
변수명은 어떤 의미인지 알 수 있게 지어주세요 

login_decorator 같은 경우에는 user view 에서만 사용하기 보다는 
여러곳에서 사용 할 수 있기 때문에, 절대경로에서 import 할 수 있게 해주는게 좋을 것 같에요

2021-01-01 10:18 UTC, ddalkigum commented on students/16th/team1/jinsookim/user/views.py
>  class Sign_Up(View):
```suggestion
class SignUp(View):
```
클래스이름 바꿔주세요!

2021-01-05 06:43 UTC, jamessoun93 requested changes
진수님 너무 잘하셨습니다~ 리뷰 내용 확인하시고 반영해주세요!

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/models.py
> +    email        = models.EmailField(max_length = 254, null=True)
이렇게 3개의 필드 전부 `null=True` 를 주신다면 `password` 만 들어와도 `User` 데이터 생성이 가능해진다는 뜻입니다. 문제 파악을 잘못 하신 것 같네요. 3개의 필드 중 하나는 필수값이어야 합니다.

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/models.py
> +    password     = models.BinaryField(max_length = 500)
`password` 부분에 암호화를 마친 문자열을 넣어주기때문에 `CharField` 로 선언해주시면 됩니다.

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/views.py
>  class Sign_Up(View):
@ddalkigum 👍

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/views.py
> +from user.utils import login_decorator
이 부분은 여러개의 import 문이 뒤섞여 있어서 가독성이 좋지 않습니다. 
가독성이 좋아질 수 있게끔 재정렬해주세요.

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/utils.py
> +            token = request.headers.get("Token")
`access token`은 `headers`의 `Authorization` 에 넣어서 보내주기 때문에 그에 맞는 `key`로 받아주셔야 합니다.

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/utils.py
> +            jwt_user = jwt.decode(token, SECRET, algorithms="HS256")
jwt decode 하신 후 과정이 없네요? 아직 진행중이신가요?

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/utils.py
> +            return JsonResponse({"message :" : "해당 게시물이 없습니다."}, status=401)
Post 관련 에러처리를 여기서 해주신 이유가 있을까요?

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/views.py
> +        password     = data.get("password")
여기서 전부 `get()`을 사용하신 이유를 설명해주세요!

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/views.py
> +                return JsonResponse({'MESSAGE': 'KEY_ERRORS'}, status=400)
`KeyError` 는 이렇게 하나하나 직접 조건문으로 걸어서 띄워주실 필요없이 앞서 남겨드린 모델링 리뷰 반영하여 이 `if` 문 없이도 원하는 `Key` 가 들어오지 않는다면 `KeyError` 가 발생할 수 있도록 수정해주세요.

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/views.py
> +                return JsonResponse({'MESSAGE': 'KEY_ERRORS'}, status=400)
여기도 마찬가지입니다.

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/views.py
> +                    return JsonResponse({"message" :"이미 회원가입 되어있습니다."}, status = 400)
이 부분들도 모델 수정 사항에 따라 로직이 조금 변경될 것 같아서 모델먼저 수정해주시고 한번 어떤 부분이 불필요할 지 찾아보고 적용해주세요.

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/views.py
> +                                password      = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
`decode` 해서 저장해주세요.

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/views.py
> +            new_password = data['password']
- `=` 을 기준으로 정렬해주시고 구분을 위해 아래 한 줄 추가해주세요.
- 비밀번호 변수명을 `new_password`로 지어주신 이유가 있나요?

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/views.py
> +            if Users.objects.filter(Q(user_name=account) | Q(phone_number=account)|Q(email =account)).exists()==True:
`exists()` 자체가 `boolean` 값을 리턴하기 때문에 이 부분은 줄여줄 수 있습니다.

2021-01-05 06:43 UTC, jamessoun93 commented on students/16th/team1/jinsookim/user/views.py
> +                    return JsonResponse( {"ACCESS_TOKEN": access_token}, status = 200)
구현하신 내용을 확인하면 들어온 유저 정보를 가지고 `filter` 를 통한 쿼리를 날려서 쿼리셋을 반환받는데 어짜피 조건에 맞는 유저 객체 하나만 가져오면 되는 부분이라 전제적으로 수정을 할 수 있습니다. 시도해보세요!

2021-01-28 07:39 UTC, merged