Add: 16기 장진욱 장고 프로젝트 초기설정
wecode-bootcamp-korea/westagram-backend pull request #164
Opened 2020-12-29 07:47 UTC by jinukix

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-29 07:50 UTC, jamessoun93 requested changes

2020-12-29 07:50 UTC, jamessoun93 commented on students/16th/team1/jinukjang/westagram/urls.py
> +from django.contrib import admin
저희는 장고 admin을 사용하지 않습니다. 지워주세요!

2021-01-05 02:30 UTC, jinukix commented on students/16th/team1/jinukjang/posts/urls.py
> +from .views      import CreatePostView, PostView, CreateCommentView, CommentView, PostLikeView
조언 감사합니다.~_~

2021-01-05 02:30 UTC, jinukix commented on students/16th/team1/jinukjang/users/views.py
> +
감사합니답

2021-01-05 07:47 UTC, jamessoun93 requested changes
진욱님 코드 너무 깔끔하네요!! 👍👍👍
리뷰 남겨드렸으니 수정사항 반영해주세요~

2021-01-05 07:47 UTC, jamessoun93 commented on students/16th/team1/jinukjang/users/models.py
> +# Create your models here.
불필요한 주석 지워주세요~

2021-01-05 07:47 UTC, jamessoun93 commented on students/16th/team1/jinukjang/users/models.py
> +    user_id  = models.CharField(max_length=10)
- `user_id` 라는 변수명은 `foreign key` 필드와 헷갈릴 수 있는 여지가 있으니 `username` 같은 변수명으로 변경해주시면 좋을 것 같습니다.
- 그리고 view를 확인해보니 username 은 unique 값이네요! 로직으로 적용이 되어있지만, 모델도 적용해주세요.

2021-01-05 07:47 UTC, jamessoun93 commented on students/16th/team1/jinukjang/users/views.py
> +
👍👍👍

2021-01-05 07:47 UTC, jamessoun93 commented on students/16th/team1/jinukjang/users/views.py
> +            if phone    != None and not phone.replace('-','').isdigit():
https://jaredgrubb.blogspot.com/2009/04/python-is-none-vs-none.html
위 링크 내용을 읽어보시고 한번 수정해보세요!

2021-01-05 07:47 UTC, jamessoun93 commented on students/16th/team1/jinukjang/users/views.py
> +                return JsonResponse({'MESSAGE :':"PHONENUMBER_SHOULD_CONTAIN_ONLY_DIGITS"},status = 400)
모든 `return` 문에서 `MESSAGE :` 를 통째로 `key`로 써주고 계신데 그렇게 하실 필요가 없습니다. 실제로 return 되는 value 를 확인하시고 이렇게 따옴표를 추가해주신걸까요?

2021-01-05 07:47 UTC, jamessoun93 commented on students/16th/team1/jinukjang/users/models.py
> +    nickname = models.CharField(max_length=20)
`nickname`도 마찬가지로 `unique` 값이네요!

2021-01-05 07:47 UTC, jamessoun93 commented on students/16th/team1/jinukjang/users/views.py
> +                password = password
`password` 암호화를 안하시고 그냥 넣어주시네요!? 암호화 해서 넣어주세요~

2021-01-05 07:47 UTC, jamessoun93 commented on students/16th/team1/jinukjang/users/views.py
> +            if user.password == data['password']:
password 를 암호화해서 넣어주시는 로직으로 변경하신다면 이쪽에 변경사항이 생기실거에요!

2021-01-28 07:38 UTC, merged