Add: 16기 이성용 장고프로젝트 초기설정
wecode-bootcamp-korea/westagram-backend pull request #165
Opened 2020-12-29 07:47 UTC by klioop

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-29 16:49 UTC, klioop commented on students/16th/team1/sungyong_Lee/account/models.py
> +    email         = models.EmailField(max_length=50)
email 에 unique 값을 주고 이미 db 에 저장된 이메일과 같은 값으로 request test 를 하였더니, 오류가 발생했습니다. 
unique  값을 model 에서 설정할 경우 view 에서 따로 같은 값을 체크해주는 코드를 작성하지 않아도 되나요?

2020-12-29 16:52 UTC, klioop commented on students/16th/team1/sungyong_Lee/account/views.py
> +
처음에는 아래 주석 으로 달린 코드를 먼저 작성했는데요. 위 코드 처럼 짤 때 간결해져서 위 처럼 작성 했습니다. 하지만 에러메세지를 세분하는 코드를 짜려면 if 문을 계속 사용해야 할 것 같아서 일단 위 처럼만 해놨는데, 아래 주석 달린 코드에서 처럼 각 에러를 알려주는 게 더 좋은 방향인가요?

2021-01-04 10:28 UTC, klioop commented on students/16th/team1/sungyong_Lee/account/views.py
> +            return JsonResponse({"message": "hi"}, status=400)
오 수정했어요 감사합니다

2021-01-05 08:19 UTC, jamessoun93 requested changes
성용님! 전반적으로 코드가 너무 깔끔합니다~ 리뷰내용 반영해서 push 해주세요!

2021-01-05 08:19 UTC, jamessoun93 commented on students/16th/team1/sungyong_Lee/account/views.py
> +                password     = password_encoded,
데이터베이스에는 `byte` 로 `encoding` 된 데이터보다는 `decode` 된 문자열 그대로를 저장해주세요!

2021-01-05 08:19 UTC, jamessoun93 commented on students/16th/team1/sungyong_Lee/account/views.py
> +            password     = data[1]
이렇게 value 들만 처리를 해주시는 이유가 있으신가요!?

2021-01-05 11:34 UTC, klioop commented on students/16th/team1/sungyong_Lee/account/views.py
> +            password     = data[1]
리뷰 잘봤습니다. 감사합니다 :)
data.values( ) 로 가져오는 이유는 사용자가 이름, 이메일, 또는 폰번호로 중 하나로만  로그인 할 수 있다고 생각했기 때문에 저렇게 했습니다. 보통 id, email, 번호 셋 중 하나만 id 에 입력하니까요.

values  로 가져오지 않으면, 이름으로, 이메일로, 또는 폰 번호로 로그인할 때를 나누어서 모두 코드를 써줘야 한다고 생각했습니다.  values 로 가져오면 어떤 것으로 로그인 하던지 상관없이 깔끔한 코드로 로그인 id 를 정해줄 수 있다고 생각했습니다.

2021-01-28 07:38 UTC, merged