[홍연우] Mission 1: 장고 초기세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #169
Opened 2020-12-29 07:48 UTC by redsaumon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Mission 1 초기 세팅
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
Mission 2 진행 중인 코드가 있는데 무시해주세요

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-05 12:49 UTC, jamessoun93 requested changes
전체적으로 너무 깔끔하네요 연우님! 👍
리뷰 남겨드렸으니 반영해서 push 해주세요!

2021-01-05 12:49 UTC, jamessoun93 commented on students/16th/team1/yeonu_hong/user/models.py
> +    email     = models.EmailField(max_length=130, null=True)
`email`, `phone`, `name` 셋 중 한가지는 필수값이어야 합니다!

2021-01-05 12:49 UTC, jamessoun93 commented on students/16th/team1/yeonu_hong/user/views.py
> +from .models      import User, Follow
너무 깔끔하지만 조금 더 발전시킬 수 있다면, 구분을 위해 그룹을 지어주시는 방법이 있습니다. 한번 시도해보세요!

2021-01-05 12:49 UTC, jamessoun93 commented on students/16th/team1/yeonu_hong/user/views.py
> +            # 들어오는 값만 변수에 지정하기 어떻게 하지?!
고민의 흔적이 잘 보여서 좋네요 ㅎㅎㅎ 하지만 github에 push 를 한다는것은 해당 코드가 merge-ready 상태여야 한다는 뜻이기 때문에 이런 주석은 없애주신 뒤 push 해주세요~

2021-01-05 12:49 UTC, jamessoun93 commented on students/16th/team1/yeonu_hong/user/views.py
> +            email = data['email']
셋 중 하나만 들어와도 가입이 진행되어야 하는데 KeyError 로 넘어가는 이유는 여기에 있습니다! 그냥 파이썬 shell 에서 아무 dictionary나 만든 뒤 해당 dictionary 에 없는 key 값을 접근해보세요!

2021-01-05 12:49 UTC, jamessoun93 commented on students/16th/team1/yeonu_hong/user/views.py
> +            password_decoded = password_encoded.decode('utf-8')
너무 깔끔하게 구현해주셨네요 👍
하지만 이런 부분은 이제 프로세스를 아시기 때문에 아래처럼 한줄로 줄여서 써주셔도 좋을 것 같아서 남겨드립니다.
```suggestion
            hashed_password = bcrypt.hashpw(password, bcrypt.gensalt()).decode('utf-8')
```

2021-01-05 12:49 UTC, jamessoun93 commented on students/16th/team1/yeonu_hong/user/views.py
> +
구분을 위한 빈줄은 한줄 정도면 충분합니다!

2021-01-05 12:49 UTC, jamessoun93 commented on students/16th/team1/yeonu_hong/user/views.py
> +                return JsonResponse({'message': '이미 사용중인 email'}, status=400)
`if` 조건에서 `filter` 를 통해 쿼리셋 리스트를 가져오게 되는데, 불필요하게 전부 가져올 필요 없이 존재하는지 여부만 확인할 수 있는 메소드가 있습니다. 알아보시고 적용해보세요.

2021-01-05 12:49 UTC, jamessoun93 commented on students/16th/team1/yeonu_hong/user/views.py
> +                return JsonResponse({'message': 'SUCCESS'}, status=201)
`name`, `phone`, `email` 이 전부 존재해야만 새로운 유저를 `create` 해줄 수 있게끔 하셨는데, 원래 의도하신 바랑 다르지 않나요?

2021-01-05 12:49 UTC, jamessoun93 commented on students/16th/team1/yeonu_hong/westagram/urls.py
> +    path('comment/', include('post.urls')),
저희는 뒤에 `/` 를 붙이지 않고 `app` 의 `urls.py` 에서 `path` 마다 `/` 를 앞에 주는 컨벤션을 지키고 있습니다!

2021-01-05 12:49 UTC, jamessoun93 commented on students/16th/team1/yeonu_hong/user/views.py
> +            return JsonResponse({'message':'KEY_ERROR 비번만넣음'}, status=400)
연우님, 너무 잘해주셨는데 원래 미션의 의도가 잘못 전달이 되었던 것 같습니다! (이 부분은 연우님뿐만 아니라 거의 대부분 이해를 잘못하신 것 같아서 미션 내용을 수정했습니다.)

원래 미션내용은 로그인할때 비밀번호를 제외하고 꼭 필요로 하는 정보를 이메일, 폰번호, 이름 중에 골라서 해당 값으로 로그인을 처리하라는 요구사항 이었습니다. 헷갈려하시는분들이 많으셔서 email 로 통일하였으니, email 과 password 받아서 로그인 처리하는 로직으로 수정해보세요!

2021-01-06 03:07 UTC, redsaumon commented on students/16th/team1/yeonu_hong/user/models.py
> +    email     = models.EmailField(max_length=130, null=True)
네!

2021-01-06 06:46 UTC, redsaumon commented on students/16th/team1/yeonu_hong/user/views.py
> +from .models      import User, Follow
네~ 깔끔하게 정리해볼게요!

2021-01-06 06:47 UTC, redsaumon commented on students/16th/team1/yeonu_hong/user/views.py
> +            # 들어오는 값만 변수에 지정하기 어떻게 하지?!
넵!! 맨날 혼자만 봐서 메모장처럼 다 써놨네요ㅎ

2021-01-06 06:50 UTC, redsaumon commented on students/16th/team1/yeonu_hong/user/views.py
> +            email = data['email']
네.. 자주 보던 KeyError 또 보고 왔습니다~ 궁금한 점이 있는데요! 만약 mission 2 잘못 이해했던 것처럼 name, phone, email 셋 중 아무 값이나 들어오는 애로 회원가입을 진행한다고 하면, if 'name' in  data 이런 식으로 하나하나 확인하고 값을 저장해 줘야 할까요?

2021-01-06 06:51 UTC, redsaumon commented on students/16th/team1/yeonu_hong/user/views.py
> +            password_decoded = password_encoded.decode('utf-8')
넵!!

2021-01-06 06:52 UTC, redsaumon commented on students/16th/team1/yeonu_hong/user/views.py
> +
네! 수정하겠습니다~ 승현님 한 class 내의 여러 메서드 구분, class끼리의 구분도 한줄씩 쓰면 될까요?

2021-01-06 06:54 UTC, redsaumon commented on students/16th/team1/yeonu_hong/user/views.py
> +                return JsonResponse({'message': '이미 사용중인 email'}, status=400)
넵! 혹시 exists()를 말씀하시는 건가요? 처음에 넣었다가 if문에 문자열 들어오면 True로 넘어가길래 지워버렸는데 최대한 DB를 안다녀오는 게 효율적일까요?

2021-01-06 06:55 UTC, redsaumon commented on students/16th/team1/yeonu_hong/user/views.py
> +                return JsonResponse({'message': 'SUCCESS'}, status=201)
헐 네 그러네요 왜 저렇게 했을까요 수정해서 push 하겠습니다~

2021-01-06 06:59 UTC, redsaumon commented on students/16th/team1/yeonu_hong/westagram/urls.py
> +    path('comment/', include('post.urls')),
넵!

2021-01-06 07:01 UTC, redsaumon commented on students/16th/team1/yeonu_hong/user/views.py
> +            return JsonResponse({'message':'KEY_ERROR 비번만넣음'}, status=400)
승현님이 말씀해 주신 대로 다시 작성해보겠습니다~ 감사합니다!! :+1:

2021-01-07 05:36 UTC, redsaumon commented on students/16th/team1/yeonu_hong/user/models.py
> +    email     = models.EmailField(max_length=130, null=True)
@jamessoun93 승현님! name, phone, email 중 아무 값이나 들어와도 회원가입이 되게 변경해봤는데 이럴 때는 세가지 모두 null=True로 지정해주는 게 맞는 방법인가요?

2021-01-28 07:37 UTC, merged