[이혜성] 장고 프로젝트 초기 설정
wecode-bootcamp-korea/westagram-backend pull request #170
Opened 2020-12-29 07:52 UTC by hyeseong-dev

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-05 13:58 UTC, jamessoun93 requested changes
혜성님도 코드가 너무 깔끔하시네요!!
리뷰 남겨드렸으니 반영해서 push 해주세요~

2021-01-05 13:58 UTC, jamessoun93 commented on students/16th/team1/hyeseonglee/user/views.py
> +                return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
둘 중 하나라도 없다면 `data['email']` 과 `data['password']` 에서 이미 `KeyError` 가 발생하므로 이 부분은 필요가 없습니다.

2021-01-05 13:58 UTC, jamessoun93 commented on students/16th/team1/hyeseonglee/user/views.py
> +                return JsonResponse({'MESSAGE':'SUCCESS'}, status=201)
- `201` 굳굳입니다!
- 하지만 비밀번호 암호화 과정이 빠졌네요!

2021-01-05 13:58 UTC, jamessoun93 commented on students/16th/team1/hyeseonglee/user/views.py
> +            return JsonResponse({'MESSAGE': 'VALUE ERROR OCCURED!'},status=400)
`bcrypt` 이용해서 암호화한 비밀번호를 대조하는 기능을 추가해주세요!

2021-01-06 03:45 UTC, hyeseong-dev commented on students/16th/team1/hyeseonglee/user/models.py
> +    password = models.CharField(max_length=20, verbose_name='비밀번호')
리뷰 주셔서 감사합니다. 
max_length=20 --> 255로(추후 해쉬값으로 저장되는 만큼) 넉넉히 잡아줄게요!

2021-01-06 03:46 UTC, hyeseong-dev commented on students/16th/team1/hyeseonglee/user/views.py
> +from user.models  import User
정리 되지 않은 `import`  키워드 정렬하도록 할게요. 
감사합니다!😀

2021-01-06 03:47 UTC, hyeseong-dev commented on students/16th/team1/hyeseonglee/user/views.py
> +                return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
중복된 코드 줄여서 리팩토링 하도록 할게요.
```python
           if not email and password: 
                return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
```
Thank you🤗

2021-01-06 03:49 UTC, hyeseong-dev commented on students/16th/team1/hyeseonglee/user/views.py
> +                return JsonResponse({'MESSAGE':'SUCCESS'}, status=201)
암호화 과정은 다른 동기분들 내용 및 구글링 통해서 구현에 힘쓰도록 할게요!
도전!🛩

2021-01-06 03:50 UTC, hyeseong-dev commented on students/16th/team1/hyeseonglee/user/views.py
> +            return JsonResponse({'MESSAGE': 'VALUE ERROR OCCURED!'},status=400)
`bycrpt`부분 바로 적용해보도록 할게요.
조언 너무나 감사합니다!!😆

2021-01-28 07:32 UTC, merged