mission1 : Django 초기 세팅
wecode-bootcamp-korea/westagram-backend pull request #173
Opened 2020-12-30 12:13 UTC by jeongmin14

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Django 초기세팅 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Mission 1 & 팀 프로젝트 초기 설정을 따라 초기 세팅완료
- 초기세팅 상세 내용 : django project / user app 생성, settings.py / urls.py 수정, my_settings.py 생성, .git ignore 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- manage.py가 있는 디렉토리에 .git ignore, my_settings.py를 생성했는데요 이 디렉토리에 있는 리스트를 보면 
 .git ignore이 안보이던데..원래 그런건가요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-30 13:56 UTC, ulfrid requested changes
전체적으로 잘하셨는데 초기 설정이란건 사실 모델 생성도 존재하면 안됩니다. 이미 해놓으셨기때문에 수정하려고 하진 마시고 염두해 두세요. 수정사항 확인 바랍니다.

2020-12-30 13:56 UTC, ulfrid commented on students/16th/team2/jmyoon/westagram/westagram/settings.py
> +SECRET_KEY = '_i@cj9$4x($$c!$bpvv8m%m9bmjv&#ea!xp58qipe1@x70j4lv'
사용하진 않을거지만 아래에 따로 선언하셨다면 이부분은 삭제해주세요.

2020-12-30 13:56 UTC, ulfrid commented on students/16th/team2/jmyoon/westagram/westagram/settings.py
> +import my_settings
이 부분은 파일의 윗부분에 존재하는게 컨벤션상 좋습니다.

2020-12-31 00:53 UTC, jeongmin14 commented
수정했습니다.

2020-12-31 02:10 UTC, ulfrid commented
LGTM 👍

2020-12-31 02:10 UTC, merged