[김건희] Mission 2: 회원가입 엔드포인트
wecode-bootcamp-korea/westagram-backend pull request #179
Opened 2020-12-31 13:23 UTC by konh2e

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- user model 작성 및 Sign-Up view 작성
		 
## 수정 사항들 자세한 내용
- user 모델 작성
- Sign-Up view 작성
- sign-up url 수정
- Email or mobile_number 가입 기능 구현
- 정규 표현식 이용 Email, mobile_number 판별
- 정규 표현식 이용 password 8자리 이상 판별
- 가입 성공시 200 반환
- 가입 실패시 400 반환

## 기타 질문 및 특이 사항
-  예외처리를 위해 Try Except를 많이 사용해도 상관이 없나요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-04 12:13 UTC, jeongmin14 requested changes

2021-01-04 12:14 UTC, jeongmin14 commented on students/16th/team2/konhee-kim/user/views.py
> +def validate_password(password):
asdf

2021-01-04 12:36 UTC, jeongmin14 commented on students/16th/team2/konhee-kim/user/views.py
> +def validate_email(email):
email, mobile, password 확인을 따로 함수로 정의하는 방법도 있군요! 많이 배워갑니다,,

2021-01-04 12:38 UTC, jeongmin14 requested changes
가독성이 좋아 코드보기 편했습니다!

2021-01-06 01:41 UTC, jamessoun93 requested changes
건희님 리뷰 남겨드렸으니 반영해주세요! 😉

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/models.py
> +    mobile_number = models.CharField(blank=True, max_length=11)
@jeongmin14 👍👍👍 CharField 에는 max_length 를 함께 지정해주셔야 합니다!

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/models.py
> +    password      = models.CharField(max_length=20)
- `blank=True` 는 빈 스트링이어도 된다는 뜻인데 의도하신 바인가요? 지금대로면 비밀번호를 제외한 모든 필드에 빈 스트링을 넣고도 정상적으로 회원가입을 할 수 있게 됩니다!
- password 는 암호화해서 저장해야하기 때문에 길이를 넉넉하게 잡아주세요~

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/views.py
> +from user.models  import User
깔끔합니다! 👍

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/views.py
> +    """
이렇게 validation 관련 로직을 함수로 분리해주신 것 너무 잘하셨네요! 하지만 이렇게 하단에 모아놓으시는 것보다 아예 이런 util 함수를 모아놓는 파일에 따로 모아놓고 필요한 곳에서 import 해서 사용해주시면 기능별로 분리가 확실해져서 수정할때 도움이 많이 됩니다!

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/views.py
> +        return JsonResponse({'MESSAGE': 'SUCCESS'}, status=200)
```python
email, mobile = check_email_or_mobile(data['email_or_mobile'])
username      = data['username']
```
당장 위 내용에서부터 발생할 수 있는 에러가 있기때문에 `try ... except ...` 를 활용한 에러처리를 추가해보세요! 안그러면 서버가 멈추게 됩니다~

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/views.py
> +            return JsonResponse({'MESSAGE': 'KEY_ERROR'}, status=400)
파이썬의 KeyError 에 대해서 조금 더 알아보시고 알아보신 내용을 바탕으로 에러처리와 함께 로직을 조금 변경해주실 수 있을 것 같네요.

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/views.py
> +            return JsonResponse({'MESSAGE': 'KEY_ERROR'}, status=400)
password 암호화 과정이 빠졌네요! 추가해주세요~

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/views.py
> +            return JsonResponse({'MESSAGE': 'EXISTENCE_ERROR'}, status=400)
`and` 와 `=` 을 기준으로 정렬해주시려는 시도는 너무 좋았지만 여기서는 오히려 가독성이 좋지 못합니다. 아래처럼 수정해주세요. 그리고 `exists()` 사용 너무 good 입니다 👍
```suggestion
        if email and User.objects.filter(email = email).exists():
            return JsonResponse({'MESSAGE': 'EXISTENCE_ERROR'}, status=400)
       
        if mobile and User.objects.filter(mobile_number = mobile).exists():
            return JsonResponse({'MESSAGE': 'EXISTENCE_ERROR'}, status=400)
        
        if username and User.objects.filter(username = username).exists():
            return JsonResponse({'MESSAGE': 'EXISTENCE_ERROR'}, status=400)
```

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/views.py
> +        a_user = User.objects.create(
변수명을 이렇게 지어주시는 습관은 없애주세요! 나중에 복잡한 로직을 담고 있는 view 같은경우 알아보기가 힘들 수 있습니다.

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/views.py
> +                return JsonResponse({'MESSAGE': 'INVALID_USER'}, status=400)
이렇게 블록별로 `try ... except ...` 를 해주시는것보다 처음부터 로직은 try 로 감싸주시고 발생할 수 있는 에러들을 하단에 모아주시는게 가독성에는 더 좋습니다.

2021-01-06 01:41 UTC, jamessoun93 commented on students/16th/team2/konhee-kim/user/views.py
> +                return JsonResponse({'MESSAGE': 'INVALID_USER'}, status=400)
이런식으로 똑같은 코드가 여러번 반복되는 경우 어떻게하면 줄일 수 있을지에 대한 고민을 꼭 해보셔야 합니다. 우선 미션을 이해하시는데 착오가 좀 있던 것 같아서, 로그인은 이메일과 패스워드를 받는다는 기준을 두고 로직을 변경해주세요!

2021-01-28 07:29 UTC, merged