[최수아] Mission 2 : 회원가입 엔드포인트
wecode-bootcamp-korea/westagram-backend pull request #181
Opened 2021-01-01 09:32 UTC by sue517

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일로 로그인 할 수 있으며 중복된 이메일의 경우 EXIST EMAIL 이라는 error message 가 반환되게 했음
- 비밀번호나 이메일 양식이 잘못 된 경우 (비밀번호가 8자리 미만이거나 이메일에 @와 . 이 포함되지 않은 경우를 의미함) NOT VALID PASSWORD/EMAIL 이라는 error message 가 반환됨
- 성공시 SUCCESS 라는 메시지가 반환됨

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-04 08:17 UTC, jamessoun93 requested changes

2021-01-04 08:17 UTC, jamessoun93 commented on students/16th/team2/suaChoi/user/models.py
> +    email      = models.CharField(max_length=800)
장고의 `EmailField` 를 활용해주시는 것도 좋을 것 같습니다!
```python
print("hello world")
```

2021-01-04 08:26 UTC, hamineee commented on students/16th/team2/suaChoi/user/views.py
> +             if len(password) <  8:
비밀번호 8자리 조건을 정규식에 넣는다면 코드를 더 줄일 수 있을 것 같아요!

2021-01-04 08:34 UTC, hamineee commented on students/16th/team2/suaChoi/user/views.py
> +
회원가입 시 email 없이 name 이나 phone 만으로도 할 수 있기때문에 exist name 과 exist phone 에 해당하는 코드도 필요한 것 같아요 !

2021-01-04 15:56 UTC, sue517 commented on students/16th/team2/suaChoi/user/models.py
> +    email      = models.CharField(max_length=800)
수정했습니다! 감사합니다

2021-01-04 15:56 UTC, sue517 commented on students/16th/team2/suaChoi/user/views.py
> +
해당 기능 추가했습니다! 감사합니다

2021-01-06 12:43 UTC, soheon-lee commented on students/16th/team2/suaChoi/posting/views.py
> +            content = data.get('content')
모두 data라는 딕셔너리에서 키를 이용하여 데이터를 가져오는 구문인데, `img` 변수만 다른 방법으로 가져오신 이유가 따로 있을까요?

2021-01-06 12:43 UTC, soheon-lee commented on students/16th/team2/suaChoi/posting/views.py
> +
`else`가 없어도 바로 위의 `if`문이 만족되지 않는다면 바로 도달할 수 있는 로직입니다. 꼭 필요한 경우가 아니면 `else`를 사용하지 않는 것이 보다 파이썬다운 코딩 스타일입니다. `else`는  지워주셔도 됩니다 :)

2021-01-06 12:43 UTC, soheon-lee commented on students/16th/team2/suaChoi/posting/views.py
> +#
깔끔한 코드를 위해 사용하지 않는 주석은 제거해주세요

2021-01-06 12:43 UTC, soheon-lee commented on students/16th/team2/suaChoi/posting/views.py
> +            })
goood!

2021-01-06 12:43 UTC, soheon-lee commented on students/16th/team2/suaChoi/user/views.py
> +
DATA_ERROR은 어떨 때에 발생하는 에러일까요?
KEY가 빠져서 나는 에러라면 KEY_ERROR가 보다 적합합니다 :)

2021-01-06 12:43 UTC, soheon-lee commented on students/16th/team2/suaChoi/user/views.py
> +
모든 에러를 다 캐치하는 것은 디버깅에 도움이 되지 않습니다 :) 에러가 나지 않는다면 제거해주시고, 지칭하고 싶은 에러가 있다면 정확하게 명시해주시는 것이 좋습니다

2021-01-06 13:12 UTC, sue517 commented on students/16th/team2/suaChoi/posting/views.py
> +            content = data.get('content')
당시에는 이메일/폰번호 둘 중 하나로만 로그인이 가능하게 설정해두었어서 get 을 사용하였는데 이메일만으로 로그인하게 바꾸어 수정 완료했습니다!
인스타에 글을 업로드할때는 이미지는 반드시 필요하되 별도의 내용이 없어도 이미지가 등록되는거 같아 이미지는 필수 키로 두고,  content 는 get 으로 가져오는 형식을 취했습니다 :)

2021-01-06 13:13 UTC, sue517 commented on students/16th/team2/suaChoi/user/views.py
> +
리뷰 주신 부분 수정하여 커밋했습니다 감사합니다 😊

2021-01-08 01:59 UTC, jamessoun93 requested changes

2021-01-08 01:59 UTC, jamessoun93 commented on students/16th/team2/suaChoi/posting/models.py
> +    image_url    = models.URLField(max_length=2000)
👍

2021-01-08 01:59 UTC, jamessoun93 commented on students/16th/team2/suaChoi/posting/views.py
> +            content   = data.get('content')
`NULL` 허용필드만 `get` good! 👍

2021-01-08 01:59 UTC, jamessoun93 commented on students/16th/team2/suaChoi/posting/views.py
> +            return JsonResponse({"message":"INVALID_USER"}, status=401)
user email 를 받아 post 를 생성하는 로직을 작성하셨는데, 유저정보는 데코레이터를 활용하여 jwt 로 부터 받아와야합니다! 그렇게 적용해보세요 :)

2021-01-28 07:29 UTC, merged