[윤정민] Mission 3: 로그인 엔드포인트
wecode-bootcamp-korea/westagram-backend pull request #183
Opened 2021-01-02 19:12 UTC by jeongmin14

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 or 핸드폰 번호 or 사용자 이름으로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 회원가입 구현한 브랜치에서  push를 했는데 상관없나요?
- SigninView에서 json.loads데이터들을 변수 지정했을 때 왜 keyerrorr가 뜨는걸까요,,?(user/view.py 56~59번째 줄, 에러뜨길래 일단 변수지정 안했습니다.) 
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-04 12:02 UTC, konh2e commented on students/16th/team2/jmyoon/westagram/user/views.py
> +                ).save()
`User.objects.create` 메소드를 사용해서 유저 정보를 DB에 저장하실때, `save` 메소드를 추가로 사용하신 의미가 궁금합니다

2021-01-04 12:04 UTC, konh2e commented on students/16th/team2/jmyoon/westagram/user/views.py
> +
현재 `SigninView` 구조상 이메일이나 휴대폰번호 등으로 로그인을 시도할시, 각 로그인유형에 맞는 http json 구조의 key 값이 다르게 지정되는데, 변수 지정을 하여 사용하고자 한다면, 해당 부분이 고려되면 좋을것 같습니다.

2021-01-04 12:07 UTC, konh2e commented on students/16th/team2/jmyoon/westagram/user/views.py
> +            elif ('@' not in email or '.' not in email):
22번 라인의 테스트로 이메일주소를 검사하고자 할 때, `@` 앞에` .` 있는 형식 (예를들어 `na.me@google` 과 같은 형태 또한 이메일 주소로 인식하게 되는것 같습니다.

2021-01-04 12:23 UTC, konh2e requested changes
SingUp, SignIn peer review single comment 달았습니다. 확인해 주세요

2021-01-07 02:21 UTC, jamessoun93 requested changes
너무너무 깔끔하네요 정민님!
리뷰 남겨드렸으니 반영하여 push 해주세요!

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +from my_settings   import SECRET_KEY
너무 깔끔하네요!! 👍

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +            if not data['email']:
이미 아래쪽에 KeyError 잡아주시는 익셉션이 있는데 여기서 중복처리를 해주실 필요가 없습니다. 파이썬에서 어떻게 하면 KeyError 가 발생하는지 알아보시고 수정해보세요 :)

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +            if not validate_email.match(data['email']):
Truthy, Falsy 값에 대한 이해도가 이미 있으시군요 👍👍👍

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +            if (User.objects.filter(email = data['email']).exists()):
- exists() 활용 너무 좋습니다!
- 소괄호는 불필요하니 없애주세요~
```suggestion
            if User.objects.filter(email = data['email']).exists():
```

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +                )
이미 위 조건문마다 return 문이 있어서 여기까지 왔다는 것은 위 조건들에 맞지 않았다는 듯으로 여기서 else 는 필요하지 않습니다.

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +                pw_encrypt = pw_encrypt.decode()
암호화 과정을 상세하게 스텝스텝 잘 적용해주셨네요 👍 하지만 조금 줄여서 더 깔끔하게 만들 수 있어보이네요!
```suggestion
                pw = data['password'].encode()
                hashed_password = bcrypt.hashpw(pw, bcrypt.gensalt()).decode()
```

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +            return JsonResponse({'MESSAGE' : 'KeyError'}, status = 400)
위에서 발생하는 모든 에러를 KeyError로 잡아주는 것은 부정확한 결과 전달하게 될 수도 있는 방법입니다. 이런식으로 except 로 모든 에러를 받는 방법은 비추드리고, 발생할 수 있는 에러를 명확하게 잡아주시는 방법을 추천드립니다.

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +            if 'email' in data.keys():
data.keys() 로 원하는 key 가 있는지 확인하시는 로직도 좋지만, 그냥 직접 꺼내서 변수에 넣어보는 방법도 있습니다. 그렇게 하게되면 불필요한 if 문은 사라지게 되고, 원하는 key 가 없을 시 KeyError 가 raise 되어 except 문에서 받아주실 수 있습니다. 
```python
email = data['email']
```

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +                    user=User.objects.get(email=data['email'])
```suggestion
                    user = User.objects.get(email=data['email'])
```

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +                    if bcrypt.checkpw(data['password'].encode(), user.password.encode()):
구분을 위해 위에 빈줄을 추가해주시면 도움이 되겠네요!

2021-01-07 02:21 UTC, jamessoun93 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +                        token = jwt.encode({'id' : user.id}, SECRET_KEY, algorithm='HS256')
너무 잘해주셨네요~ 토큰을 생성할때 사용한 알고리즘도 숨겨주시는게 좋으니 my_settings 에 추가해서 import 해오는 방법으로 변경해보시겠어요?

2021-01-08 01:54 UTC, jamessoun93 commented
@jeongmin14 리뷰 후에 새로 push 된 코드가 없네요 정민님!

2021-01-08 06:17 UTC, jeongmin14 commented on students/16th/team2/jmyoon/westagram/user/views.py
> +            if 'email' in data.keys():
@jamessoun93 코드 수정한 부분 확안부탁드립니다~

2021-01-28 07:28 UTC, merged