[16기 정지원] Mission 2 : 회원가입 엔드포인트
wecode-bootcamp-korea/westagram-backend pull request #185
Opened 2021-01-03 16:51 UTC by jungzi1

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현
- views models 작성 및 계정 10개 생성 test 완료
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항
validation 기능을 사용해 볼려고 하였으나 form import부터 validation.py 파일을 어느 경로에 생성하는것이 맞는지 등 모르는 내용이 너무 많아서 이번 미션에 구현해보지 못했습니다.
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-04 15:19 UTC, donqlee requested changes
항상 많이 도와주셔서 감사합니다 지원님. 고생하셨습니다.

2021-01-04 15:19 UTC, donqlee commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +                return JsonResponse({'MESSAGE':'existing ID'}, status=400)
먼저, signup_db = User.objects.all()로 따로 정의를 해주셔서 좀더 깔끔하게 정리 된거 같아 잘하신거 같습니다.
틀린거는 아니지만, 오류 메시지를 모두 대문자로 하시는것을 추천드립니다(통일성있게 하기위해...)

2021-01-04 15:19 UTC, donqlee commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +            if '@' and '.' not in data['email']:
제가 정확하지 않아 맞는지 정확히 모르겠지만 ㅠ 
if '@' and '.' not in data['email']: -> @와 . 모두 없을 경우로 생각되서
if '@' not in data['email'] or '.' not in data['email']: -> 둘중 하나 라도 없으면 오류 메시지 전달

근데 사실... 위에꺼도 되는지 정확히 몰라서 조심스럽긴 합니다... 한번 확인 해주시면 감사하겠습니다.

2021-01-04 16:33 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +                return JsonResponse({'MESSAGE':'existing ID'}, status=400)
아넵넵 정신없이 만드느라 그랬는지 통일성 고려를 못했네요ㅜㅜ 감사합니다 동규님!!!!! 완전 공감합니다

2021-01-04 16:33 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +            if '@' and '.' not in data['email']:
아..... 동규님 말씀이 맞으세여.... 하 이걸 왜 이렇게 했지... 역시 동규님 꼼꼼하세요..... 바로 수정하겠습니다!

2021-01-05 15:18 UTC, jungzi1 commented
미션 4, post된 게시물 저장까지 구현, get 수정중, 존재하지 않는 id나 id와 url필드를 미입력시 반환하는 오류 메세지 구현 중

2021-01-06 19:20 UTC, hyeseong-dev commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +            if '@' and '.' not in data['email']:
동규님 조언에 저도 보다가 갑자기 코드를 더 단축할수 있지 않을까?! 라는 생각에

아래 부분을
```python
if '@' not in data['email'] or '.' not in data['email']:
```

이렇게도 된다는걸 깨달았어요?!
```python
if '@'  or '.' not in data['email']
````

콘솔에서 1. 골뱅이랑 점 없는 경우 2. 둘중하나만 없는 경우 해보니깐. 작동되는 로직인건 확인했어요.
```bash
>>> a='hyeseong43gmailcom'
>>> if '.' or '@' not in a:
...      print('업어요')
...
업어요
>>> a2='hyeseong43@gmailcom'
>>> if '.' or '@' not in a:
...      print('업어요')
...
업어요
>>> a3='hyeseong43.gmailcom'
>>> if '.' or '@' not in a:
...      print('업어요')
...
업어요
```


```

2021-01-07 02:50 UTC, jamessoun93 requested changes
리뷰 남겨드렸습니다! 반영하여 push 해주세요!

2021-01-07 02:50 UTC, jamessoun93 commented on students/16th/team2/jungjiwon/westagram/user/models.py
> +from django.conf    import settings
settings 는 불필요합니다~

2021-01-07 02:50 UTC, jamessoun93 commented on students/16th/team2/jungjiwon/westagram/user/models.py
> +    tel_num      = models.CharField(max_length = 20)
데이터베이스 컬럼명은 이런식으로 줄여주시는것보다 길더라도 명확하게 정해주시는게 좋습니다!
phone_number <- 이런식으로요!

2021-01-07 02:50 UTC, jamessoun93 commented on students/16th/team2/jungjiwon/westagram/user/models.py
> +    email        = models.EmailField(max_length = 30)
EmailField good!

2021-01-07 02:50 UTC, jamessoun93 commented on students/16th/team2/jungjiwon/westagram/user/models.py
> +    updated_time = models.DateTimeField(auto_now = True)
👍👍👍

2021-01-07 02:50 UTC, jamessoun93 commented on students/16th/team2/jungjiwon/westagram/user/urls.py
> +    path('/login'   , LogInView.as_view())
```suggestion
from django.urls import path
from user.views  import UsersView, LogInView

urlpatterns=[
    path('/create', UsersView.as_view()),
    path('/login', LogInView.as_view())
```

2021-01-07 02:50 UTC, jamessoun93 commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +class UsersView(View):
저는 밑에 LogInView 라는 클래스가 있어서 이 view 클래스가 회원가입 view 라는걸 알았지만, 이런식으로 유추해내야 하게끔 클래스명을 지어주시는것은 좋은 practice 가 아닙니다.

2021-01-07 02:50 UTC, jamessoun93 commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
- User 인스턴스를 먼저 생성하신 뒤 여러가지 조건을 확인하는 것 보다 모든 조건을 충족할 시 create 를 해주는 방법이 더 자연스러운 흐름이라고 생각합니다. 그렇게 수정해보세요!
- 그리고 지금 작성하신 코드 상으로는 try 문에 들어가기 전부터 에러가 발생할 수 있습니다. 파이썬의 KeyError 가 언제 raise 되는지 공부해보시고 try 문으로 어디까지 감싸줘야할지 고민해보세요!
- exists() 활용 good 입니다!
- 그리고 비밀번호 암호화 과정이 빠져있으니 추가해주세요 :)

2021-01-07 02:50 UTC, jamessoun93 commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +            return JsonResponse({'MESSAGE':'INVALID LOGIN ID'}, status=400)
지금 구현하신 로직이 많이 복잡하고 빠진 부분들이 있어서 제가 정리해드린 순서대로 로직을 수정해보시겠어요?
1. email을 대조하여 user 가 객체를 가져온다
2. 해당 user 객체의 password 와 request로 부터 받는 password 를 대조하여 일치하는지 확인한다.
3. 모든게 정상이라면 access_token 을 생성하여 JsonResponse 로 리턴한다.

2021-01-07 18:04 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +            if '@' and '.' not in data['email']:
오홋 수정 했습니다!

2021-01-07 18:04 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/models.py
> +from django.conf    import settings
수정했습니다!

2021-01-07 18:04 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/models.py
> +    tel_num      = models.CharField(max_length = 20)
넵넵 좀더 직관적인 컬럼명으로 바꿨습니다 승현님!

2021-01-07 18:05 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/models.py
> +    email        = models.EmailField(max_length = 30)
thank you!!

2021-01-07 18:05 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/models.py
> +    updated_time = models.DateTimeField(auto_now = True)
🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

2021-01-07 18:05 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/urls.py
> +    path('/login'   , LogInView.as_view())
수정했습니다!

2021-01-07 18:06 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +class UsersView(View):
넵 승현님 SignupView로 수정하여 좀더 직관적으로 바꿧습니다! 앞으로 유의하겠습니다

2021-01-07 18:06 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
승현님 조언하신 수정사항 수정 했습니다!

2021-01-07 18:07 UTC, jungzi1 commented on students/16th/team2/jungjiwon/westagram/user/views.py
> +            return JsonResponse({'MESSAGE':'INVALID LOGIN ID'}, status=400)
password 대조와 JsonResponse으로 토큰 응답 구현 완료했습니다!

2021-01-28 07:28 UTC, merged