[조하민]Mission 2,3 : 회원가입 엔드포인트, 로그인 엔드포인트
wecode-bootcamp-korea/westagram-backend pull request #186
Opened 2021-01-04 07:55 UTC by hamineee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Mission 1까진 통과된 상태이구요, 그 후브랜치들을 여러개 생성하는 바람에 작업이 꼬여서 새브랜치로 다시 PR 합니다.
- 회원가입 엔드포인트
- 로그인 엔드포인트
- 게시물 등록도 들어가있는데  이건 수정중에 있습니다 무시해주세요!
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
[Mission 2]
- email, phone, name 중 1개이상 입력 확인
- password 입력 확인
- email 입력시, 조건확인과 기존회원 유무확인
- phone /name 입력시 기존회원 유무확인
- 실패시 에러 반환
- 성공시 200 OK 반환
[Mission 3]
- email, phone, name 중 1개이상 입력 확인
- password 입력확인
- name/email/phone 입력 시 각각 회원 유무 확인 후 password 매칭 확인
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- email/ phone/ name validation 에서 반복되는 구문이 많은데 여기서 더 줄일 수 있는 방법이 없는지 궁금합니다.
-  
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-04 08:47 UTC, sue517 commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +        if email is None and phone is None and name is None:
해당 부분을 `if not email and phone and name` 으로 쓰면 중복되는 None 을 줄일 수 있을거 같아요!

2021-01-04 08:50 UTC, sue517 commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +        if not email and not phone and not name:
`if not email and phone and name` 이라고 쓰시면 중복되는 not 을 줄일 수 있을거 같아요!
수정하신지 모르고 이전의 commit 에다가 리뷰 남겼다가 지우고 다시 남깁니다 😅

2021-01-04 14:06 UTC, sue517 commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +        if not email and not phone and not name:
해당 리뷰가 잘못된거 같아서 개인적으로 DM 드리고 번복했습니다아 😭

2021-01-05 16:26 UTC, sue517 commented on students/16th/team2/hamin-jo/westagram/post/views.py
> +                "image" : post.image,
이 부분 align 해주시면 더 깔끔한 느낌이 들어서 좋을거 같아요!

2021-01-06 13:26 UTC, hamineee commented on students/16th/team2/hamin-jo/westagram/post/views.py
> +                "image" : post.image,
헉 맞아요 감사해요!

2021-01-07 03:45 UTC, jamessoun93 requested changes
하민님~ 코드 너무 깔끔하네요!
리뷰내용 반영하여 수정해주세요!

2021-01-07 03:45 UTC, jamessoun93 commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +                return JsonResponse({'MESSAGE': 'KEY_ERRORS; password'}, status=400)
- 이미 위에서 email 과 password 를 추출하여 변수로 선언하셨는데 여기서 if 문으로 재확인하실 필요가 없습니다.
- 수정해주시면 불필요한 if, else 가 사라지겠죠!?
- if 조건을 소괄호로 감싸주실 필요가 없습니다!
- exists 활용 굳!!! 👍

2021-01-07 03:45 UTC, jamessoun93 commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +            User.objects.create(name= name, password= decoded_pw, email= email, phone= phone)
kwargs 부분 `=` 앞뒤로 공백 양쪽 다 추가해주시거나 둘다 없애거나 통일해주세요!
```suggestion
            User.objects.create(name = name, password = decoded_pw, email = email, phone = phone)
```

2021-01-07 03:45 UTC, jamessoun93 commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +class UserView(View):
아래 로그인뷰가 있어서 이 view 클래스가 회원가입 view 라는 것을 유추해낼 수 있었지만 더욱 더 명확한 class 명으로 지어주신다면 그런 수고스러움이 사라지겠죠?!

2021-01-07 03:45 UTC, jamessoun93 commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +            if 'email' in data.keys():
여기서도 email 존재 여부를 재확인해주실 필요가 없습니다!

2021-01-07 03:45 UTC, jamessoun93 commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +            return JsonResponse({'MESSAGE': 'KEY_ERRORS'}, status=400)
지금 로직을 보시면 이메일이 일치하는 유저 객체가 존재한다면 그때부터 비밀번호를 체크하고 jwt 를 generate 하는 과정이 있지만, 사실 LoginView 자체가 해야하는일이 해당 내용이므로, 조건은 오히려 반대로 일치하는 유저가 없거나, 비밀번호가 일치하지 않을 때 어떻게 처리를 해줄것이냐에 대한 내용을 걸어주시는게 더 적합한 flow 라고 생각합니다.

2021-01-07 11:44 UTC, hamineee commented on students/16th/team2/hamin-jo/westagram/core/util.py
> +from account.models import User
헉 네 !

2021-01-07 11:45 UTC, hamineee commented on students/16th/team2/hamin-jo/westagram/user/models.py
> +    password = models.CharField(max_length=200, null=False)
헉 네네

2021-01-07 11:45 UTC, hamineee commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +            decoded_pw     = hashed_pw.decode('utf-8')
아 네!!

2021-01-07 11:46 UTC, hamineee commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +            password_regex = '[A-Za-z0-9@#$]{8,12}'
오오 네!

2021-01-07 11:46 UTC, hamineee commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +                return JsonResponse({'MESSAGE': 'KEY_ERRORS; password'}, status=400)
아 정말 그렇네요!  네네 !

2021-01-07 11:47 UTC, hamineee commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +class UserView(View):
맞아요 !

2021-01-07 11:47 UTC, hamineee commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +            if 'email' in data.keys():
맞습니다 😢

2021-01-07 13:26 UTC, hamineee commented on students/16th/team2/hamin-jo/westagram/user/views.py
> +            return JsonResponse({'MESSAGE': 'KEY_ERRORS'}, status=400)
\

> 하민님~ 코드 너무 깔끔하네요!
> 리뷰내용 반영하여 수정해주세요!

넵 수정했습니다 리뷰감사합니다 !!

2021-01-28 07:18 UTC, merged