[안재이] Mission 1: 초기세팅 진행중
wecode-bootcamp-korea/westagram-backend pull request #193
Opened 2021-01-28 07:00 UTC by jaeyiahn

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 초기세팅 진행중
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- django 프로젝트 폴더만 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-29 02:12 UTC, ulfrid commented
잘 하셨네요 재이님! 다음 미션 진행해주세요~👍

2021-02-01 15:31 UTC, ulfrid requested changes
수정 부탁드립니다~!

2021-02-01 15:31 UTC, ulfrid commented on students/17th/team3/jaeyiahn/user/models.py
> +    email      = models.EmailField(max_length=100)
```suggestion
    username   = models.CharField(max_length=45, null=True)
    phone      = models.CharField(max_length=45, null=True)
    email      = models.EmailField(max_length=100)
```
요 세개의 필드는 유일성이 필요하지 않을까요? unique 옵션을 적용하시면 좋을것 같습니다.

2021-02-01 15:31 UTC, ulfrid commented on students/17th/team3/jaeyiahn/user/views.py
> +                return JsonResponse({'message': '중복된 email'}, status=400)
```suggestion
                return JsonResponse({'message': 'EMAIL_EXISTS'}, status=400)
```
우리가 리스판스시 응답메세지를 주는부분은 사실 status_code 만으로도 충분합니다. 
하지만 보다 원할한 소통을 하고자 함으로서 메세지도 응답코드화해서 사용하는데, 이는 코드화된 문자열이어야 합니다. 
따라서 위에 작성하신것과 다르게 단순한 코드형태로 작성해서 프론트엔드와 소통하는 것이 좋습니다. 
결국 모든것은 규격화해서 전달하는게 좋습니다. 
아래의 다른 리턴도 변경 부탁드립니다.

2021-02-01 15:31 UTC, ulfrid commented on students/17th/team3/jaeyiahn/user/views.py
> +            if len(password) < 8:
```suggestion
            if len(password) < MINIMUM_PASSWORD_LENGTH:
```
위와 같이 8이라는 값은 하드코딩하기보다, 상수로 작성해서 관리하는게 좋습니다. 
향후 기준이 달라질 경우 상수 값만 변경하면 되기 떄문입니다.
상수의 선언은 코드 상단 import 아래에 선언해주세요.

2021-02-02 01:42 UTC, jaeyiahn commented on students/17th/team3/jaeyiahn/user/models.py
> +    email      = models.EmailField(max_length=100)
넵 적용하겠습니다

2021-02-02 01:49 UTC, jaeyiahn commented on students/17th/team3/jaeyiahn/user/views.py
> +                return JsonResponse({'message': '중복된 email'}, status=400)
네 수정하겠습니다~

2021-02-02 01:49 UTC, jaeyiahn commented on students/17th/team3/jaeyiahn/user/views.py
> +            if len(password) < 8:
네 반영하여 적용하도록 하겠습니다

2021-02-02 02:19 UTC, ulfrid commented
미션2도 가볍게 통과하시는군요 재이님~! 다음미션 진행 부탁드립니다~!

2021-02-03 08:59 UTC, ulfrid commented
잘 하셨네요. 이슈탭에 있는 미션 다시 확인 하셔서 블로깅 과제도 제출 부탁드립니다~!

2021-02-04 14:50 UTC, jaeyiahn commented
블로깅 과제 [여기](https://velog.io/@jaeyiahn/TIL-11-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%97%94%EB%93%9C%ED%8F%AC%EC%9D%B8%ED%8A%B8-%EC%97%90%EB%9F%AC-%EC%A0%95%EB%A6%AC)에 작성했습니다!

2021-02-07 06:27 UTC, ulfrid commented
확인 했습니다 통과입니다~! 설 연휴 잘보내세요 재이님~🥳

2021-03-04 01:01 UTC, merged