[송빈호] Mission 1:초기셋팅 진행중
wecode-bootcamp-korea/westagram-backend pull request #194
Opened 2021-01-28 07:00 UTC by binogood

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 초기 셋팅 진행중 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- django 프로젝트 폴더만 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-29 02:08 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-01-29 02:08 UTC, ulfrid commented on students/17th/team3/binhosong/westargram/settings.py
> +SECRET_KEY = 'w77p6^j5$%37jb$i%77lf%=tx&-hk_o@7&7g(li$o4^@z$#&+6'
SECRET_KEY는 보안에 영향이 있는 요소이므로, 프로젝트 상위에 manage.py와 같은 위치에 my_settings.py라는 파일을 작성하고, 그안에 선언한뒤  임포트해서 적용 부탁드립니다.

2021-01-29 02:08 UTC, ulfrid commented on students/17th/team3/binhosong/westargram/settings.py
>  }
데이터베이스 접속  정보도 중요하므로 my_settings.py에 기록후 임포트해서 적용해주세요.

2021-01-29 03:04 UTC, binogood commented on students/17th/team3/binhosong/westargram/settings.py
> +SECRET_KEY = 'w77p6^j5$%37jb$i%77lf%=tx&-hk_o@7&7g(li$o4^@z$#&+6'
넵 수정하도록 하겠습니다!

2021-01-29 03:04 UTC, binogood commented on students/17th/team3/binhosong/westargram/settings.py
>  }
넵 수정하도록 하겠습니다!

2021-01-29 12:06 UTC, ulfrid commented
미션 1 통과입니다. 다음 과정 진행 부탁드립니다!

2021-02-01 08:36 UTC, ulfrid commented
아직 코드가 완성된 상황이 아닌것 같은데 수정 부탁드립니다.

2021-02-02 02:03 UTC, ulfrid requested changes
깃 관리를 잘하셔야 할 것 같습니다. 본인 프로젝트외에 제가 작성한 샘플 프로젝트도 포함되어 있고, 필요 없는 파일이 많이 포함되어 있는데 이부분 확인해서 삭제 하셨으면 좋겠습니다. 
수정사항 확인 바랍니다~😀

2021-02-02 02:03 UTC, ulfrid commented on students/17th/team3/binhosong/users/views.py
> +                if Account.objects.filter(password=password):
로직대로면 무슨 값이든 대상이 존재하면 다시 비밀번호가 존재 하면 로그인 하겠다인데. 이런방식의 로그인은 평범한 상황은 아니겠죠.
패스워드가 평문이라 해서 패스워드를 찾아야 하는건 아닙니다. 어떤 이메일을 가진 유저를 찾아서 그 유저가 가진 패스워드와 입력받은 패스워드를 비교해야 겠죠? 다시한번 로직 작성 부탁드립니다~!

2021-02-02 03:03 UTC, binogood commented on students/17th/team3/binhosong/users/views.py
> +class SignUp(View):
수정하도록 하겠습니다~

2021-02-02 04:14 UTC, binogood commented on students/17th/team3/binhosong/users/views.py
> +            )
수정하도록 하겠습니다~

2021-02-02 04:14 UTC, binogood commented on students/17th/team3/binhosong/users/views.py
> +                if Account.objects.filter(password=password):
수정하도록 하겠습니다 ~

2021-02-02 07:21 UTC, ulfrid requested changes
확인 부탁드립니다. 수정 하시고, 블로그 제출하시면 통과입니다.

2021-02-02 07:21 UTC, ulfrid commented on students/17th/team3/binhosong/users/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=401)
```suggestion      
                return JsonResponse({"message": "INVALID_PASSWORD"}, status=401)
          
            return JsonResponse({"message": "INVALID_USER"}, status=401)
```
줄일 수 있는 else:는 제거하고 인덴트로 해결하는게 좋습니다. 코드라인수를 줄일 수 있는 방법이기도 합니다.

2021-02-04 11:15 UTC, binogood commented on students/17th/team3/binhosong/users/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=401)
불필요한 else 제거하고 블로그 작성하였습니다 .
https://velog.io/@binogood68/Django-Backend-Westargram-%EA%B8%B0%EC%B4%88-%EC%84%A4%EC%A0%95
https://velog.io/@binogood68/Django-Backend-Westargram-2%EC%9E%A5-Mysql%EC%84%A4%EC%A0%95-%EB%B0%8F-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-%EA%B5%AC%ED%98%84
https://velog.io/@binogood68/Django-Backend-Westargram-3%EC%9E%A5%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B5%AC%ED%98%84

2021-02-04 11:50 UTC, ulfrid commented
통과입니다~!!!! 다음 미션 진행해주세요~!

2021-03-04 01:01 UTC, merged