[최호진] Mission 1: 초기세팅 진행중
wecode-bootcamp-korea/westagram-backend pull request #195
Opened 2021-01-28 07:00 UTC by jenehojinchoi

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 초기세팅 진행중 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- django 프로젝트 폴더만 생성 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-28 10:04 UTC, ulfrid requested changes
이슈에 있는 미션1에서 해야할 일들을 적용 해주시면 다시 리뷰 하겠습니다~😀

2021-01-28 10:04 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/westagram/settings.py
> +SECRET_KEY = 'd!wbz2g+%j(92g)xbte&fqpowckq6=++a%%6#5!s#v6f@v56+v'
SECRET_KEY 는 보안상 공개 저장소에 노출 되어선 안되는 코드입니다. 
my_settings.py 같은 외부 파일에 기록후 임포트해서 적용해주세요.

2021-01-28 10:04 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/westagram/settings.py
> +}
SECRET키와 마찬가지로 DATABASE도 MySQL로 변경하시고 접속정보는 my_settings.py로 기록후 임포트 해서 적용 부탁드립니다.

2021-01-29 14:47 UTC, jenehojinchoi commented on students/17th/team3/hojinjenechoi/westagram/settings.py
> +SECRET_KEY = 'd!wbz2g+%j(92g)xbte&fqpowckq6=++a%%6#5!s#v6f@v56+v'
앗 넵 바로 바꾸겠습니다...! 감사합니다!

2021-01-29 14:48 UTC, jenehojinchoi commented on students/17th/team3/hojinjenechoi/westagram/settings.py
> +}
앗 넵 이것 또한 바꾸겠습니다....

2021-02-01 01:41 UTC, ulfrid commented
호진님 통과입니다. mission2 진행해주세요. 작업이 완료 됐을때는 라벨을 정확히 변경해주셔야 리뷰를 합니다 ㅎㅎ. 다음부턴 주의해주세요.

2021-02-01 10:39 UTC, ulfrid requested changes
확인 바랍니다~!

2021-02-01 10:39 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/user/models.py
> +    phone           = models.CharField(null=True, max_length=11, validators=[RegexValidator(r'^\d{3}-\d{3}-\d{4}$')])
오 이건 안알려 드린건데 잘하셨습니다 👍

2021-02-01 10:39 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/westagram/urls.py
> +"""
주석은 필요 없으니 제거해주세요~!

2021-02-01 10:39 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/westagram/urls.py
> +    path('user/', include('user.urls'))
이런식으로 user/ 를 주게되면 만약~ 뒤에 오는 경로가 ' ' 일 경우 user를 가르키는게 아니는 user/??? 를 의미하게 되므로 중간 경로는 / 룰 주지 않는게 좋습니다. user의 urls에서 앞에  /를 주는게 좋습니다.

2021-02-01 10:39 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/user/views.py
> +
```suggestion
    def post(self, request):
        signup_data = json.loads(request.body)
```
의미없는 빈줄은 주지 않도록 해주세요

2021-02-01 10:39 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/user/views.py
> +              return JsonResponse({'message':'EMAIL INVALIDATION.'}, status=400)
```suggestion
              return JsonResponse({'message':'INVALID_EMAIL'}, status=400)
```
이런식으로 코드화 해주세요~!

2021-02-01 10:39 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/user/views.py
> +                return JsonResponse({'message':'USER ALREADY EXISTS.'}, status=409)
```suggestion
                return JsonResponse({'message':'USER_ALREADY_EXISTS'}, status=409)
```

2021-02-01 10:39 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/user/views.py
> +                return JsonResponse({'message':'NICKNAME ALREADY EXISTS.'}, status=409)
```suggestion
                return JsonResponse({'message':'NICKNAME_ALREADY_EXISTS'}, status=409)
```

2021-02-01 10:39 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/user/views.py
> +                return JsonResponse({'message':'PASSWORD SHOULD BE LONGER THAN 8 LETTERS.'}, status=400)
```suggestion
                return JsonResponse({'message':'SHORT_PASSWORD'}, status=400)
```

2021-02-01 10:39 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/user/views.py
> +
빈칸 지워주세요~!

2021-02-01 10:45 UTC, jenehojinchoi commented on students/17th/team3/hojinjenechoi/westagram/urls.py
> +"""
넵! 수정하겠습니다!

2021-02-01 10:46 UTC, jenehojinchoi commented on students/17th/team3/hojinjenechoi/westagram/urls.py
> +    path('user/', include('user.urls'))
넵! 이것 또한 수정하겠습니다!

2021-02-01 10:47 UTC, jenehojinchoi commented on students/17th/team3/hojinjenechoi/user/views.py
> +
넵!

2021-02-01 10:47 UTC, jenehojinchoi commented on students/17th/team3/hojinjenechoi/user/views.py
> +              return JsonResponse({'message':'EMAIL INVALIDATION.'}, status=400)
넵! 알겠습니다!

2021-02-01 11:10 UTC, ulfrid requested changes
마지막 수정입니다~😀

2021-02-01 11:10 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/user/views.py
> +            if len(signup_data['password']) < 8:
```suggestion
            if len(signup_data['password']) < MINIMUM_PASSWORD_LENGTH:
```
8 이라는 비교값 또한 하드코딩이므로~! 상수화 해서 관리 해주세요.

2021-02-01 11:10 UTC, ulfrid commented on students/17th/team3/hojinjenechoi/user/views.py
> +
```suggestion
MINIMUM_PASSWORD_LENGTH = 8
```
상수값은 클래스 밖이나 , 함수 바깥에 위치 시켜주세요. 재사용 범위에 따라 결정하시면 됩니다.

2021-02-01 11:22 UTC, jenehojinchoi commented on students/17th/team3/hojinjenechoi/user/views.py
> +
넵 마지막으로 수정하겠습니다! 감사합니다!!

2021-02-01 12:33 UTC, ulfrid commented
아까 말씀드린 줄바꿈 수정하시고~! 미션 3 진행해주세요~! 통과입니다👍

2021-02-02 02:47 UTC, ulfrid commented
통과입니다~!😃 다음 미션 진행해주세요~!!

2021-02-02 15:33 UTC, jenehojinchoi commented
지훈님! 이것저것 실험해보고 에러 모음 남겼습니다! 항상 피드백 주셔서 너무너무 감사합니다!!!  [(https://velog.io/@hojin11choi/TIL-Westagram-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-error-test-views.py)]

2021-02-02 16:03 UTC, jenehojinchoi commented
지훈님 제가 뭔가 대형사고를 친거 같아요 괜찮을까요 대체 어떻게 원 상태로 돌아가죠..? 커밋을 undo 할수 없나요...? 커밋 메세지 고치는 법 찾아보다가 뭔가 시도했는데 이상한걸 해버린거 같아요.................................................

2021-02-03 03:00 UTC, ulfrid commented
블로그 잘 봤습니다~ 호진님!

2021-03-04 01:02 UTC, merged