[이지윤] Mission 1: 초기세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #196
Opened 2021-01-28 09:12 UTC by yoon1ee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 초기세팅 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- django 프로젝트 생성 후 settings.py, views.py, urls.py  수정 완료.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-28 09:59 UTC, ulfrid requested changes
수정사항 확인 후 적용 부탁 드립니다~😀

2021-01-28 09:59 UTC, ulfrid commented on students/17th/team1/jiyoonlee/westagram/settings.py
> +SECRET_KEY = '-&*ckfdq252y#ao*zzk!))2_gy_%%sm#@rzlukut&l*7n9ok41'
씨크릿키는 보안에 중요한 사항이므로, my_settings.py 같은 파일에 별도로 저장 후 임포트 처리해야합니다.

2021-01-28 09:59 UTC, ulfrid commented on students/17th/team1/jiyoonlee/westagram/settings.py
> +}
마찬가지로 Database도  MySQL로 연결해야하고 그정보 또한 my_settings.py에 기록후 임포트해서 적용 부탁드립니다.

2021-01-28 09:59 UTC, ulfrid commented on students/17th/team1/jiyoonlee/westagram/urls.py
> +"""
주석 제거해주세요.

2021-01-28 09:59 UTC, ulfrid commented on students/17th/team1/jiyoonlee/westagram/urls.py
> +# from django.contrib import admin
사용하지 않을 거라면 주석처리가 아니라 제거해주세요.

2021-01-28 09:59 UTC, ulfrid commented on students/17th/team1/jiyoonlee/westagram/urls.py
> +  #  path('admin/', admin.site.urls),
마찬가지 입니다.

2021-01-29 02:55 UTC, yoon1ee commented
> 수정사항 확인 후 적용 부탁 드립니다~😀

2021-01-29 02:56 UTC, yoon1ee commented
수정 완료했습니다!

2021-01-29 03:36 UTC, yoon1ee commented on students/17th/team1/jiyoonlee/westagram/settings.py
> +SECRET_KEY = '-&*ckfdq252y#ao*zzk!))2_gy_%%sm#@rzlukut&l*7n9ok41'
수정했습니다!

2021-01-29 03:36 UTC, yoon1ee commented on students/17th/team1/jiyoonlee/westagram/settings.py
> +}
수정했습니다!

2021-01-29 03:36 UTC, yoon1ee commented on students/17th/team1/jiyoonlee/westagram/urls.py
> +"""
수정했습니다!

2021-01-29 03:36 UTC, yoon1ee commented on students/17th/team1/jiyoonlee/westagram/urls.py
> +# from django.contrib import admin
수정했습니다!

2021-01-29 03:36 UTC, yoon1ee commented on students/17th/team1/jiyoonlee/westagram/urls.py
> +  #  path('admin/', admin.site.urls),
수정했습니다!

2021-01-29 12:04 UTC, ulfrid commented
통과입니다. 다음 미션 진행 부탁드립니다. 지윤님!

2021-02-01 14:48 UTC, ulfrid requested changes
수정사항 확인 바랍니다~!

2021-02-01 14:48 UTC, ulfrid commented on students/17th/team1/jiyoonlee/user/models.py
> +    password = models.CharField(max_length=100, validators=[password_validator], null=True)
```suggestion
    password = models.CharField(max_length=100, validators=[password_validator], null=True)
```
좋은 아이디어네요~👍

2021-02-01 14:48 UTC, ulfrid commented on students/17th/team1/jiyoonlee/user/views.py
> +                    {'message': '휴대폰 번호나 이메일을 입력하세요.'},
```suggestion
                    {'message': 'INVAILD_INPUT'}, 
```
친절한 응답이지만 우리의 메세지는 고객에게 바로 전달하는것이 아닌 프론트 클라이언트에게 전달합니다. 사실은 status code만으로도 응답은 충분합니다. 하지만, 정확한 상황 판단을 위해 약속된 메세지 코드를 주고 받음으로서 상황에 대해 더 명확히 판단할 수 있으므로, 메세지를 주는것 입니다. 그러므로 이러한 문자열은 단순히 메세지가 아니라 문자로 된 상태 코드여야 합니다. 따라서 'INVALID_INPUT' 과 같은 상태코드문자열을 주는게 맞습니다.

2021-02-01 14:48 UTC, ulfrid commented on students/17th/team1/jiyoonlee/user/views.py
> +                    {'message': '휴대폰 번호나 이메일을 입력하세요.'},
아래의 다른 리턴에 적힌 메세지도 변경해주세요.

2021-02-01 14:48 UTC, ulfrid commented on students/17th/team1/jiyoonlee/user/views.py
> +            if len(password) < 8:
```suggestion
            if len(password) < MINIMUN_PASSWORD_LENGTH:
```
8과 같은 비교값은 하드코딩하지 말고, 상수화 시켜서 사용하는게 좋습니다.
상수선언은 코드상단 임포트 아래 혹은 함수의 바깥에 선언해주세요.

2021-02-02 03:37 UTC, yoon1ee commented on students/17th/team1/jiyoonlee/user/models.py
> +    password = models.CharField(max_length=100, validators=[password_validator], null=True)
아 근데.. 작동은 안돼요...

2021-02-02 03:37 UTC, yoon1ee commented on students/17th/team1/jiyoonlee/user/views.py
> +                    {'message': '휴대폰 번호나 이메일을 입력하세요.'},
수정했습니다

2021-02-02 03:37 UTC, yoon1ee commented on students/17th/team1/jiyoonlee/user/views.py
> +            if len(password) < 8:
수정했습니다

2021-02-02 05:21 UTC, ulfrid requested changes
마지막 수정 같습니다~! 부탁드립니다~!

2021-02-02 05:21 UTC, ulfrid commented on students/17th/team1/jiyoonlee/user/views.py
> +                username= data['username']
이미 위에 변수로 담아뒀는데 그걸 사용하지 않고 또 키호출 하는건 변수 재사용성을 포기하는거니까 좀 아깝습니다. 상단의 각 변수를 대입해주세요. 위의 필터메소드들도 그렇게 해야 유 의미 하겠네요~😀

2021-02-02 05:51 UTC, yoon1ee commented on students/17th/team1/jiyoonlee/user/views.py
> +                username= data['username']
수정했습니다!

2021-02-02 06:26 UTC, ulfrid commented
통과 드립니다~! 다음 미션 진행해주세요~!

2021-02-02 14:48 UTC, ulfrid requested changes
확인 바랍니다~!

2021-02-02 14:48 UTC, ulfrid commented on students/17th/team1/jiyoonlee/user/views.py
> +                            return JsonResponse({'message': 'KEY_ERROR'}, status=400)
다루는 데이터 외에 같은 방식이 3번이나 반복된다면, 뭔가 줄일수 있다는 이야기가 됩니다. 
어떻게 줄일 수 있을까요? 문제는 필터링을 한번에 하지 못하기 때문인데, 이를 해결해줄 마법같은 객체가 장고에 존재합니다. 
장고 Q객체를 찾아보세요~! 

https://docs.djangoproject.com/en/3.1/ref/models/querysets/#or

2021-02-03 02:44 UTC, yoon1ee commented on students/17th/team1/jiyoonlee/user/views.py
> +                            return JsonResponse({'message': 'KEY_ERROR'}, status=400)
수정했습니다!~

2021-02-03 08:57 UTC, ulfrid commented
잘 하셨습니다 .블로깅 과제 제출 부탁드립니다~! 상세내용은 ISSUE탭 미션 3 참고해주세요.

2021-02-05 04:38 UTC, yoon1ee commented
블로그 작성했습니다~ : https://velog.io/@yoon1ee/django-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-%EB%A1%9C%EA%B7%B8%EC%9D%B8

2021-02-07 06:28 UTC, ulfrid commented
확인했습니다. 통과입니다~! 리뷰가 늦어져서 죄송합니다. 설 연휴 잘보내세요!! 지윤님👍

2021-03-04 01:02 UTC, merged