[강승연] Mission 1: 초기 세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #197
Opened 2021-01-28 09:46 UTC by phin09

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장고 프로젝트를 생성하고 초기 세팅 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- INSTALLED_APPS에 corsheaders와 users 추가
- admin, auth, CsrfViewMiddleware, AuthenticationMiddleware 주석 처리

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- westagram/settings.py의 import my_settings 라인에 Import "my_settings" could not be resolved 에러가 뜹니다. 실행엔 문제가 없는데 왜 에러가 뜨는지 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-28 09:55 UTC, ulfrid requested changes
잘하셨네요. 주석만 제거하고 다음 미션 갑시다~👍

2021-01-28 09:55 UTC, ulfrid commented on students/17th/team1/seongyeonkang/westagram/urls.py
> +"""
실제 프로젝트에 필요 없는 주석도 지워주세요.

2021-01-28 10:14 UTC, ulfrid commented
다음 미션 진행해주세요 승연님

2021-01-29 03:18 UTC, phin09 commented on students/17th/team1/seongyeonkang/westagram/urls.py
> +"""
감사합니다 지훈님! 리뷰 받고 응답 없이 수정 요청부터 드려서 죄송해요.
혹시 여기에 이렇게 쓰면 request한 사용자에게(지금은 지훈님께) 알림이 가는, 슬랙 스레드와 같은 대화 방식인지 궁금합니다.

2021-01-29 12:12 UTC, ulfrid commented on students/17th/team1/seongyeonkang/westagram/urls.py
> +"""
ㅎㅎ 그렇지는 않습니다. 물론 프로젝트때는 그렇게 하도록 할거에요 다만, 지금은 자주 확인 하는 수 밖에 없습니다😅

2021-01-29 12:37 UTC, ulfrid requested changes
확인 부탁드립니다.

2021-01-29 12:37 UTC, ulfrid commented on students/17th/team1/seongyeonkang/README.md
> +- password : 사용자가 로그인시 사용할 비밀번호. 최대 8글자.
👍

2021-01-29 12:37 UTC, ulfrid commented on students/17th/team1/seongyeonkang/user/models.py
> +
조금더 미래 지향적으로 생각해보자면 인스타그램에서 요구하는 로그인 가능 정보는 email, phone number, account 입니다.
그럼 필드가 좀 부족하죠? 
당장 쓰이진 않겠지만, 반영해보아요~!
그리고, 보통 회원가입을 관리할때에는 시간정보가 중요합니다. 
created_at = DateTimeField(auto_now_add=True)
updated_at=DateTimeField(auto_now=True)
와 같은 시간 기록을 할때 요긴한 필드가 있습니다. 뒤의 옵션은 한번 구글링 해보시면 어떤 의미인지 설명하는 블로그가 있을겁니다!

2021-01-29 12:37 UTC, ulfrid commented on students/17th/team1/seongyeonkang/user/views.py
> +            return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status=400)
좋은 시도인데, data['email']이 not이라면 이미 이떄에 KeyError이 날거라서 아래의 리턴을 전달하기 전에 에러가 날겁니다.
exception handle을 하거나 다른 방식으로 딕셔너리 값을 겟 하셔야 할것 같아요.

2021-01-29 12:37 UTC, ulfrid commented on students/17th/team1/seongyeonkang/user/views.py
> +        except DataError:
max_length 초과의 케이스 인가요? 잘하셨습니다.
하지만, 익셉션으로 처리하기보다, 입력받으려는 필드의 길이제한을 최소 요건보다 더 많이 주거나, 아니면 입력전에 if문으로 검사하는게 더 좋을 것 같습니다.

2021-01-29 12:37 UTC, ulfrid commented on students/17th/team1/seongyeonkang/user/views.py
> +        try:
try는 필요한 구간에 선언하는것 보다는 로직 상단에 위치하는 게 좋습니다. 
try, except 구문은 매번 구간 마다 선언하는 것이 아닌, 코드 전체에 걸고  로직에서 나는 except만 종류별로 하단에 선언하면 됩니다.

2021-01-29 13:46 UTC, phin09 commented on students/17th/team1/seongyeonkang/westagram/urls.py
> +"""
넵 감사합니다!

2021-01-29 13:48 UTC, phin09 commented on students/17th/team1/seongyeonkang/README.md
> +- password : 사용자가 로그인시 사용할 비밀번호. 최대 8글자.
인용해주신 덕분에 이 파일 수정해야되는 걸 알 수 있었습니다. 내용이 예전 거네요. 감사합니다!!ㅠㅠ

2021-01-30 10:34 UTC, phin09 commented on students/17th/team1/seongyeonkang/user/models.py
> +
이미 DB에 데이터가 있는 상태에서 column을 추가하려고 하니까 이래저래 손이 가네요. 당장 쓰지 않아도 추가해놨다면 이런 일이 없었을 텐데요.. 미래 지향적으로 생각하는 모델링의 이점을 바로 알 수 있었습니다. 감사합니다.

2021-01-30 10:41 UTC, phin09 commented on students/17th/team1/seongyeonkang/user/views.py
> +            return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status=400)
네 KeyError가 납니다. 제가 이 조건을 만들어두고 테스트를 빼먹어서 발견하지 못했어요. 말씀해주신 대로 다른 방법으로 잡겠습니다!

2021-01-30 11:05 UTC, phin09 commented on students/17th/team1/seongyeonkang/user/views.py
> +        except DataError:
그러면 max_length 초과의 케이스는 대개 프론트에서 처리하나요? 이메일을 '@.로 입력한 경우에 http error가 나는 것도 동일한지 궁금합니다(기타질문 두번째 항목). 요청시 아무 메이터도 입력하지 않았을 때 json.decoder.JSONDecodeError가 나서 exception 처리하는 걸 추가했는데 이것도 프론트 소관에 가까운지 궁금합니다!

2021-01-30 11:28 UTC, phin09 commented on students/17th/team1/seongyeonkang/user/views.py
> +        try:
변경하니 코드 가독성이 좋아졌습니다. 감사합니다! 말씀해주신 부분 모두 수정하고 PR에 커밋 쌓았습니다.

2021-01-30 12:02 UTC, ulfrid requested changes
잘하셨습니다 확인 부탁드립니다~!

2021-01-30 12:02 UTC, ulfrid commented on students/17th/team1/seongyeonkang/user/views.py
> +                return JsonResponse({'MESSAGE' : 'EMAIL_ALREADY_EXIST'}, status=400)
```suggestion
                return JsonResponse({'MESSAGE' : 'EMAIL_ALREADY_EXIST'}, status=409)
```
중복 문제니까 409로 해주시면 되겠네요

2021-01-30 12:02 UTC, ulfrid commented on students/17th/team1/seongyeonkang/user/views.py
> +from django.db.utils    import DataError
안쓰게 됐다면~ 제거해주세요 
```suggestion
from django.db.utils    import DataError
```

2021-01-30 12:02 UTC, ulfrid commented on students/17th/team1/seongyeonkang/user/models.py
> +
네 이후에 컬럼 추가를 해야하는 부분은 아마도 장고에서 디폴트 밸류를 요청할텐데 당황하지마시고, 해당 데이터 타입에 맞는 임의값을 넣으시면 됩니다~!

2021-01-30 12:18 UTC, phin09 commented on students/17th/team1/seongyeonkang/user/views.py
> +                return JsonResponse({'MESSAGE' : 'EMAIL_ALREADY_EXIST'}, status=400)
아 코드 설정에 주의 깊지 못했습니다 감사합니다!

2021-01-30 12:19 UTC, phin09 commented on students/17th/team1/seongyeonkang/user/views.py
> +from django.db.utils    import DataError
인용해주신 라인을 포함한 안 쓰는 import들 제거했습니다. 감사합니다.

2021-01-30 12:49 UTC, ulfrid commented on students/17th/team1/seongyeonkang/user/views.py
> +        except DataError:
네 기본적으로는 둘다 해야합니다.  어느 한쪽의 소관이라고 할것 없이 둘다 책임이 있습니다.

2021-01-30 12:50 UTC, ulfrid commented
승연님 미션2도 통과입니다~! 미션 3 진행 부탁드립니다 ~👏👏👏

2021-01-30 13:53 UTC, phin09 commented on students/17th/team1/seongyeonkang/user/models.py
> +
네 가능한 보존하는 쪽으로 연습하겠습니다!

2021-01-30 13:54 UTC, phin09 commented on students/17th/team1/seongyeonkang/user/views.py
> +        except DataError:
그렇군요. '@.'로 인한 http error 빼고는 다 handle했는데 이 것만 해결이 안 나서 추가를 못 했어요. 좀 더 고민해보고 질문드리겠습니다ㅠㅠ

2021-01-30 14:44 UTC, phin09 commented
Mission 3 내에 있는 블로깅 과제는 [여기](https://phin09.tistory.com/60)에 올렸습니다.

2021-01-31 01:43 UTC, phin09 commented
> Mission 3 내에 있는 블로깅 과제는 [여기](https://phin09.tistory.com/60)에 올렸습니다.

블로그 글 수정 중 입니다. 로그인 엔드포인트만 쓰기엔 내용이 부족해서 회원가입 엔드포인트 만들 때 handle했던 사항들도 추가하고 있습니다!

2021-01-31 09:33 UTC, phin09 commented
> > Mission 3 내에 있는 블로깅 과제는 [여기](https://phin09.tistory.com/60)에 올렸습니다.
> 
> 블로그 글 수정 중 입니다. 로그인 엔드포인트만 쓰기엔 내용이 부족해서 회원가입 엔드포인트 만들 때 handle했던 사항들도 추가하고 있습니다!

account와 phone_number 관련 user/views.py 수정을 하기 전의 내용으로 블로깅했습니다.

2021-01-31 09:34 UTC, phin09 commented
잘못 눌러서 PR을 닫았습니다..죄송합니다ㅠㅠ...
블로그 글은 account, phone_number 관련 로직을 추가하기 이전 코드로 수정해두었습니다.

2021-01-31 11:56 UTC, ulfrid commented
잘 하셨습니다. 미션3 통과입니다. 추후에 리팩토링의 기회가 있을 겁니다. 이제는 다음 미션으로 넘어가봐요~👍

2021-03-04 01:02 UTC, merged