[박재현] Mission 1 : Django 초기 세팅
wecode-bootcamp-korea/westagram-backend pull request #198
Opened 2021-01-29 03:48 UTC by namujinju

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Django 초기 프로젝트 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 가상환경 실행하여 Django 설치
- Westagram Django project 생성
- settings.py 수정
- user 앱 생성
- westagram/urls.py 사용하지 않는 코드 삭제
- user/views.py 사용하지 않는 코드 삭제

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-29 05:46 UTC, ulfrid requested changes
확인 바랍니다~!

2021-01-29 05:46 UTC, ulfrid commented on students/17th/team1/jaehyeonpark/westagram/settings.py
> +    'user',
원래의 초기 세팅이면 사용자앱은 포함되어선 안됩니다.

2021-01-29 06:35 UTC, namujinju commented on students/17th/team1/jaehyeonpark/westagram/settings.py
> +    'user',
user 앱 삭제 완료했습니다.
'[Mission 1] Django 초기 세팅'의 STEP2: 02_project_settings_guide.md 파일의 맨 마지막에 user 앱을 만드는 부분이 있어서 따라서 만들었었습니다.

2021-01-29 12:39 UTC, ulfrid commented on students/17th/team1/jaehyeonpark/westagram/settings.py
> +    'user',
저희가 수정하겠습니다 ㅎㅎ;

2021-01-29 12:39 UTC, ulfrid commented
통과입니다. 다음 미션 진행해 주세요! 👍

2021-02-01 02:10 UTC, namujinju commented on students/17th/team1/jaehyeonpark/westagram/settings.py
> +    'user',
감사합니다.

2021-02-01 10:45 UTC, ulfrid requested changes
로직은 깔끔하네요. 다만 모델을 수정 후에 다시 반영 부탁드립니다.

2021-02-01 10:45 UTC, ulfrid commented on students/17th/team1/jaehyeonpark/user/models.py
> +
인스타그램 회원 정보에는 phone_number, account 등의 정보도 있고, 회원정보의 경우 보통 가입일 정보 수정일 등을 담기위해, 
created_at, updated_at등의 시간관리 필드를 사용합니다.
이들 시간관리 필드를 장고에서 사용할때 DateTimeField를 사용하는데 옵션중 (auto_now_add=True), (auto_now=True)와 같은 옵션이 있습니다. 이러한 옵션값을 쓰는 것에 대해 조사해 보신 후 적용 부탁드립니다.

2021-02-01 10:45 UTC, ulfrid commented on students/17th/team1/jaehyeonpark/user/views.py
> +            hashed_password = bcrypt.hashpw(encoded_password, salt)
```suggestion
            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
```
굳이 여러번 담을 필요가 잇을까요?

2021-02-01 11:08 UTC, namujinju commented on students/17th/team1/jaehyeonpark/user/views.py
> +            hashed_password = bcrypt.hashpw(encoded_password, salt)
네, 간단 명료하게 수정하겠습니다.

2021-02-01 11:09 UTC, namujinju commented on students/17th/team1/jaehyeonpark/user/models.py
> +
네. 시간관리 필드에 대해 조사하고 추가하겠습니다. 감사합니다.

2021-02-01 11:48 UTC, namujinju commented on students/17th/team1/jaehyeonpark/user/models.py
> +
추가 완료했습니다.

2021-02-01 15:23 UTC, ulfrid commented
잘 하셨습니다~! 3단계 진행해주세요🥳

2021-02-02 06:31 UTC, ulfrid requested changes
수정 및 블로그 과제도 부탁드립니다.

2021-02-02 06:31 UTC, ulfrid commented on students/17th/team1/jaehyeonpark/user/views.py
> +                    access_token = jwt.encode({'user_id': user_id}, SECRET, algorithm='HS256')
```suggestion
                    access_token = jwt.encode({'user_id': user.id}, SECRET, algorithm='HS256')
```
재사용성 없는 변수 사용은 지양합시다~!

2021-02-02 06:31 UTC, ulfrid commented on students/17th/team1/jaehyeonpark/user/views.py
> +            print(email, account, phone_number)
일단 기본 전제상 프론트에서 한가지 유저정보를 주도록 되어 있기 때문에! 
본 기획의도 및 코드는 좋습니다. 하지만 아래 모델에서 이미 필터링이 충분히 되고 있어서 과하다고 생각되네요.

2021-02-02 06:45 UTC, namujinju commented on students/17th/team1/jaehyeonpark/user/views.py
> +                    access_token = jwt.encode({'user_id': user_id}, SECRET, algorithm='HS256')
네. 의미없는 변수 선언으로 메모리 낭비하는 부분을 고치겠습니다.

2021-02-02 06:47 UTC, namujinju commented on students/17th/team1/jaehyeonpark/user/views.py
> +            print(email, account, phone_number)
네 알겠습니다. 수정하겠습니다. 블로그도 정리해서 코멘트하겠습니다.

2021-02-03 04:27 UTC, namujinju commented on students/17th/team1/jaehyeonpark/user/views.py
> +            print(email, account, phone_number)
블로깅 완료했습니다.
https://namujinju.tistory.com/94

2021-02-03 08:46 UTC, ulfrid requested changes
확인 바랍니다. 블로그는 통과입니다~!

2021-02-03 08:46 UTC, ulfrid commented on students/17th/team1/jaehyeonpark/user/views.py
> +        return JsonResponse({'message':'SUCCESS'}, status=200)
모든 익셉션 뒤에 성공 리턴이 있는건 뭔가 자연스럽지 않죠 회원 가입 성공 리턴을 익셉션 전에 주는건 이상한게 아닙니다. try: except: 는 True/ False 개념에 있지 않기대문에 오리혀 익셉션 리스트 전에 성공 코드를 마무리 하셔야 합니다.

2021-02-03 08:46 UTC, ulfrid commented on students/17th/team1/jaehyeonpark/user/views.py
> +            print(email, account, phone_number)
확인 했습니다.

2021-02-03 10:05 UTC, namujinju commented on students/17th/team1/jaehyeonpark/user/views.py
> +        return JsonResponse({'message':'SUCCESS'}, status=200)
넵 수정 완료했습니다!

2021-02-03 10:35 UTC, ulfrid commented
블로그 과제 제출 부탁드립니다~!

2021-02-03 11:14 UTC, namujinju commented on students/17th/team1/jaehyeonpark/user/views.py
> +        return JsonResponse({'message':'SUCCESS'}, status=200)
https://namujinju.tistory.com/94
블로깅 완료해서 comment 하고 통과했는데 제가 그 이후에 resolve conversation을 눌러서 못보신 것 같습니다.

2021-02-03 11:39 UTC, ulfrid commented
통과입니다~! 다음 미션 진행해 주세요~!!🥳

2021-03-04 01:02 UTC, merged