Feature/hyeonsoogang
wecode-bootcamp-korea/westagram-backend pull request #199
Opened 2021-01-29 04:01 UTC by exgaze

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 초기설정 완료
- 회원가입 구축 1차 완료
		 
## 수정 사항들 자세한 내용
- 초기설정에 따라 가상환경 구축, settings.py 수정, database구축 등을 수행하였습니다.
- 미션 2의 회원가입 엔드포인트 구축을 위해 views.py, urls.py를 작성하였습니다.
- 서로 다른 이메일로 데이터베이스에 데이터가 추가되는지 확인하고, 조건이 제대로 동작하는지 확인하였습니다.

## 기타 질문 및 특이 사항
- 가입시 비밀번호가 아이디의 PK를 참조하도록 만들었습니다. 목적은 로그인 할 때 굳이 비밀번호 데이터 테이블을 직접 불러오지 않고 아이디 테이블을 통해 접근이 가능하도록 하고, 회원 정보를 삭제할 때 아이디만 삭제하여도 그 아이디를 참조하고 있는 비밀번호도 같이 삭제하도록 하고자 한 것입니다. 헌데 작성하다보니 둘은 one-to-one관계라 한 테이블에 있을 수도 있겠다는 생각이 들었는데, 어떤 방식이 더 나은 접근인지 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-29 05:34 UTC, ulfrid requested changes
미션은 한번에 하나씩 하셔야 합니다. 다음부터는 가이드 준수해주세요.

2021-01-29 05:34 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/views.py
> +from user.models  import Id, Password
```suggestion
import json

from django.http  import JsonResponse
from django.views import View

from user.models  import Id, Password
```
줄바꿈이 과합니다. 
임포트의 순서는 다음과 같습니다.
1. python  라이브러리
2. django모듈
3. 사용자가 만든 서브클래스 혹은 메소드 들 
위 순서로 정의 하시되 그룹지어 줄바꿈 해주세요.

2021-01-29 05:34 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/views.py
> +
pep8 상으로는 이렇게 한줄 비우는게 맞지만 위코드 컨벤션에서는 붙여주세요.

2021-01-29 05:34 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/models.py
> +    ids      = models.ForeignKey('Id', on_delete=models.CASCADE, null=True)
이렇게 만들면 사용자 정보는 어디에 저장하죠? 

email. password 모두 결국 사용자 정보에 해당하는 요소들 아닌가요?

2021-01-29 05:34 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/westagram/urls.py
> +
필요없는 주석은 제거부탁드립니다.

2021-01-29 05:34 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/views.py
> +                    )
모델 수정 후 로직 변경 부탁드립니다.

2021-01-29 06:43 UTC, exgaze commented on students/17th/hkk/hyeonsookang/user/models.py
> +    ids      = models.ForeignKey('Id', on_delete=models.CASCADE, null=True)
미션마다 Pull하지 않아 죄송합니다. 이후에는 주의하겠습니다. 주석들은 찾아보며 제거해보도록 하겠습니다. 그리고 User table을 만들고, 사용자 한명당 email과 password는 하나씩 가지니,  User 클래스에 email과 password를 attribute로 만들어 보겠습니다. 마지막으로 이에따라 views.py를 수정해보겠습니다!

2021-01-29 12:09 UTC, ulfrid requested changes
수정 부탁드립니다.

2021-01-29 12:09 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/models.py
> +
회원 가입을 할때에는 필수적으로 필요한 정보가 있습니다. 가입일 이라던지, 조금 더 미션 자체에 집중도 필요하지만, 현실적인 요구사항도 검토해보세요~!
created_at = models.DateTimeField(auto_now_add=True)
같은 요소 입니다.

2021-01-29 12:09 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/views.py
> +            user = User.objects.create(
그저 유저를 생성만 하면 되는데 재사용성 없는 변수를 선언하는 것은 메모리의 낭비입니다. 
```suggestion
            User.objects.create(
```

2021-02-01 02:18 UTC, exgaze commented on students/17th/hkk/hyeonsookang/user/models.py
> +
phonenumber는 integerfield로, account는 charfield로 작성하겠습니다. 그리고 말씀하신 시간정보 찾아보고 적용하겠습니다~

2021-02-01 10:48 UTC, ulfrid requested changes
수정사항 확인 바랍니다~!

2021-02-01 10:48 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/views.py
> +            passwordvalidity = len(data['password'])
굳이 여러번 활용하지 않을것이라면 이렇게 담아두는 것보다 로직에 그대로 작성하는게 나을것 같습니다~!

2021-02-01 10:48 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/views.py
> +            if passwordvalidity < 8:
```suggestion
            if passwordvalidity < PASSWORD_MINIMUM_LENGTH:
```
오히려 위와 같이 비교값 8을 상수로 저장해서 사용해주세요.

2021-02-01 15:21 UTC, ulfrid requested changes
마지막 수정이 될 것 같네요~! 화이팅!

2021-02-01 15:21 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/views.py
> +                return JsonResponse({'MESSAGE': 'ALREADY_SIGNUP'}, status=409)
하나로 줄일 수 있지 않을까요?

2021-02-02 01:56 UTC, exgaze commented on students/17th/hkk/hyeonsookang/user/views.py
> +                return JsonResponse({'MESSAGE': 'ALREADY_SIGNUP'}, status=409)
넵, 줄여보겠습니다!

2021-02-02 02:07 UTC, ulfrid commented
잘 하셨습니다~! 이제 다음미션으로 넘어가시죠~🤩

2021-02-02 05:17 UTC, ulfrid requested changes
확인바랍니다~!

2021-02-02 05:17 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/views.py
> +                if bcrypt.checkpw(data['password'].encode('utf-8'),(id.password).encode('utf-8')) == True:
```suggestion
                if bcrypt.checkpw(data['password'].encode('utf-8'),(id.password).encode('utf-8')):
```
같지 않나요?

2021-02-02 05:17 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/views.py
> +                else:
줄일수 있는 else: 는 없애고 인덴트로 구분하는게 코드 라인수를 줄일 수 있는 습관입니다.

2021-02-02 05:17 UTC, ulfrid commented on students/17th/hkk/hyeonsookang/user/views.py
> +                id = User.objects.get(email=data['email']) or User.objects.get(account='account') or User.objects.get(phonenumber='phone_number')
그다지 효율적으로 느껴지지 않는데요. 장고 Q객체에 대해서 한번 조사해보시겠어요?

2021-02-02 05:28 UTC, exgaze commented on students/17th/hkk/hyeonsookang/user/views.py
> +                if bcrypt.checkpw(data['password'].encode('utf-8'),(id.password).encode('utf-8')) == True:
습관적으로 했네요... 수정하겠습니다~

2021-02-02 05:28 UTC, exgaze commented on students/17th/hkk/hyeonsookang/user/views.py
> +                else:
넵, 알겠습니다

2021-02-02 05:29 UTC, exgaze commented on students/17th/hkk/hyeonsookang/user/views.py
> +                id = User.objects.get(email=data['email']) or User.objects.get(account='account') or User.objects.get(phonenumber='phone_number')
고민하던 부분이었는데 힌트 주셔서 감사합니다~ 한번 조사해보겠습니다!

2021-02-02 09:14 UTC, ulfrid commented
로직은 이정도면 된 것 같고 블로그좀 제출해주세요.

2021-02-02 11:38 UTC, exgaze commented
https://velog.io/@signet/Westagram-Clone-%EB%A1%9C%EA%B7%B8%EC%9D%B8
블로그 주소입니다~ 확인 부탁드려요!

2021-02-02 14:20 UTC, ulfrid commented
블로그의 주제는 아래와 같습니다~!
- httpie를 이용하여 로그인을 진행해보세요.
- 어떠한 잘못된 접근을 시도하였을 때, 어떤 에러가 나는지 블로깅해주세요.
열심히 작성해 주셨지만, 다시 작성 부탁드려요~!

2021-02-03 03:35 UTC, exgaze commented
말씀하신 사항 블로그에 다시 확인하여 작성하였습니다~ 확인 부탁드립니다!

2021-02-03 08:40 UTC, ulfrid commented
수고하셨습니다! 다음 미션 진행 해주세요~🥳

2021-03-04 01:02 UTC, merged