Feature/chaehyun kim
wecode-bootcamp-korea/westagram-backend pull request #200
Opened 2021-01-29 07:28 UTC by JELLO-Kim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 초기세팅 완료
		 
## 수정 사항들 자세한 내용
- my_settings.py 와 .gitignore requirements.txt 생성
- settings.py 주석처리, my_settings.py import 완료
- urls.py와 views.py 초기세팅 완료
- user app 생성 완료

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-29 12:44 UTC, soheon-lee commented
채현님 굿~~~ 통과하셨습니다 :) 다음 스탭 진행해주세요!

2021-02-01 01:49 UTC, ulfrid requested changes
확인 부탁드립니다.

2021-02-01 01:49 UTC, ulfrid commented on students/17th/hkk/chaehyun-kim/user/models.py
> +   password     = models.CharField(max_length=20)
현재로서는 가능한 길이지만 나중에 암호화를 고려했을때는 부족합니다. 
암호화 해서 저장을 고려해서 300자 정도로 변경 부탁드립니다.

2021-02-01 01:49 UTC, ulfrid commented on students/17th/hkk/chaehyun-kim/user/models.py
> +   phone_number = models.CharField(max_length=20)
```suggestion
   email        = models.EmailField(max_length=100, unique=True)
   password     = models.CharField(max_length=20)
   name         = models.CharField(max_length=10, unique=True)
   phone_number = models.CharField(max_length=20, unique=True)
```
이름이 사용자 명을 의미하는 것이 아닌 ID 라면, 모두 유일값만 유지되도록 해주셔야 합니다.

2021-02-01 01:49 UTC, ulfrid commented on students/17th/hkk/chaehyun-kim/user/views.py
> +                return JsonResponse({'message' : 'INVALID_NAME'}, status=409)
꼭 elif여야 하나요? 로직을 작성할때 elif는 꼭 필요하지 않다면 지양하는게 좋습니다.

2021-02-01 01:49 UTC, ulfrid commented on students/17th/hkk/chaehyun-kim/user/views.py
> +        return JsonResponse({user_list}, status=200)
미션과 상관없지만, 확인을 편하게 하려고 작성하신건가요? ㅎㅎ. 지우라는 의미는 아닙니다.

2021-02-01 03:11 UTC, JELLO-Kim commented on students/17th/hkk/chaehyun-kim/user/models.py
> +   password     = models.CharField(max_length=20)
넵!!

2021-02-01 03:13 UTC, JELLO-Kim commented on students/17th/hkk/chaehyun-kim/user/views.py
> +        return JsonResponse({user_list}, status=200)
앗 ㅎㅎ 한번 보려고 작성했던건데 지우는걸 깜빡했습니다!ㅎ

2021-02-01 03:26 UTC, JELLO-Kim commented on students/17th/hkk/chaehyun-kim/user/models.py
> +   phone_number = models.CharField(max_length=20)
name은 계정을 만든 사용자의 실명을 입력시키려는 의도로 작성했습니다! 필요없는 field 였을려나요...ㅎㅎ unique 지정해서 수정하겠습니다! 그런데 password는 지정하지 않아도 되는건가요??

2021-02-01 07:22 UTC, JELLO-Kim commented on students/17th/hkk/chaehyun-kim/user/models.py
> +   phone_number = models.CharField(max_length=20)
넵! 개념 이해하고 추가하겠습니다!

2021-02-01 07:23 UTC, JELLO-Kim commented on students/17th/hkk/chaehyun-kim/user/views.py
> +                return JsonResponse({'message' : 'INVALID_NAME'}, status=409)
넵! 수정하겠습니다!

2021-02-01 10:51 UTC, ulfrid commented
미션 2 통과 축하드립니다! 채현님~! 다음 미션 진행해주세요~!

2021-02-02 08:16 UTC, ulfrid commented
블로그 제출하시면 통과 입니다~!

2021-02-07 16:01 UTC, JELLO-Kim commented
질문은,,, 언제,,어떻게 하면 되는걸까요,, 이 댓글을 보시려나,,,,,,,,,,,,,,,,

2021-02-08 15:37 UTC, JELLO-Kim commented
follow를 할순 있는데 아직 취소는 못함,,

2021-02-09 08:02 UTC, JELLO-Kim commented
게시글 수정, 삭제 기능 추가

2021-02-09 08:12 UTC, JELLO-Kim commented
좋아요 취소 추가

2021-02-09 08:53 UTC, JELLO-Kim commented
팔로우 삭제 기능

2021-02-09 09:12 UTC, JELLO-Kim commented
댓글 삭제 delete method 추가

2021-02-09 17:09 UTC, JELLO-Kim commented
posting, comment, like DetailView 생성

2021-02-09 17:23 UTC, JELLO-Kim commented
follow detailview 작성 - 유저별 following 목록, 언팔기능

2021-02-09 19:09 UTC, JELLO-Kim commented
대댓기능 : 생성, 읽어오기 (특정 댓글에 달린 대댓글들)

2021-03-04 01:02 UTC, merged