[양한아] Mission 1 : 초기 세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #201
Opened 2021-01-30 19:13 UTC by yangahh

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 초기 세팅 완료
		 
## 수정 사항들 자세한 내용
- django 프로젝트 생성
- .gitignore 파일 생성
- my_settings.py 생성과 settings.py 수정
- user app 생성
- requirements.txt 파일 생성

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-31 00:22 UTC, ulfrid commented
잘하셨네요 한아님~! 미션2 진행해 주세요~!👍

2021-01-31 08:08 UTC, ulfrid requested changes
확인 부탁드립니다

2021-01-31 08:08 UTC, ulfrid commented on students/17th/team1/hanahyang/user/views.py
> +                    has_phone = User.objects.filter(Q(phone=phone) & Q(phone__isnull=False))
굳이 인덴트가 뒤로 밀려야 하는 이유를 말씀해주세요. 
일단 값에 대해 검사하는 로직 및 Q객체 사용은 칭찬드립니다.
다만 조금 로직의 논리가 단순히 들어오지가 않네요.
회원가입시 필수값이 전부 들어오지 않아도 가입 할 수 있도록 설정하시는 건가요? 
그렇다해도 null=True 했다면, 굳이 다 검사 할 필요 없이 unique에 대한 부분만 확인 하면 될 것 같습니다.

2021-01-31 17:59 UTC, yangahh commented on students/17th/team1/hanahyang/user/models.py
> +    phone      = models.CharField(max_length=15, null=True, unique=True)
```suggestion
    email      = models.EmailField(max_length=50, unique=True) 
    name       = models.CharField(max_length=20, unique=True) 
    phone      = models.CharField(max_length=15, unique=True)
```
email, name, phone 중 하나만 입력해도 로그인이 되도록 하려고 했었는데 
생각해보니 이건 회원가입이라서 모든 값을 입력받거나 세 개 중 적어도 하나의 값은 not null로 처리해야 하는 게 맞는 것 같습니다.
모든 값을 입력 받는 것으로 수정해보았습니다.

2021-01-31 17:59 UTC, yangahh commented on students/17th/team1/hanahyang/user/models.py
> +    password   = models.CharField(max_length=50)
넵 수정하겠습니다~

2021-01-31 18:02 UTC, yangahh commented on students/17th/team1/hanahyang/user/views.py
> +    p = re.compile('^.+@+.+\.+.+$')
```suggestion
    pattern = re.compile('^.+@+.+\.+.+$')
```
네. 변수명은 구글링으로 생각없이 가져와 쓴 것인데 의미를 확실히 짚고 넘어가게 되었습니다...

2021-01-31 18:32 UTC, yangahh commented on students/17th/team1/hanahyang/user/views.py
> +                    has_phone = User.objects.filter(Q(phone=phone) & Q(phone__isnull=False))
여기서 인덴트는 '&' 앞뒤를 말씀하시는건가요? 아니면 if문 이하 부분인가요?

저의 원래 로직은 회원가입시 email, name, phone 중 하나만 값을 받더라도 가입이 가능하고 
기존 데이터에서 셋 중 하나라도 이미 존재하는 데이터라면 가입이 안되게하는 것이었는데, 
models.py 부분 처럼 세 값 중 아무 한 값만 받아오도록 한 것이  회원가입에 적합하지 않은 로직 같습니다.

세 값을 모두 입력받는 것으로 하여 중복 데이터 체크만 할 수 있도록 수정하겠습니다.
감사합니다!

2021-02-01 02:01 UTC, ulfrid requested changes
확인해주세요~!

2021-02-01 04:03 UTC, yangahh commented on students/17th/team1/hanahyang/user/views.py
> +                return JsonResponse({'message': 'USER_ALREADY_EXISTS'}, status=409)
네 수정하겠습니다!

2021-02-01 04:42 UTC, yangahh commented on students/17th/team1/hanahyang/user/views.py
> +                return JsonResponse({'message': 'USER_ALREADY_EXISTS'}, status=409)
지훈님! 수정하다가 궁금한게 생겼는데 key error를 먼저 체크해야하나요 아니면 validation 체크를 먼저 해야하나요?

2021-02-01 10:54 UTC, ulfrid requested changes
마지막 수정입니다~ 😀

2021-02-01 10:54 UTC, ulfrid commented on students/17th/team1/hanahyang/user/views.py
> +    if len(password) < 8:
```suggestion
    if len(password) < MINIMUM_PASSWORD_LENGTH:
```
8 같은 비교수치를 하드코딩보다는 상수화하는게 좋습니다.

2021-02-01 10:54 UTC, ulfrid commented on students/17th/team1/hanahyang/user/views.py
> +
```suggestion
MINIMUM_PASSWORD_LENGTH = 8
```

2021-02-01 10:54 UTC, ulfrid commented on students/17th/team1/hanahyang/user/views.py
> +                return JsonResponse({'message': 'USER_ALREADY_EXISTS'}, status=409)
지금 상황에서는 KeyError를 우선하는게 맞을것 같습니다~!

2021-02-01 11:26 UTC, yangahh commented on students/17th/team1/hanahyang/user/views.py
> +                return JsonResponse({'message': 'USER_ALREADY_EXISTS'}, status=409)
네 감사합니다! 그러면 if문 인덴트가 지훈님이 제안 주신 거랑 달라질 것 같습니다. 확인 부탁드립니다ㅠㅠ

2021-02-01 11:26 UTC, yangahh commented on students/17th/team1/hanahyang/user/views.py
> +
넵 수정하겠습니다~

2021-02-01 15:19 UTC, ulfrid commented
언제나 정해진 방법이 딱 한가지로 있는것이 아니기 때문에 전 지금 한아님의 로직도 괜찮다고 생각합니다. 미션2 고생하셨습니다. 
이제 3 진행해주세요~!😀

2021-02-02 01:38 UTC, ulfrid requested changes
잘 하셨습니다. 수정 부탁드립니다~!

2021-02-02 01:38 UTC, ulfrid commented on students/17th/team1/hanahyang/user/views.py
> +        return JsonResponse({'message': 'KEY_ERROR'}, status=400)
```suggestion
        if password and (email or name or phone):
             return JsonResponse({'message': 'KEY_ERROR'}, status=400)
        # valid user check  
        if User.objects.filter(Q(email=email) | Q(name=name) | Q(phone=phone)).exists():
            user = User.objects.get(Q(email=email) | Q(name=name) | Q(phone=phone))

            # password check
            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
                # JSON Web Token
                token = jwt.encode({'user_id': user.id}, SECRET['secret'], algorithm='HS256')
                return JsonResponse({'message': 'SUCCESS', 'access_token': token}, status=200) 
            
        return JsonResponse({'message': 'INVALID_ERROR'}, status=401)

               
```
사실 사인 업도 그렇고 이 코드도~ 이렇게 바꾼다고 해서 결과가 달라지진 않을 것  같네요. 코드 가독성 상으로도 훨씬 편해집니다.  Q객체를 사용하니 로직이 너무 간편해지셨죠? 잘 사용하셨습니다.

2021-02-02 02:14 UTC, yangahh commented on students/17th/team1/hanahyang/user/views.py
> +        return JsonResponse({'message': 'KEY_ERROR'}, status=400)
오 감사합니다! 이 생각을 왜 못했을까요ㅎㅎ 수정하겠습니다~

2021-02-02 05:05 UTC, ulfrid requested changes
확인해주세요~!

2021-02-02 05:05 UTC, ulfrid commented on students/17th/team1/hanahyang/user/views.py
> +        return JsonResponse({'message': 'INVALID_ERROR'}, status=401)
```suggestion
        return JsonResponse({'message': 'USER_DOES_NOT_EXIST'}, status=401)
```
이 리턴이 맞을것 같아요.

2021-02-02 05:05 UTC, ulfrid commented on students/17th/team1/hanahyang/user/views.py
> +
비밀 번호가 틀릴경우에 대한 리턴이 없는것 같습니다~!

2021-02-02 05:46 UTC, yangahh commented on students/17th/team1/hanahyang/user/views.py
> +
일치하는 계정이 없는 것과 패스워드가 틀린 것에 대해 반환하는 에러가 같아서 
84번째 줄에서 에러를 같이 처리하도록 한 건데 따로 분리하는게 좋을까요?

2021-02-02 06:25 UTC, ulfrid commented
블로깅 마저 해주시면 통과 드리겠습니다~😀

2021-02-02 08:28 UTC, yangahh commented
https://devvvyang.tistory.com/41
확인 부탁드립니다!
감사합니다:)

2021-02-02 09:45 UTC, ulfrid commented
통과입니다~! 4단계 진행해주세요~!

2021-03-04 01:02 UTC, merged