[정희영] Mission 1 : 초기 세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #202
Opened 2021-01-31 09:50 UTC by sayxyoung

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-31 12:22 UTC, ulfrid commented
통과입니다! 다음 미션 진행해주세요!

2021-02-01 11:03 UTC, ulfrid requested changes
모델 수정 및 로직 수정 부탁드립니다~~!

2021-02-01 11:03 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +class SignUp(View):
```suggestion
class SignUpView(View):
```
그냥 이름을 주기보다 View에 있는 클래스란 의미로 View를 붙여주는 네이밍을 권장 드립니다.
차후에 모델 클래스와 겹칠 가능성이 있기 때문에 애초에 분리하자는 의미로 그렇게 하고 있습니다.

2021-02-01 11:03 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +
이 줄비우기는 의미 없어보이는데 줄여 주세요.

2021-02-01 11:03 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                return JsonResponse({'message':'KEY_ERROR'}, status=400)
```suggestion
                return JsonResponse({'message':'USER_ALREADY_EXIST'}, status=409)
```
이미 존재하는 유저가 있는게 아닐까요?

2021-02-01 11:03 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +            return JsonResponse({'message': 'KEY_ERROR'}, status=400)
이경우도 키에러가 아니라 뭘까요? 바디에 값이 안온거죠? 메세지를 변경해주세요.

2021-02-01 11:03 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +            if not 8 <= len(data['password']):
```suggestion
            if not MINIMUM_PASSWORD_LENGTH <= len(data['password']):
```
패스워드의 최소 허용길이라면 이값도 하드코딩할게 아니라 상수화 해주세요~!

2021-02-01 13:53 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/models.py
> +    password  = models.CharField(max_length=20)
길이 300으로 변경하였습니다.

2021-02-01 13:55 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/models.py
> +
수정하고 db에 값 추가하였습니다.

2021-02-01 13:55 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +from user.models import User
수정하였고 스타일가이드 숙지하겠습니다.

2021-02-01 13:55 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +class SignUp(View):
수정하였고 내용 숙지하겠습니다.

2021-02-01 13:56 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +
위 아래로 불필요한 줄비우기 제거하겠습니다.

2021-02-01 13:57 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                return JsonResponse({'message':'KEY_ERROR'}, status=400)
놓친것 같습니다.. 수정하였습니다. 
관련 http status도 정리하겠습니다.

2021-02-01 13:57 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +            return JsonResponse({'message': 'KEY_ERROR'}, status=400)
유효하지 않은 요청이라는 메시지로 변경하였습니다.

2021-02-01 13:58 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +            if not 8 <= len(data['password']):
수정하였습니다.
하드코딩 피하도록 하고 상수화 사용하도록 하겠습니다.

2021-02-01 15:16 UTC, ulfrid requested changes
마지막 수정이 될 것 같군요~!

2021-02-01 15:16 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +            MINIMUM_PASSWORD_LENGTH = 8
이 상수 선언은~ 함수 바깥 혹은 임포트 아래에 해주세요.

2021-02-01 15:16 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/westagram/urls.py
> +
불필요한 주석 제거해주세요.

2021-02-01 15:31 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +            MINIMUM_PASSWORD_LENGTH = 8
완료하였습니다.

2021-02-01 15:32 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/westagram/urls.py
> +
파일 꼼꼼히 살펴보도록 하겠씁니다.

2021-02-01 15:33 UTC, ulfrid commented
수고하셨습니다~! 미션 3 진행바랍니다 🥳

2021-02-02 07:17 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-02-02 07:17 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                    check.remove(key)
본 로직을 작성 했음에도 불구하고 아래의 모델 필터링에서도, 코드는 전혀 효율적이지 않습니다.
그렇다면 장고 모델 Q객체를 찾아보신 후 효과적 filtering을 진행해보시길 권장 드립니다~!

2021-02-02 08:45 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                    check.remove(key)
Q objects 내용 공부하고 코드 적용하였습니다.
이 후 request.body의 key error는 
dict get method를 활용하여 해결하였습니다.

2021-02-02 09:05 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-02-02 09:05 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                return JsonResponse({'message':'KEY_ERROR'}, status=400)
```suggestion
            if not password:
                return JsonResponse({'message':'KEY_ERROR'}, status=400)
```
작성하신 코드와 이코드의 차이는 무엇일까요?

2021-02-02 09:05 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                    return JsonResponse({'message': 'KEY_ERROR'}, status=400)
이렇게 검사하는 것 보다는 그냥 data['abc'] 에 대해 KeyError exception 핸들하는게 더 공수가 적을 것 같습니다.

2021-02-02 09:05 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                    return JsonResponse({'message':'The account is not valid'}, status=400)
```suggestion
                    return JsonResponse({'message':'The account is not valid'}, status=400)
```
우리가 메세지로 전달하는것은 어떠한 문장이 아닌 스테이터스 코드를 문자화한 코드를 전달하는것입니다.
컨벤션을 따지자면 INVALID_ACCOUNT 와 같이 작성 하셔야 합니다. 나머지 코드들도 수정해주세요~!

2021-02-02 10:29 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                if (user_name == user.user_name or email == user.email or phone_number == user.phone_number) and password == user.password:
따로 쿼리셋 매소드 숙지를 하도록 하겠습니다..

2021-02-02 10:29 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                return JsonResponse({'message':'KEY_ERROR'}, status=400)
변수를 정의하고 조건을 판별해야한다는 고정관념을.... 제거하도록 하겠씁니다..

2021-02-02 16:40 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                    return JsonResponse({'message': 'KEY_ERROR'}, status=400)
지훈님 
해당 class 위에서 정의한 변수
```python
user_name       = data.get('user_name', None)
email                 = data.get('email', None)
password          = data.get('password', None)
phone_number = data.get('phone_number', None)
```
를 최대한 활용하기위해서

```python
if not (user_name or email or phone_number) and not password:
return JsonResponse({'message': 'KEY_ERROR'}, status=400)
```
이런 식으로 코드 구현했는데 괜찮을가요 ?

data['abe']으로 코드 구성하면 제 능력으로는 또 for문을 돌려야할 것같아서요 ㅠ.ㅠ

2021-02-02 16:43 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                    return JsonResponse({'message':'The account is not valid'}, status=400)
인증관련 부분을 401 상태로 처리하고 매칭되는 message로 수정하였습니다.

2021-02-03 08:38 UTC, ulfrid requested changes

2021-02-03 08:38 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                if User.objects.filter(password=password):
이러면 위에서 힘들게 유저 필터링한 의미가 없지 않나요? ㅎㅎ 
패스워드 비교 로직은 패스워드가 있는지 찾는게 아니라, 저 필터링 되는 요건중 어느하나라도 일치해서 나오는 유저의 패스워드와 전송받은 패스워드를 비교 해야겠죠? 확인 부탁드립니다~! 
그리고 수정 다하시면 issue 탭에가서 미션3 과제를 정확히 확인하시고 블로그 제출 부탁드립니다.

2021-02-03 13:37 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                if User.objects.filter(password=password):
```python
user = User.objects.filter(Q(user_name=user_name) | Q(email=email) | Q(phone_number=phone_number))
            if user:
                if user[0].password:
                    return JsonResponse({'message': 'SUCCESS'}, status=200)

2021-02-04 04:36 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                if User.objects.filter(password=password):
아 지훈님 생각해봤는데 위와 같이 하면
기존유저가 아닐 시 에러 메시지 반환을 안되더라구요.. 감사합니다. 그리고 
아래코드 exists 도 스펠링 오타났습니다.

2021-02-04 14:58 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                if User.objects.filter(password=password):
issue 사항 7가지 수정하였고
블로그 아래와 같이 정리하였습니다.

1. 만나고 해결한 에러 정리(https://velog.io/@sayxyoung/TIL-Django-오류모음)
2. 장고 정리(https://velog.io/@sayxyoung/Django-정리)
3. bcrypt, JWT 인증 인가 정리(https://velog.io/@sayxyoung/인증과-인가)

2021-02-04 15:12 UTC, ulfrid requested changes
수정하시면 통과입니다~!

2021-02-04 15:12 UTC, ulfrid commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
else:만 제거해주세요.

2021-02-05 03:19 UTC, sayxyoung commented on students/17th/team-one/heeyoungjeong/user/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
네 알겠습니다.

2021-02-05 15:31 UTC, sayxyoung reviewed
정규 표현식 사용하여
로그인의 이메일, 비밀번호 코드 수정
검증 완료

2021-02-07 14:04 UTC, sayxyoung reviewed
게시물 관련
app 및 모델 클래스 생성

2021-02-07 16:50 UTC, sayxyoung reviewed
PostingVeiw 생성

토큰 복호화 후 인가 절차 구현
인가 후 데이터 저장까지 확인

* 추가로 코드 중복제거를 위한 decorator 구현 필수

2021-02-08 04:01 UTC, sayxyoung reviewed
토큰을 통한 인가부분
decorator생성

* 현재 httpie를 사용하고 있어, 
   request.header가 아닌 request.body로 코드 작성함

2021-02-08 04:44 UTC, sayxyoung reviewed
미션 4번 
get 매소드 누락하여 
생성완료함

2021-02-08 05:44 UTC, sayxyoung reviewed
게시판 댓글 기능 추가
모델링 생성
Class Comment

2021-02-08 06:45 UTC, sayxyoung reviewed
댓글 기능 
Views.py 의 클래스 생성(CommentView)

2021-02-08 07:24 UTC, sayxyoung reviewed
댓글 호출 기능 추가
+ 특정 댓글만 호출 기능 추가

2021-02-08 12:52 UTC, sayxyoung reviewed
좋아요 모델 생성
MtoM

Q. user app / models 에서
    from posting.models import Posting하면 계속 에러남

ImportError: cannot import name 'User' from 'posting.models' (/Users/young/devel/westagram-backend/students/17th/team-one/heeyoungjeong/posting/models.py)
/Users/young/devel/westagram-backend/students/17th/team-one/heeyoungjeong/posting/views.py changed, reloading.

2021-02-08 13:32 UTC, sayxyoung reviewed
unlike 구현 필요

2021-02-09 11:29 UTC, sayxyoung reviewed
PostingDeleteView생성
     (X) user/urls.py user/veiws.py 
     (O) posing/urls.py posing/views.py

2021-03-04 01:02 UTC, merged