[조수아] Mission 1: 초기 세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #203
Opened 2021-01-31 10:10 UTC by suasue

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 프로젝트 초기 세팅 완료
		 
## 수정 사항들 자세한 내용
- westagram project 생성
- settings.py, urls.py 파일 수정
- 보안 정보 저장을 위한 my_settings.py 생성
- .gitignore 파일 생성
- user app 생성 및 views.py 수정

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-31 12:23 UTC, ulfrid commented
통과입니다~!

2021-02-01 02:11 UTC, ulfrid requested changes
전체적인 로직이 깔끔하네요. 확인 부탁드립니다~!

2021-02-01 02:11 UTC, ulfrid commented on students/17th/team1/suacho/user/models.py
> +    username      = models.CharField(max_length=100, unique=True)
둘의 차이는 ID와 진짜 실명의 차이인가요?

2021-02-01 02:11 UTC, ulfrid commented on students/17th/team1/suacho/user/views.py
> +        PASSWORD_MINIMUM_LENGTH = 8
오 상수 사용 굿👍 하지만 이런 상수는 코드 중간에 하기보다는 함수 바깥 혹은 임포트 아래에 선언해주세요.

2021-02-01 02:25 UTC, suasue commented on students/17th/team1/suacho/user/models.py
> +    username      = models.CharField(max_length=100, unique=True)
넵 그렇습니다!  full_name이 실명, username이 ID입니다. 실제 인스타그램 회원가입할 때 이렇게 구분을 하더라구요.

2021-02-01 02:26 UTC, suasue commented on students/17th/team1/suacho/user/views.py
> +        PASSWORD_MINIMUM_LENGTH = 8
네 수정하겠습니다~!

2021-02-01 11:06 UTC, ulfrid requested changes
수정 부탁드립니다~!

2021-02-01 11:06 UTC, ulfrid commented on students/17th/team1/suacho/user/views.py
> +                password      = data['password']
```suggestion
                email         = data.get('email', None),
                mobile_number = data.get('mobile_number', None),
                full_name     = data['full_name'],
                username      = data['username'],
                password      = data['password']
```
검사 마치고 담는거라 위의 최초 변수에 담은 데이터로 연결하면 될 것 같습니다~!

2021-02-01 11:06 UTC, ulfrid commented on students/17th/team1/suacho/user/views.py
> +        return JsonResponse({'message':'SUCCESS'}, status=201)
요 라인은 except 위  create문 아래에 위치해야 할 것 같은데요~!

2021-02-01 11:41 UTC, suasue commented on students/17th/team1/suacho/user/views.py
> +                password      = data['password']
아하 그렇네요.. 수정하겠습니다!

2021-02-01 11:41 UTC, suasue commented on students/17th/team1/suacho/user/views.py
> +        return JsonResponse({'message':'SUCCESS'}, status=201)
넵~!

2021-02-02 05:02 UTC, ulfrid commented
2차미션~ 통과입니다~!🥳 다음 미션 진행해주세요~!!!!

2021-02-02 08:38 UTC, suasue commented
https://velog.io/@suasue/Djaong-HTTP-통신할-때-Error-모음  블로그입니다!

2021-02-02 08:54 UTC, ulfrid requested changes
수정만 마치면 통과입니다~!

2021-02-02 08:54 UTC, ulfrid commented on students/17th/team1/suacho/user/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
보안상 알수 없게 만드는게 좋긴하지만, 지금은 초기임을 입각해서 친절하게 프론트에 전달되도록, INVALID_PASSWORD 라고 해줍시다~!

2021-02-02 09:03 UTC, suasue commented on students/17th/team1/suacho/user/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
네 수정하였습니다~

2021-02-02 09:18 UTC, ulfrid commented
통과입니다~!!! 다음 미션 도전해주세요~!

2021-03-04 01:03 UTC, merged