[허민지] Mission 1: 초기세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #204
Opened 2021-02-01 00:40 UTC by mjhuh263

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Westagram 프로젝트 초기 세팅 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Westagram Project 생성
- User App 생성
- urls.py, settings.py, views.py 주석처리 및 수정
- .gitignore 파일 생성
- mysettings.py 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 앱 이름을 잘못 설정하여 바로 지우고 새로운 앱을 만들었는데 괜찮겠죠..? 나중에 문제될까요..? ㅠㅠ  

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-01 02:13 UTC, ulfrid requested changes
수정 부탁드립니다~!

2021-02-01 02:13 UTC, ulfrid commented on students/17th/team1/minjihuh/westagram/mysettings.py
> +}
my_settings.py로 했으면 안올라왔을텐데 중요정보가 등록되었네요. 변경 및 수정 부탁드려요.

2021-02-01 02:25 UTC, mjhuh263 commented on students/17th/team1/minjihuh/westagram/mysettings.py
> +}
앆!!! 감사합니다... 수정하겠습니다ㅠㅠ

2021-02-01 03:51 UTC, mjhuh263 commented on students/17th/team1/minjihuh/westagram/mysettings.py
> +}
수정했습니다! :-)

2021-02-01 11:36 UTC, ulfrid commented
고생하셨습니다~! 미션~2 진행하시면 됩니다👍

2021-02-01 11:54 UTC, ulfrid requested changes
수정 부탁드립니다.

2021-02-01 11:54 UTC, ulfrid commented on students/17th/team1/minjihuh/user/views.py
> +            MINIMUM_PASSWORD_LEN = 8
상수 값은 함수 내부 보다는 함수 바깥 혹은 클래스 바깥에 위치하는게 좋습니다.
```suggestion
            MINIMUM_PASSWORD_LENGTH = 8
```
이름도 위와 같은게 더 좋을것 같아요

2021-02-01 11:54 UTC, ulfrid commented on students/17th/team1/minjihuh/user/views.py
> +                    return JsonResponse({"MESSAGE" : "INVALID_EMAIL_SYNTAX"}, status=400)
인덴트가 넓은것 같습니다. 조정 해주세요~!

2021-02-01 15:42 UTC, mjhuh263 commented on students/17th/team1/minjihuh/user/views.py
> +            MINIMUM_PASSWORD_LEN = 8
앗 지금 바로 수정하겠습니다! :-)

2021-02-01 15:43 UTC, mjhuh263 commented on students/17th/team1/minjihuh/user/views.py
> +                    return JsonResponse({"MESSAGE" : "INVALID_EMAIL_SYNTAX"}, status=400)
앗..! 지금 수정하겠습니다 ㅠㅠ

2021-02-02 01:33 UTC, ulfrid commented
미션2 통과입니다~! 수고하셨습니다! 다음 미션 진행해주세요~🥳

2021-02-03 08:29 UTC, ulfrid requested changes
확인 바랍니다~!

2021-02-03 08:29 UTC, ulfrid commented on students/17th/team1/minjihuh/user/views.py
> +                user_id = {'user' : user.id}
그냥 바로 넘겨도 되지 않을까요?

2021-02-03 08:29 UTC, ulfrid commented on students/17th/team1/minjihuh/user/views.py
> +                return JsonResponse({"MESSAGE" : "PASSWORD_MUST_BE_LONGER_THAN_EIGHT_LETTERS"}, status=400)
아래 모델에서 비교될 부분이라 굳이 하지 않아도 될 것 같네요. 
특히 길이 비교는 이미 회원가입때 요건 통과한 비밀번호와 비교하는 것이기 때문에 굳이 입력값 검사를  할 필요 없습니다.

2021-02-03 11:31 UTC, mjhuh263 commented on students/17th/team1/minjihuh/user/views.py
> +                return JsonResponse({"MESSAGE" : "PASSWORD_MUST_BE_LONGER_THAN_EIGHT_LETTERS"}, status=400)
넵 바로 고치겠습니다!

2021-02-03 11:31 UTC, mjhuh263 commented on students/17th/team1/minjihuh/user/views.py
> +                user_id = {'user' : user.id}
넵 알겠습니다! :-)

2021-02-04 01:24 UTC, ulfrid commented
코드는 통과입니다~! 민지님 블로그도 주세요~!

2021-02-04 03:21 UTC, mjhuh263 commented
> 코드는 통과입니다~! 민지님 블로그도 주세요~!

2021-02-04 07:46 UTC, mjhuh263 commented
> 코드는 통과입니다~! 민지님 블로그도 주세요~!

https://velog.io/@mjhuh263/TIL-55-Django-%EC%9D%B8%EC%8A%A4%ED%83%80%EA%B7%B8%EB%9E%A8-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-%EB%B0%8F-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%97%94%EB%93%9C%ED%8F%AC%EC%9D%B8%ED%8A%B8-error-%EB%AA%A8%EC%9D%8C

**블로그 작성했습니다!** :-) PR 리오픈 해주셔서 감사합니다~~~ 세션 때 언급하신 부분도 다시 commit했습니다! ><

2021-02-04 08:58 UTC, ulfrid commented
고생하셨습니다~! 통과입니다🥳 다음 미션부터는 자유롭게 진행해주세요~!

2021-03-04 01:03 UTC, merged