[이동근] Mission 1 : 초기 세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #205
Opened 2021-02-01 06:57 UTC by gledong12

…ettings

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-01 11:14 UTC, ulfrid commented
1차는 통과인데 .gitignore 인데 gitignore라고 해서 그냥 파일이 추가됐고, 아직 미션2 아니지만 user app의 urls를 만들어서 경로 전달 해주세요.😀

2021-02-01 11:37 UTC, gledong12 commented
gitignore에서 .gitignore로 수정완료했습니다.!! 
User app에도 urls.py복사 완료했습니다.

2021-02-01 15:14 UTC, ulfrid commented
2단계로 제목 바꿔주시고, 라벨도 변경해주세요~!

2021-02-01 15:38 UTC, ulfrid requested changes
수정부탁드립니다~!

2021-02-01 15:38 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/models.py
> +    Phone_number = models.IntegerField(unique=True)
```suggestion
    phone_number = models.IntegerField(unique=True)
```
변수명은 소문자로, 그리고 전화번호를 인티저로 저장하면 0으로 시작하면 무시되므로, 적절하지 않습니다.

2021-02-01 15:38 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/urls.py
> +
불필요한 주석은 제거해주세요.

2021-02-01 15:38 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/urls.py
> +from django.urls import path, include
```suggestion
from django.urls import path
```
필요없는 건 제거 해주세요.

2021-02-01 15:38 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/views.py
> +        password_validity = data['password']
```suggestion
        password_validity = data['password']
```
이코드도 try안에 안들어가면 KeyError 핸들이 안돼서 익셉션 500 에러가 날겁니다.

2021-02-01 15:38 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/views.py
> +                    Phone_number = data['phone_number'],
변수명 규칙 어긋나게 사용하지 마세요.

2021-02-01 16:34 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/models.py
> +    Phone_number = models.IntegerField(unique=True)
``
phone_number = models.CharField(max_length=15, unique=Ture)
``
1. phone_number  - 소문자로 변경완료했습니다.
2. 정수형 필드인 IntegerField 대신 CharField로 변경했습니다.

2021-02-01 16:37 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/urls.py
> +
westagram/urls.py, User/urls.py - 관련해서 불필요한 주석 제거 완료했습니다.!

2021-02-01 16:37 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/urls.py
> +from django.urls import path, include
User/urls.py 복사해와서 신경을 못쓴것 같습니다. 제거완료했습니다.!!

2021-02-01 16:43 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +        password_validity = data['password']
500 에러 나는거 확인했고, 수정했습니다.!!

2021-02-01 16:45 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +                    Phone_number = data['phone_number'],
수정완료했습니다.

2021-02-02 05:01 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-02-02 05:01 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/views.py
> +        return JsonResponse({'MESSAGE': 'SUCCESS'}, status = 200)
정상 리턴이 익셉션보다 밑에 있는건 코드 흐름상 이상하지 않을까요?

2021-02-02 05:27 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +        MINIMUM_PASSWORD_LENGTH = 8
수정완료했습니다.!!

2021-02-02 05:27 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +
넵!!! 수정완료 했습니다.!!

2021-02-02 05:28 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +                return JsonResponse({"MESSAGE": "Inavailed_Number_Syntax"}, status= 403)
수정완료 했습니다.

2021-02-02 05:29 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +        return JsonResponse({'MESSAGE': 'SUCCESS'}, status = 200)
수정완료했습니다!!!

2021-02-02 05:55 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-02-02 05:55 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/views.py
> +                return JsonResponse({"MESSAGE" : "SHORT_PASSWORD"}, status= 403)
해당 에러들은 400 처리가 맞지 않을까요? 403의 의미를 정확히 짚어봐주시길 바랍니다.

2021-02-02 06:05 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +                return JsonResponse({"MESSAGE" : "SHORT_PASSWORD"}, status= 403)
400 - 해당요청이 잘못되었을때 보내는 코드
403 - 유저가 해당 요청에 대한 권한이 없다는 뜻 

수정완료 했습니다.!!

2021-02-02 06:34 UTC, ulfrid commented
통과입니다~! 미션 3 진행해주세요~👍

2021-02-02 07:41 UTC, ulfrid requested changes
수정 부탁드립니다~!

2021-02-02 07:41 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/models.py
> +# Create your models here.
제거 부탁드립니다~!

2021-02-02 07:41 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/models.py
> +from django.db.models.constraints import UniqueConstraint
이 임포트는 뭔가요?

2021-02-02 07:41 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/views.py
> +            if Userinfo.objects.filter(password = password):
여전히 패스워드를 찾으시는데, 유저를 특정한 뒤 입력받은 패스워드와 유저에 저장된 패스워드가 일치하는지, 비교하셔야 합니다.

2021-02-02 07:53 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/models.py
> +# Create your models here.
넵!!!

2021-02-02 07:53 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/models.py
> +from django.db.models.constraints import UniqueConstraint
중복을 막기위해 unique 속성 넣을려다가 자동으로 넣어진거 같습니다. 제거하겠습니다.!!

2021-02-02 08:16 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +            if Userinfo.objects.filter(password = password):
수정했습니다.

2021-02-02 14:17 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-02-02 14:17 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/views.py
> +                user = Userinfo.objects.get(name = name)
위에서 3가지중에 무엇이 됐든 필터링 되면 True인데, 아래에서는 그냥 name을 기준으로 조회하는건 위험합니다. 
거의 다 오셨는데, 어떻게 하면 될지 생각해보세요~!

2021-02-02 14:17 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/views.py
> +                if Userinfo.objects.filter(user.password == password):
그리고 여전히 왜 password를 조회할까요? 그리고 이거 작동하나요? filter의 대상이  user.password? 확인 부탁드립니다~!

2021-02-02 15:03 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +                user = Userinfo.objects.get(name = name)
아 세개중에 어떤게 올줄 모르니까 name만 해줄께 아니고 or를 통해서 get도 조건을 줘야하네요!!

감사합니다.!!!

2021-02-03 02:52 UTC, ulfrid requested changes
확인 바랍니다~!

2021-02-03 02:52 UTC, ulfrid commented on students/17th/team1/donggeunLEE/westagram/urls.py
> +        path('User', include('User.urls'))
```suggestion
        path('user', include('User.urls'))
```
경로명은 소문자로 해야합니다~!

2021-02-03 02:52 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/views.py
> +                return JsonResponse({"MESSAGE" : "DON'T_EXIST_ID"}, status = 401)
```suggestion
                
                return JsonResponse({"MESSAGE" : "INVALID_PASSWORD"}, status = 401)
           
            return JsonResponse({"MESSAGE" : "INVALID_USER"}, status = 401)
```
else 는 하나라도 줄일 수 있을때 줄여주는게 코드라인수를 줄일수 있는 방법 입니다. 인덴트로 처리해주세요~!
메세지 코드도 보통은 이렇게 해주시는걸 추천드려요.

2021-02-03 02:52 UTC, ulfrid commented on students/17th/team1/donggeunLEE/User/views.py
> +            return JsonResponse({"MESSAGE": "INVALID_USER"}, status = 401)
```suggestion
            return JsonResponse({"MESSAGE": "INVALID_KEYS"}, status = 401)
```
키에러인데 리턴이 유저가 잘못됐다는 잘 못된 것 같습니다~!

2021-02-03 04:28 UTC, gledong12 commented on students/17th/team1/donggeunLEE/westagram/urls.py
> +        path('User', include('User.urls'))
수정하겠습니다.!!

2021-02-03 04:28 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +                return JsonResponse({"MESSAGE" : "DON'T_EXIST_ID"}, status = 401)
또 하나 배웠습니다. 감사합니다.!!

2021-02-03 04:28 UTC, gledong12 commented on students/17th/team1/donggeunLEE/User/views.py
> +            return JsonResponse({"MESSAGE": "INVALID_USER"}, status = 401)
수정하겠습니다.!!

2021-02-03 08:17 UTC, ulfrid commented
코드는 어느정도 정리 된 것 같습니다. issue를 정확히 보셨다면 블로깅 과제 확인 하셔서 작성 후 제출 해주세요!

2021-02-04 10:23 UTC, gledong12 commented
블로깅 과제 제출합니다.!! 
 [https://velog.io/@eagle5424/TIL-43-Westagram3](url)

2021-02-04 10:24 UTC, gledong12 commented
[https://velog.io/@eagle5424/TIL-43-Westagram3](url)
블로깅 과제 제출합니다.!!!!

2021-02-04 10:28 UTC, gledong12 commented
[https://velog.io/@eagle5424/TIL-43-Westagram3](url)

2021-02-04 10:31 UTC, gledong12 commented
지훈님 블로깅 과제는 완료했는데 url추가하니 404에러가 계속 뜨네요.... github에서 404를 주네요......
[https://velog.io/@eagle5424](url)

2021-02-04 10:34 UTC, gledong12 commented
지훈님 블로깅 과제는 완료했는데 url추가하니 404에러가 계속 뜨네요.... github마저도 404를 주네요......
[https://velog.io/@eagle5424](url)
https://velog.io/@eagle5424/TIL-43-Westagram3
완료한 블로깅  url 입니다.!!

2021-02-04 10:45 UTC, ulfrid commented
통과 입니다~! 이후 과정 진행 해주세요~!

2021-03-04 01:03 UTC, merged