Create: created django project - started  django westagram proejct
wecode-bootcamp-korea/westagram-backend pull request #206
Opened 2021-02-01 07:13 UTC by markkimjr

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
- Created django westagram project
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-01 11:16 UTC, ulfrid commented on students/17th/team1/markkim/westagram/settings.py
> +SECRET_KEY = '3-0fem@v84%55y3-*g5w!-0hazn+l-tr+j=&!22dd(+8h1l$9r'
```suggestion
SECRET_KEY = '3-0fem@v84%55y3-*g5w!-0hazn+l-tr+j=&!22dd(+8h1l$9r'
```
씨크릿 키는  중요정보이므로 깃에 공유되어서는 안됩니다. 따라서  manage.py가 위치하는 경로에 my_settings.py같은 파일을 만들어서 거기에 저장한뒤에 임포트 후 적용해야 합니다. 변경 부탁드립니다.

2021-02-01 11:17 UTC, ulfrid commented on students/17th/team1/markkim/westagram/settings.py
> +}
```suggestion
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
```
MySQL 적용한뒤 접속정보는 마찬가지로 my_settings.py에 기록한 후 임포트해서 적용해주세요.

2021-02-01 11:17 UTC, ulfrid commented on students/17th/team1/markkim/westagram/settings.py
> +    'django.contrib.auth',
```suggestion
#    'django.contrib.admin',
#    'django.contrib.auth',
```

2021-02-01 11:17 UTC, ulfrid commented on students/17th/team1/markkim/westagram/settings.py
> +    'django.contrib.auth.middleware.AuthenticationMiddleware',
```suggestion
#    'django.middleware.csrf.CsrfViewMiddleware',
#    'django.contrib.auth.middleware.AuthenticationMiddleware',
```

2021-02-01 11:17 UTC, ulfrid commented on students/17th/team1/markkim/westagram/urls.py
> +"""
주석은 제거부탁드립니다.

2021-02-01 11:18 UTC, ulfrid commented on students/17th/team1/markkim/westagram/urls.py
> +from django.contrib import admin
안쓸꺼라 제거해주세요.

2021-02-01 11:18 UTC, ulfrid commented on students/17th/team1/markkim/westagram/urls.py
> +    path('admin/', admin.site.urls),
마찬가지로 필요없으니 제거해주세요.

2021-02-01 14:58 UTC, markkimjr commented on students/17th/team1/markkim/westagram/settings.py
> +SECRET_KEY = '3-0fem@v84%55y3-*g5w!-0hazn+l-tr+j=&!22dd(+8h1l$9r'
수정했습니다!

2021-02-01 14:58 UTC, markkimjr commented on students/17th/team1/markkim/westagram/settings.py
> +}
넵!

2021-02-01 14:59 UTC, markkimjr commented on students/17th/team1/markkim/westagram/settings.py
> +    'django.contrib.auth',
주석 처리했습니다!

2021-02-01 15:11 UTC, ulfrid commented
하성님~! 아직 미션1 통과 안됐는데 맘대로 미션2 하시면 안됩니다~!  일단 미션 1은 통과입니다. 하지만, 제가 확인 해드리기전에 이렇게 바꾸시면 안돼요~! 그리고 미션 2 코드는 아직 평가하기에는 코드가 다 완성 안되있는 상태로 보이는데 확인 바랍니다~!

2021-02-01 15:18 UTC, markkimjr commented
앗! 지훈님 미안해요ㅠ 다음분터는 꼭 미션 통과 받은 다음에 다음 미션을 도전 할게요. 늦은 시간에 피드백 주셔서 너무 감사해요!!

2021-02-02 03:19 UTC, markkimjr commented
지훈님~ 2번 미션에 views.py에 있는 코드가 완성 안된건가요? 혹시 어느 부분 (models.py, views.py)을 수정해야되는지 힌트 줄수있어요 ㅠ

2021-02-02 07:09 UTC, ulfrid commented
구두로 리뷰해드린대로, values_list를 쓰는것보다 더 간결한 컨디션을 갖게 해주는 filter.exists()를 권장드리고~! request.body에 들어온 데이터를 어떻게 핸들링 할지 결정후 로직의 방향도 정해서 다시 구현 부탁드립니다.~!

2021-02-02 09:17 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-02-02 09:17 UTC, ulfrid commented on students/17th/team1/markkim/user/views.py
> +        return JsonResponse({'message': 'SUCCESS'}, status=200)
```suggestion
    try:
        data         = json.loads(request.body)
        email        = data['email']
        password     = data['password']
        full_name    = data['full_name']
        phone_number = data['phone_number']
        username     = data['username']

        if email == '' or password == '':
            return JsonResponse({'message': 'KEY_ERROR'}, status=400)

        if '@' not in email or '.' not in email:
            return JsonResponse({'message': 'INVALID_EMAIL'}, status=400)
        
        if len(password) < 8:
            return JsonResponse({'message': 'INVALID_PASSWORD'}, status=400)
        
        if User.objects.filter(full_name=full_name).exists():
            return JsonResponse({'message': 'FULL_NAME_ALREADY_EXISTS'}, status=409)
        
        if User.objects.filter(email=email).exists():
            return JsonResponse({'message': 'EMAIL_ALREADY_EXISTS'}, status=409)
        
        if User.objects.filter(phone_number=phone_number).exists():
            return JsonResponse({'message': 'PHONE_NUMBER_ALREADY_EXISTS'}, status=409)
        
        User.objects.create(
                full_name    = full_name,
                email        = email,
                phone_number = phone_number,
                username     = username,
                password     = password
                )
        
        return JsonResponse({'message': 'SUCCESS'}, status=200)
    except KeyError:  
```
잊은것 같지 않아요? 😫

2021-02-02 09:48 UTC, markkimjr commented on students/17th/team1/markkim/user/views.py
> +        return JsonResponse({'message': 'SUCCESS'}, status=200)
변수 다 빼고 if문으로 처리 했어요 (try/error 안쓰고)~ 또 리뷰해야되서 죄송해요 ㅠ

2021-02-02 14:52 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-02-02 14:52 UTC, ulfrid commented on students/17th/team1/markkim/user/views.py
> +
여전히 키에러의 위험이 있으니 try & except 적용해주세요~!

2021-02-03 03:00 UTC, markkimjr commented on students/17th/team1/markkim/user/views.py
> +
넵 적용했어요!!

2021-02-03 07:12 UTC, ulfrid commented
축하합니다~! 미션 3 진행해주세요🥳

2021-02-04 02:23 UTC, ulfrid requested changes
수정 및 ISSUE탭 확인해서 미션3 내용확인 후 블로그 과제 작성해서 제출 바랍니다.

2021-02-04 07:48 UTC, markkimjr commented on students/17th/team1/markkim/user/views.py
> +            pw    = data['password']
피드백 감사합니다~~ pw를 password로 바꾸고 hashed_pw도 hashed_password로 바꿨어요. jwt_token에 있는 'secret'은 my_settings.py에 있는 secret_key로 대입했어요. 제 블로그 링크 는: https://velog.io/@markkimjr/WEstagram-Login-Errors 입니다😄

2021-02-04 07:54 UTC, ulfrid requested changes
수정 부탁드립니다.

2021-02-04 07:54 UTC, ulfrid commented on students/17th/team1/markkim/user/views.py
> +            print(data)
print 문은 제거해 주세요~!

2021-02-04 07:54 UTC, ulfrid commented on students/17th/team1/markkim/user/views.py
> +
빈줄 제거해주세요~!

2021-02-04 07:54 UTC, ulfrid commented on students/17th/team1/markkim/user/views.py
> +            salt         = bcrypt.gensalt()
```suggestion
            salt         = bcrypt.gensalt()
```
salt를 여러번 쓰지 않기 때문에 그냥 hashpw에서 바로 선언하시고, 이 내용은 삭제해주세요.

2021-02-04 07:54 UTC, ulfrid commented on students/17th/team1/markkim/user/views.py
> +
빈줄 제거해주세요.

2021-02-04 11:25 UTC, ulfrid commented
블로그는 합격입니다 ㅋㅋㅋ 수정마저 해주세요!

2021-02-04 11:52 UTC, markkimjr commented on students/17th/team1/markkim/user/views.py
> +            salt         = bcrypt.gensalt()
넵 salt삭제했어요~

2021-02-04 11:52 UTC, markkimjr commented on students/17th/team1/markkim/user/views.py
> +            print(data)
ㅋㅋㅋ 넵!

2021-02-04 11:53 UTC, markkimjr commented
빈칸 제거 하고 salt변수 삭제 했어요~ 리뷰 감사합니다!

2021-02-04 12:06 UTC, ulfrid commented
고생하셨습니다~! 통과입니다!! 다음 미션 진행해주세요~!!

2021-03-04 01:03 UTC, merged