[조혜윤] Mission 1 : 초기 세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #207
Opened 2021-02-01 11:49 UTC by hyeyoonc

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-01 14:57 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-02-01 14:57 UTC, ulfrid commented on students/17th/raon/hyeyoon/westagram/settings.py
> +SECRET_KEY = 'scjya3ww1x1un9+m86o(mn6m+m)s4*563t&6lsv5q(2#($0u!@'
SECRET_KEY는 보안상 깃헙에 공개되면 이슈가 되는 사항입니다. 노출되면 보안취약점이 되는 부분이죠.
그래서 가이드해드렸던, manage.py 와 같은 경로에 my_settings.py를 작성하시고, 거기에 SECRET 코드를 작성한뒤  settings.py에서 import 후 적용해주셔야 합니다.

2021-02-01 14:57 UTC, ulfrid commented on students/17th/raon/hyeyoon/westagram/settings.py
> +}
DATABASE도 MySQL 적용하시고~ 마찬가지로 접속정보는 my_settings.py에 작성후 임포트 해서 적용 부탁드립니다.

2021-02-01 14:57 UTC, ulfrid commented on students/17th/raon/hyeyoon/westagram/urls.py
> +"""
불필요한 주석은 제거해주세요~!

2021-02-02 06:09 UTC, hyeyoonc commented on students/17th/raon/hyeyoon/westagram/settings.py
> +SECRET_KEY = 'scjya3ww1x1un9+m86o(mn6m+m)s4*563t&6lsv5q(2#($0u!@'
변경했습니다~~~~

2021-02-02 06:12 UTC, hyeyoonc commented on students/17th/raon/hyeyoon/westagram/settings.py
> +}
지훈님!
mysql database 연결할때 databases에 engine,name만 넣으면되나요? 유저,패스워드,호스트는 안넣어도 되는건가요? ㅎㅎ
일단 두개만 넣었습니다~~

2021-02-02 06:18 UTC, hyeyoonc commented on students/17th/raon/hyeyoon/westagram/urls.py
> +"""
다 지워버렸습니다~

2021-02-02 06:42 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-02-02 06:42 UTC, ulfrid commented on students/17th/raon/hyeyoon/westagram/settings.py
> +
SECRET_KEY는 어디로....? 😅

2021-02-02 06:54 UTC, hyeyoonc commented on students/17th/raon/hyeyoon/westagram/settings.py
> +}
완료했습니다~

2021-02-02 07:17 UTC, hyeyoonc commented on students/17th/raon/hyeyoon/westagram/settings.py
> +
해냈습니다~

2021-02-02 07:36 UTC, ulfrid commented on students/17th/raon/hyeyoon/westagram/settings.py
> +
해내셨군요! 축하드립니다👍

2021-02-02 07:36 UTC, ulfrid commented
통과 입니다~ 혜윤님! 다음 미션 진행해주세요~🥳

2021-02-04 01:53 UTC, ulfrid requested changes
수정 부탁드립니다~!

2021-02-04 01:53 UTC, ulfrid commented on students/17th/raon/hyeyoon/user/views.py
> +
의미 없는 빈줄은 지양해주세요~!

2021-02-04 01:53 UTC, ulfrid commented on students/17th/raon/hyeyoon/user/views.py
> +min_length = 8
```suggestion
MIN_LENGTH = 8
```
변수화 잘하셨는데! 이런 케이스는 상수로 선언하는게 좋습니다.

2021-02-04 01:53 UTC, ulfrid commented on students/17th/raon/hyeyoon/user/views.py
> +min_length = 8
아래 로직도 변경해주세요~!

2021-02-04 04:14 UTC, hyeyoonc commented on students/17th/raon/hyeyoon/user/views.py
> +
네네 ㅎㅎ 삭제했습니다

2021-02-04 04:14 UTC, hyeyoonc commented on students/17th/raon/hyeyoon/user/views.py
> +min_length = 8
변경했습니다~ ㅎㅎ

2021-02-04 07:52 UTC, ulfrid requested changes
수정 부탁드립니다~!

2021-02-04 07:52 UTC, ulfrid commented on students/17th/raon/hyeyoon/user/views.py
> +class UserSignUpView(View):
```suggestion
import json

from django.views           import View
from django.http            import JsonResponse, HttpResponse
from django.core.validators import validate_email
from django.core.exceptions import ValidationError

from .models import Account

PASSWORD_MIN_LENGTH = 8

class UserSignUpView(View):
```
요렇게 해주시는게 좋을 것 같습니다~!

2021-02-04 07:52 UTC, ulfrid commented on students/17th/raon/hyeyoon/user/views.py
> +        phone_number = data['phone_number']
이 친구들이 try 밖에 있으면 안들어오면 키에러시 500될것 같아요

2021-02-04 08:00 UTC, hyeyoonc commented on students/17th/raon/hyeyoon/user/views.py
> +        phone_number = data['phone_number']
헉 그러네요 ㅠㅠ 변경했습니다 ~~~

2021-02-04 08:56 UTC, ulfrid commented
통과입니다~ 미션3 진행 부탁드립니다~!! 🥳

2021-02-07 06:25 UTC, ulfrid requested changes
수정 및 블로그 과제 확인해서 진행 부탁드립니다~!

2021-02-07 06:25 UTC, ulfrid commented on students/17th/raon/hyeyoon/user/views.py
> +            if Account.objects.filter(email = email).exists() or Account.objects.filter(password = password).exists():
이메일이 존재하는지 확인하는건 맞는데, 비밀번호가 존재하는지 확인하는게 아니라, 존재하는 사용자를 찾았다면, 그 사용자에 저장된 비밀번호와 request로 전달받은 비밀번호가 일치하는지 확인해야 합니다.

2021-02-07 07:27 UTC, hyeyoonc commented on students/17th/raon/hyeyoon/user/views.py
> +            if Account.objects.filter(email = email).exists() or Account.objects.filter(password = password).exists():
앗 네네 수정했습니다 ㅎㅎㅎ

2021-02-07 07:29 UTC, hyeyoonc commented on students/17th/raon/hyeyoon/user/views.py
> +            if Account.objects.filter(email = email).exists() or Account.objects.filter(password = password).exists():
지훈님 주말에도 리뷰해주셔서 정말 x 100 감사합니다 ㅠㅠ 
설 연휴 잘 보내세요ㅎㅎ🥳

2021-02-09 05:56 UTC, ulfrid commented
고생하셨습니다. 블로그 제출해주세요~!

2021-02-10 06:30 UTC, hyeyoonc commented
https://velog.io/@hyeyoonc/%EA%B7%80%EC%97%AC%EC%9A%B4-error-%EB%AA%A8%EC%9D%8C%EC%A7%91

2021-03-04 01:03 UTC, merged