[남채린] Mission 1 : 초기 세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #208
Opened 2021-02-01 11:50 UTC by namchaerin

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-01 14:59 UTC, ulfrid requested changes
수정 부탁드립니다~!

2021-02-01 14:59 UTC, ulfrid commented on students/17th/raon/chaerin/westagram/settings.py
> +SECRET_KEY = 'se!lei@-*&b%&@&@a#-=is6a+9cnkq*%$$#zikesvht40*a(qt'
SECRET_KEY는 보안상 깃헙에 공개되면 이슈가 되는 사항입니다. 노출되면 보안취약점이 되는 부분이죠.
그래서 가이드해드렸던, manage.py 와 같은 경로에 my_settings.py를 작성하시고, 거기에 SECRET 코드를 작성한뒤 settings.py에서 import 후 적용해주셔야 합니다.

2021-02-01 14:59 UTC, ulfrid commented on students/17th/raon/chaerin/westagram/settings.py
> +}
DATABASE도 MySQL 적용하시고~ 마찬가지로 접속정보는 my_settings.py에 작성후 임포트 해서 적용 부탁드립니다.

2021-02-01 14:59 UTC, ulfrid commented on students/17th/raon/chaerin/westagram/urls.py
> +"""
주석도 제거 부탁드립니다~!

2021-02-01 17:33 UTC, namchaerin commented on students/17th/raon/chaerin/westagram/settings.py
> +SECRET_KEY = 'se!lei@-*&b%&@&@a#-=is6a+9cnkq*%$$#zikesvht40*a(qt'
수정했습니다!

2021-02-02 04:53 UTC, ulfrid commented
통과입니다~! 미션2 진행해주세요~!

2021-02-04 02:58 UTC, ulfrid requested changes
수정 부탁드립니다~!

2021-02-04 02:58 UTC, ulfrid commented on students/17th/raon/chaerin/user/views.py
> +                if p.match(str(email)):
변수명을 의미없이 선언하는건 좋지 않은 습관입니다. 명확하게 변수명 지정하도록 해주세요~!

2021-02-04 02:58 UTC, ulfrid commented on students/17th/raon/chaerin/user/views.py
> +                    return JsonResponse({'MESSSAGE': 'PASSWORD_IS_SHORT!'}, status=400)
메세지를 주는건 대화를 하는게 아니라, 에러코드를 문자로 전달하는것 입니다~ '!'는 감정 전달이 느껴지네요 ㅋㅋㅋ
특수 기호는 빼주세요~!

2021-02-04 03:08 UTC, namchaerin commented on students/17th/raon/chaerin/user/views.py
> +                    return JsonResponse({'MESSSAGE': 'PASSWORD_IS_SHORT!'}, status=400)
앗 ㅎㅎ 느낌표로 인한 대화체 느낌을 없애라는 말씀이신거죠?! 

수정했습니다!

2021-02-04 07:49 UTC, ulfrid requested changes
수정 부탁드립니다~!

2021-02-04 07:49 UTC, ulfrid commented on students/17th/raon/chaerin/user/views.py
> +                    return JsonResponse({'MESSSAGE': 'INVALID_EMAIL'}, status=400)
```suggestion
                if not email_form.match(str(email)):
                    return JsonResponse({'MESSSAGE': 'INVALID_EMAIL'}, status=400)
```

2021-02-04 07:49 UTC, ulfrid commented on students/17th/raon/chaerin/user/views.py
> +
빈줄 제거 부탁드립니다~!

2021-02-04 09:35 UTC, namchaerin commented on students/17th/raon/chaerin/user/views.py
> +
수정 했습니다 ~ !!

2021-02-04 10:15 UTC, ulfrid commented
잘하셨습니다~!!! 미션 3로 넘어가시죠~!

2021-02-07 06:23 UTC, ulfrid requested changes
확인 부탁드립니다. 수정 및 블로그 과제도 확인해서 제출해주세요~!

2021-02-07 06:23 UTC, ulfrid commented on students/17th/raon/chaerin/user/views.py
> +                return JsonResponse({'MESSSAGE': 'INVALID_USER'}, status=401)
```suggestion
                return JsonResponse({'MESSSAGE': 'INVALID_PASSWORD'}, status=401)
```
비번이 틀린거니까 정확히 해주세요~!

2021-02-07 06:23 UTC, ulfrid commented on students/17th/raon/chaerin/user/views.py
> +            #username  = data['username']
안쓰는거면 제거 해주세요~! 머지를 가정하고 코드를 올리는거면 머지되는 코드가 최종이기 때문에 최종코드에 이런 주석이 있는건 불완전 요소이므로 지양해주세요~!

2021-02-07 06:23 UTC, ulfrid commented on students/17th/raon/chaerin/user/views.py
> +            #phone_num = data['phone_num']
```suggestion
            #phone_num = data['phone_num']
```
마찬가지입니다.

2021-02-07 06:42 UTC, namchaerin commented on students/17th/raon/chaerin/user/views.py
> +            #phone_num = data['phone_num']
수정했습니다!
😇지훈님 주말임에도 불구하고 리뷰 해주셔서 감사드립니다!!!
블로그 작성해서 제출하도록 하겠습니다! 
즐거운 주말 보내세요~! 항상 감사드립니다😊

2021-02-08 02:23 UTC, ulfrid commented on students/17th/raon/chaerin/user/views.py
> +            #phone_num = data['phone_num']
넵~!!

2021-02-08 13:00 UTC, namchaerin commented
https://velog.io/@rin0702/Westagram-3
블로그 작성하였습니다!
연휴동안 푹 쉬시구 행복한🌈 시간 보내세요 지훈님! ☺️

2021-02-09 05:55 UTC, ulfrid commented
확인했습니다~ 고생하셨습니다~! 통과입니다😁

2021-03-04 01:04 UTC, merged