[심규보] Mission 1 : 초기 세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #209
Opened 2021-02-01 11:52 UTC by Gyubster

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- westagram 생성
		 
## 수정 사항들 자세한 내용
- user app 생성
- .gitingore 생성
- my_settings 생성
- 안쓰는 모듈 주석 처리 및 삭제

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 없음. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-01 15:06 UTC, ulfrid requested changes
수정해주시고, 단계상 필요없는 코드는 리뷰하지 않았습니다. 1단계 통과하시고, 올려주시거나, 그러기 어렵다면, 일단 수정사항 수정하시고 미션2로 넘어가서 리뷰 드리겠습니다~!

2021-02-01 15:06 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/westagram/settings.py
> +SECRET_KEY = my_settings.SECRET
굳이 이렇게 해야하는지는 모르겠지만, 그냥 원래대로 자연스럽게 부탁드릴께요~!

2021-02-01 15:06 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/westagram/urls.py
> +"""
필요없는 주석은 제거합시다.

2021-02-02 14:15 UTC, Gyubster commented on students/17th/team1/gyuboshim/westagram/westagram/urls.py
> +"""
status를 바꿔야되는걸 모르고 미션2까지 git을 푸쉬하다가 늦게 status를 바꿨습니다.. 완료하기전에 mission2로 제목을 바꿔서 죄송합니다 ㅜㅜ

2021-02-02 14:45 UTC, ulfrid requested changes
수정 바랍니다~!

2021-02-02 14:45 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/models.py
> +    password        =   models.CharField(max_length = 15)
```suggestion
    phone_number    =   models.CharField(max_length = 15)
    email_adress    =   models.CharField(max_length = 100)
    name            =   models.CharField(max_length = 50)
    nickname        =   models.CharField(max_length = 50)
    password        =   models.CharField(max_length = 300)
```
길이가 너무 적네요. 여유있게 주는게 좋습니다. 현대에 와서는 디스크 가격이 싸기 때문에, 굳이 최소 공간을 적용하는것 보다, 그러한 부분은 로직에서 구별하고, DB자체는 모자라는것보다는 남는게 좋은 쪽으로, 설계해주세요.

2021-02-02 14:45 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +                if user_data['email_adress'] == User.objects.filter(email_adress = email_adress):
```suggestion
                if User.objects.filter(email_adress = email_adress):
```
둘에 차이가 있는지 한번 생각해 봅시다.

2021-02-02 14:45 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +                    return JsonResponse({'message':'CHANGE_E-MAIL_ADRESS'}, status = 409)
응답이 너무 친절하네요 규보님. 
```suggestion
                    return JsonResponse({'message':'EMAIL_ALREADY_EXISTS'}, status = 409)
```
근데 바꾸라고 하는것 보다는 이미 존재하니까 존재한다고 말해주는게 맞습니다.

2021-02-02 14:45 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +            if user_data['email_adress'] and user_data['password']:
이 로직이 바깥에 위치하지 않고 같은 인덴트에 위치해도~ 기대 효과대로 동작할것 같습니다. 
굳이 위에 변수로 다 담아 놓고 여기서 다시 딕셔너리의 키를 찍는 이유를 알고 싶습니다. 
```suggestion
            if not email_adress and not password:
                return JsonResponse('.......') 
```
이렇게 처리하면 위의 중첩 if문이 필요 없지 않을까요?

2021-02-02 14:45 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +        except:
```suggestion
        except KeyError:
```
except만 걸면 모든 익셉션시 아래 리턴이 나가므로, 주의해야합니다.

2021-02-02 14:45 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +                    return JsonResponse({'message':'CHANGE_E-MAIL_ADRESS'}, status = 409)
위의 수정사항을 기준으로 아래의 코드들도 수정 부탁드립니다.

2021-02-03 03:20 UTC, Gyubster commented on students/17th/team1/gyuboshim/westagram/user/models.py
> +    password        =   models.CharField(max_length = 15)
네 알겠습니다!

2021-02-03 03:21 UTC, Gyubster commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +                if user_data['email_adress'] == User.objects.filter(email_adress = email_adress):
아하 이해했습니다!

2021-02-03 03:29 UTC, Gyubster commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +                if user_data['email_adress'] == User.objects.filter(email_adress = email_adress):
한가지 질문이 있습니다. 
if User.objects.filter(email_adress = email_adress).extists() 와
if User.objects.filter(email_adress = email_adress)의 차이는 없는건가요..? 

찍어봤는데, 가독성을 위해서 쓰는것같다라는 생각밖에 들지않아서 혹시 다른 차이가 있나해서 질문합니다.

2021-02-03 03:31 UTC, Gyubster commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +                    return JsonResponse({'message':'CHANGE_E-MAIL_ADRESS'}, status = 409)
네 확인했습니다

2021-02-03 03:36 UTC, Gyubster commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +            if user_data['email_adress'] and user_data['password']:
이 부분 변수로 모두 고쳤습니다! 저도 어제 푸쉬하고 다시보면서 변수선언하고 변수를 안썻네..라는 상황을 마주해서 수정했습니다!

2021-02-03 03:38 UTC, Gyubster commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +            if user_data['email_adress'] and user_data['password']:
중첩 if문이 필요가 없어질 수 있다는 부분은 이해가 잘 되지않습니다..ㅜ 일단 조금 더 수정한 상태이니 한번 리뷰 부탁드립니다

2021-02-03 07:57 UTC, ulfrid requested changes
확인 바랍니다~!

2021-02-03 07:57 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +                user = User.objects.create(
```suggestion
           User.objects.create(
```
굳이 담을 필요가 있을까요?

2021-02-03 07:57 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +                    return JsonResponse({"message":"@_OR_._DOES_NOT_EXIST"}, status = 400)
```suggestion
                    return JsonResponse({"message":"NOT_EMAIL"}, status = 400)
```
너무 친절한데요. 이렇게 바꾸는건 어떨까요?

2021-02-03 07:57 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +                    return JsonResponse({"message": "PASSWORD_HAS_TO_BE_AT_LEAST_8-DIGIT"}, status = 400)
```suggestion
                    return JsonResponse({"message": "SHORT_PASSWORD"}, status = 400)
```
이정도면 될것 같습니다. 바로 메세지로서의 에러코드 이기 때문에 너무 설명적이지 않도록 해주세요.

2021-02-03 07:58 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +                if user_data['email_adress'] == User.objects.filter(email_adress = email_adress):
if 자체는 동작합니다. 하지만 리턴은 다르죠.

2021-02-03 08:01 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +            if user_data['email_adress'] and user_data['password']:
그냥 컨셉의 문제 같습니다. 이값과 이값이 들어와야만 아래에 있는 일을 하겠어와, 이것 이것 이것이 들어오지 않으면 일단 에러 리턴을 받으므로 더이상 진행하지 않는것 제가 제안드린건 이런  이야기 였습니다.

2021-02-04 07:45 UTC, ulfrid requested changes
수정해주시고 미션 3 진행 부탁드립니다~!

2021-02-04 07:45 UTC, ulfrid commented on students/17th/team1/gyuboshim/westagram/user/views.py
> +import json
```suggestion
import json

from django.shortcuts   import render
from django.views       import View
from django.http        import HttpResponse, JsonResponse
from django.db.models   import Q

from .models            import User
```
임포트 순서는 다음과 같습니다. 
1. 파이썬 모듈
2. 장고 모듈
3. 사용자화된 모듈 
각 종류별 한줄띄우기로 구분해서 임포트 정리해주세요.

2021-02-06 05:12 UTC, ulfrid commented
미션3 과제내용 다시 확인하시고 블로그 과제 수행하세요~!

2021-03-04 01:04 UTC, merged