[허정윤] Mission 1 : 초기 세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #210
Opened 2021-02-01 11:55 UTC by banana1019

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
Django 초기 세팅
		 
## 수정 사항들 자세한 내용
- project_westagram/settings.py 수정
- project_westagram/urls.py 수정
- user/views.py 수정

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-01 15:03 UTC, ulfrid requested changes
수정 부탁드립니다~!

2021-02-01 15:03 UTC, ulfrid commented on students/17th/hkk/jeongyun-heo/westagram/settings.py
> +SECRET_KEY = '9pva8z!xze=cryo-)d-m0@z_x5b0#$@qee9=#*os9ts6j=rrh5'
SECRET_KEY는 보안상 깃헙에 공개되면 이슈가 되는 사항입니다. 노출되면 보안취약점이 되는 부분이죠.
그래서 가이드해드렸던, manage.py 와 같은 경로에 my_settings.py를 작성하시고, 거기에 SECRET 코드를 작성한뒤 settings.py에서 import 후 적용해주셔야 합니다.

2021-02-01 15:03 UTC, ulfrid commented on students/17th/hkk/jeongyun-heo/westagram/settings.py
> +}
DATABASE도 MySQL 적용하시고~ 마찬가지로 접속정보는 my_settings.py에 작성후 임포트 해서 적용 부탁드립니다.

2021-02-01 15:03 UTC, ulfrid commented on students/17th/hkk/jeongyun-heo/westagram/urls.py
> +"""
주석 제거해주세요.

2021-02-02 06:37 UTC, banana1019 commented on students/17th/hkk/jeongyun-heo/westagram/settings.py
> +SECRET_KEY = '9pva8z!xze=cryo-)d-m0@z_x5b0#$@qee9=#*os9ts6j=rrh5'
SECRET_KEY를 my_settings.py로 옮겼습니다!

2021-02-02 06:38 UTC, banana1019 commented on students/17th/hkk/jeongyun-heo/westagram/settings.py
> +}
DATABASE도 my_settings.py로 옮겼습니다!

2021-02-02 06:38 UTC, banana1019 commented on students/17th/hkk/jeongyun-heo/westagram/urls.py
> +"""
주석 제거했습니다~

2021-02-02 06:43 UTC, ulfrid commented
통과 입니다~! 다음 미션 진행해주세요~🥳

2021-02-04 02:03 UTC, ulfrid requested changes
확인 부탁드립니다~!

2021-02-04 02:49 UTC, banana1019 commented on students/17th/hkk/jeongyun-heo/user/views.py
> +                if len(password) < 8:
아하.. 회원가입 할 때만 필요한 거라서 클래스 선언부 아래에 추가했습니다!

2021-02-04 04:29 UTC, banana1019 commented on students/17th/hkk/jeongyun-heo/user/views.py
> +                    return JsonResponse({'message': 'ID already exists'}, status=400)
음.. 그러면 이런 경우에는 status code로만 응답해주는 게 일반적인 건가요??!! 일단 말씀하신대로 메세지 부분 수정했습니다~~

2021-02-04 07:38 UTC, ulfrid commented
미션2 통과입니다~! 미션 3 진행 부탁드립니다~!

2021-02-04 15:09 UTC, ulfrid requested changes
확인 부탁드립니다.

2021-02-04 15:09 UTC, ulfrid commented on students/17th/hkk/jeongyun-heo/user/views.py
> +                    return HttpResponse(status=400)
앞의 리턴 다음에 이런 리턴은 소용이 없죠~! 대체해보고 싶으신 거였나요? 확인 부탁드립니다~!

2021-02-04 15:09 UTC, ulfrid commented on students/17th/hkk/jeongyun-heo/user/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
```suggestion
            if not User.objects.filter(email=email).exists():
                return JsonResponse({'message': 'INVALID_USER'}, status=401)
            user = User.objects.get(email=email)
```
이렇게 해볼수도 있겠죠?

2021-02-04 15:09 UTC, ulfrid commented on students/17th/hkk/jeongyun-heo/user/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
```suggestion
            if user.password == password:
                return JsonResponse({'message': 'SUCCESS'}, status=200)
            return JsonResponse({'message': 'INVALID_USER'}, status=401)
```
else: 는 생략해줍시다~

2021-02-04 15:58 UTC, banana1019 commented on students/17th/hkk/jeongyun-heo/user/views.py
> +                    return HttpResponse(status=400)
HttpResponse 지우는 걸 깜박했습니다.. 지웠습니다!!

2021-02-04 15:59 UTC, banana1019 commented on students/17th/hkk/jeongyun-heo/user/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
오오 감사합니다!! 수정하도록 하겠습니다~~

2021-02-04 15:59 UTC, banana1019 commented on students/17th/hkk/jeongyun-heo/user/views.py
> +                return JsonResponse({'message': 'INVALID_USER'}, status=401)
새로운 것들을 알게 됐습니다!! 수정하도록 하겠습니다~~

2021-02-05 02:56 UTC, ulfrid commented
블로그 제출해주시면 통과 입니다~!

2021-02-06 14:59 UTC, banana1019 commented
https://velog.io/@banana/Westagram-Mission-3.-에러날-수-있는-경우의-수

블로그 링크입니다~~

2021-02-07 06:20 UTC, ulfrid commented
통과입니다~! 이후 미션 진행해주세요~! 설연휴 잘보내세요 정윤님~~!

2021-03-04 01:04 UTC, merged