[김치오] Mission 1 : 초기 세팅 완료
wecode-bootcamp-korea/westagram-backend pull request #211
Opened 2021-02-02 06:41 UTC by ScottieKim

- 프로젝트 생성과 앱 생성(초기세팅)

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-02 06:50 UTC, ulfrid requested changes
확인해주세요~!

2021-02-02 06:50 UTC, ulfrid commented on students/17th/team1/ChiohKim/westagram/settings.py
> +}
데이타베이스 설정도 들어와야 할 것 같은데요~

2021-02-02 06:50 UTC, ulfrid commented on students/17th/team1/ChiohKim/westagram/urls.py
> +
주석은 제거해주세요~!

2021-02-02 06:50 UTC, ulfrid commented on students/17th/team1/ChiohKim/my_setting.py
> +
파일이름이 정확히 my_settings.py여야 깃에 포함이 안됩니다. 지금은 보안 이슈네요. 변경 부탁드리고 여기에 DB접속 정보도 기록해서 settings.py에 적용해주세요~~!

2021-02-02 07:08 UTC, ScottieKim commented on students/17th/team1/ChiohKim/westagram/settings.py
> +}
네 수정하겠습니다!

2021-02-02 07:09 UTC, ScottieKim commented on students/17th/team1/ChiohKim/westagram/urls.py
> +
네 제거하겠습니다~!

2021-02-02 07:09 UTC, ScottieKim commented on students/17th/team1/ChiohKim/my_setting.py
> +
넵 적용했습니다~!

2021-02-02 07:42 UTC, ulfrid commented
합격! 다음 미션 진행해주세요~!

2021-02-04 02:14 UTC, ulfrid requested changes
확인 바랍니다~!

2021-02-04 02:14 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/models.py
> +    #start_date = models.DateTimeField(auto_now_add=True)
당장 사용하지 않는다면 주석은 포함되지 않아야 합니다.

2021-02-04 02:14 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/models.py
> +
회원관리라는 입장에서 시간 기록을 하는게 좋습니다. 위의 주석은 그것을 시도하려고 하셨던것 같은데, 
created_at, updated_at 등 장고 모델에서 시간관리할때 그냥 필수품 처럼 만드는 변수명입니다. 
```
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeFiedl(auto_now=True)
```
위의 두 필드에 적용한 옵션이 어떤 역할을 하는 지 직접 조사해보시고, 적용 부탁드립니다.

2021-02-04 02:14 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +            if Account.objects.filter(email=signup_data['email']).exists() or Account.objects.filter(phonenumber=signup_data['phonenumber']).exists() or Account.objects.filter(name=signup_data['name'
위에 Q객체를 임포트 하셨는데 이 코드도 줄여 볼 수 있지 않을까요?

2021-02-04 02:14 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +                return JsonResponse({"message":"EXIST_USER"}, status=400) #에러메세지에도 컨벤션이있나요?
```suggestion
                return JsonResponse({"message":"EXIST_USER"}, status=400) 
```
#에러메세지에도 컨벤션이있나요? 
네 있습니다. 사실 응답은 status code  면 충분합니다. 
하지만 우리는 메세지를 제공하죠 이는 보다 분별력있는 에러 상태 파악을 제공하도록 하는것입니다.
그렇다면 이메세지는 정말 메세지 일까요? 아닙니다. 메세지로 된 코드입니다.
그렇기 때문에 긴 설명이 아닌 단축된 문자코드로서 메세지를 제공하고 수신하는 측(즉, 프론트)과 협의 해야합니다.
아래의 메세지들도 변경 부탁드립니다.

2021-02-04 02:14 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +            if len('password') < 8:
```suggestion
            if len('password') < MINIMUM_PASSWORD_LENGTH:
```
8 과 같은 비교값의 경우 하드코딩 할 수 도 있지만, 장기적으로 보자면 추후 수정시 직접 로직을 수정하러 와야하는 번거로움이 있죠. 
잘 변하지 않을 기준 값이지만, 여러 곳에서 쓰이게 된다면 추후에는 번거로움이 생깁니다. 이러한 기준값을 상수로 선언해서 관리하는 것을 추천드립니다.

상수 선언은 파일 상단 import 열 하단, 클래스내부에서만 사용될 경우 클래스 선언부 바로 아래, 보안이 중요한 경우, 설정 파일에 선언 후 임포트 하는 방법등을 선택해서 사용할 수 있습니다!

2021-02-04 02:47 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/views.py
> +            if len('password') < 8:
수정했습니다!

2021-02-04 02:47 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/views.py
> +                return JsonResponse({"message":"EXIST_USER"}, status=400) #에러메세지에도 컨벤션이있나요?
넵 수정했습니다!

2021-02-04 02:47 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/views.py
> +            if Account.objects.filter(email=signup_data['email']).exists() or Account.objects.filter(phonenumber=signup_data['phonenumber']).exists() or Account.objects.filter(name=signup_data['name'
넵 줄였습니다!

2021-02-04 02:47 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/models.py
> +
넵 적용했습니다!

2021-02-04 02:47 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/models.py
> +    #start_date = models.DateTimeField(auto_now_add=True)
넵!

2021-02-04 03:03 UTC, ulfrid requested changes
주석 처리된것 + 포함되지 않아야 할 것 모두 제거해주세요.

2021-02-04 03:03 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +        MINIMUM_PASSWORD_LENGTH = 8
아래 리뷰를 다시 읽어보시고 적용 부탁드립니다.

2021-02-04 03:03 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +#           if Account.objects.filter(email=signup_data['email']).exists() or Account.objects.filter(phonenumber=signup_data['phonenumber']).exists() or Account.objects.filter(nickname=signup_data['n
제거해주세요

2021-02-04 03:03 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +'''
작업할때 그때 당시의 작업 외에 다른 작업은 아에 포함시키지 않아야 합니다.

2021-02-04 03:03 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/models.py
> +# Create your models here.
제거해주세요~!

2021-02-04 03:55 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/views.py
> +        MINIMUM_PASSWORD_LENGTH = 8
체크를 못했네요 앞으론 하나씩 다시 체크해보겠습니다 적용했습니다!

2021-02-04 03:55 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/views.py
> +#           if Account.objects.filter(email=signup_data['email']).exists() or Account.objects.filter(phonenumber=signup_data['phonenumber']).exists() or Account.objects.filter(nickname=signup_data['n
제거했습니다!

2021-02-04 03:56 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/views.py
> +'''
넵 앞으론 포함시키지 않겠습니다

2021-02-04 03:56 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/models.py
> +# Create your models here.
제거했습니다!

2021-02-04 07:37 UTC, ulfrid requested changes
정리만 해주시면 통과될것 같습니다~!

2021-02-04 07:37 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +        MINIMUM_PASSWORD_LENGTH = 8
```suggestion
 MINIMUM_PASSWORD_LENGTH = 8
 
class SignupView(View):
    def post(self, request):
        signup_data = json.loads(request.body)
       
```

2021-02-04 07:37 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +                return JsonResponse({"message":"INVALID_EMAIL"}, status=400)
```suggestion
            if Account.objects.filter(Q(email=signup_data['email']) | Q(phonenumber=signup_data['phonenumber'])|Q(nickname=signup_data['nickname'])):
                return JsonResponse({"message":"EXIST_USER"}, status=400) 
            
            if len('password') < MINIMUM_PASSWORD_LENGTH:
                return JsonResponse({"message":"INVALID_PASSWORD"}, status=400)
            
            if '@' or '.' not in email:
                return JsonResponse({"message":"INVALID_EMAIL"}, status=400) 
```

2021-02-04 07:37 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +
빈줄 제거해주세요~!

2021-02-04 09:37 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/views.py
> +
ㅜㅜㅜㅜ 지훈님 컨벤션 체크 항상 하겠습니다 윽

2021-02-04 09:42 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/views.py
> +                return JsonResponse({"message":"INVALID_EMAIL"}, status=400)
지훈님 식사 맛있게하셨나요~?

코드가 효율적인지 체크하는 방법을 아까 말씀해주셨는데, 질문드리고싶습니다.
try 문안에 payload 데이터를 처음에 받는 곳들을 선언해주고,
if문들로 오류 걸러주고,
그다음 create하는게 더 효율적인 코드인가요??

생각해보니, 데이터를 먼저 주는지안주는지 체크하고,
오류들은 따로 처리되고,
create할때 오류나는지 처리되면 
읽기 좋을것 같다는 생각이 들었습니다!

혹시 시간되시면 답변부탁드립니다 !!

2021-02-04 10:18 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +                return JsonResponse({"message":"INVALID_EMAIL"}, status=400)
주는지 안주는지 여부는 결국 None 인지 아닌지를 보는것인데 
사실상 먼저 받아서 검사하는 과정은 동일 합니다. 
그래서 항상 데이터를 수령하면 키값에 대해 검사하는 것이죠.

2021-02-04 10:44 UTC, ulfrid requested changes
고치시면 통과 입니다.

2021-02-04 10:44 UTC, ulfrid commented on students/17th/team1/ChiohKim/user/views.py
> +        MINIMUM_PASSWORD_LENGTH = 8
계속 여기 있네요~ ㅡㅜ

2021-02-05 04:28 UTC, ScottieKim commented on students/17th/team1/ChiohKim/user/views.py
> +                return JsonResponse({"message":"INVALID_EMAIL"}, status=400)
아하 이해됐습니다 답변감사합니다!!

2021-02-05 04:41 UTC, ulfrid commented
미션 3에는 블로그 과제가 있습니다 제출해주세요~!

2021-03-04 01:04 UTC, merged